### PR TITLE
remove src/ocp-network-split submodule

### PR DESCRIPTION
**Pull request by dahorak**
This git submodule `src/ocp-network-split` was added to this repository accidentally, removing it.

### CODE REVIEW

**Review by vavuthu — APPROVED** [review]

**Comment by sagihirshfeld** [comment]
Looks like it failed due to https://github.com/red-hat-storage/ocs-ci/issues/11012. The issue has nothing to do with the removal of this module, since its also been failing unrelated verifications: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/44725/testReport/

**Pull request merged**
