### PR TITLE
Pytest jira plugin

### PR DESCRIPTION
**Pull request by petr-balogh**
Ticket:
https://issues.redhat.com/browse/OCSQE-2441

### CODE REVIEW

**Comment by petr-balogh** [comment]
Verified here:
https://url.corp.redhat.com/ddc95a0

**Comment by petr-balogh** [comment]
Verification without run=False argument as I moved it to jira.cfg and set it there to False by default:
https://url.corp.redhat.com/34e0e87

**Comment by petr-balogh** [comment]
Tested with:
```
   @acceptance
    @pytest.mark.jira("DFBUGS-31")  # Just for testing purpose, will remove before merge


    @acceptance
    @pytest.mark.jira("DFBUGS-3")  # Just for testing purpose, will remove before merge
 ```
 In `tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py`
 With this testing commit:
 https://github.com/red-hat-storage/ocs-ci/pull/10214/commits/9a03b90fd7f04b90c666f3d2f6a6cf676959a57d
 
 Which I am removing from PR now.

**Review by vavuthu — APPROVED** [review]

**Review by ebenahar — APPROVED** [review]

**Pull request merged**
