### PR TITLE
[WIP] Change pools name in PG WA

### PR DESCRIPTION
**Pull request by ebenahar**
Signed-off-by: Elad Ben Aharon <ebenahar@redhat.com>

### CODE REVIEW

**Comment by ebenahar** [comment]
Trying to run this manually, hitting the following:

[root@ip-10-0-160-124 /]# for POOL in rook-ceph-cephblockpool rook-ceph-cephfilesystem-metadata rook-ceph-cephfilesystem-data0 ; do for PGN in pg_num pgp_num; do ceph osd pool set ${POOL} ${PGN} 100;done;done
set pool 1 pgp_num to 100
set pool 2 pgp_num to 100
Error ERANGE: pool id 3 pg_num 100 size 3 would mean 924 total pgs, which exceeds max 750 (mon_max_pg_per_osd 250 * num_in_osds 3)
Error EINVAL: specified pgp_num 100 > pg_num 32

**Comment by ebenahar** [comment]
Now, with 64, everything works fine:

[root@ip-10-0-160-124 /]# for POOL in rook-ceph-cephblockpool rook-ceph-cephfilesystem-metadata rook-ceph-cephfilesystem-data0 ; do for PGN in pg_num pgp_num; do ceph osd pool set ${POOL} ${PGN} 64;done;done
set pool 1 pg_num to 64
set pool 1 pgp_num to 64
set pool 2 pg_num to 64
set pool 2 pgp_num to 64
set pool 3 pg_num to 64
set pool 3 pgp_num to 64

**Comment by vasukulkarni** [comment]
I suggest we enable pg_autoscaler and try now, I was doing the same as I saw my jenkins job failed, It will work for all pools and scales automatically.

**Comment by vasukulkarni** [comment]
Here: https://github.com/red-hat-storage/ocs-ci/pull/710

**Comment by vasukulkarni** [comment]
Closing this now, seems to be working fine with latest build with pg_autoscale enabled.

**Pull request closed without merging**
