### PR TITLE
Add timeout (default 600 seconds) for exec_oc_debug_cmd()

### PR DESCRIPTION
**Pull request by sidhant-agrawal**
Fixes: #1359
 Add timeout parameter to ocs_ci/ocs/ocp.py: exec_oc_debug_cmd()

### CODE REVIEW

**Comment by sidhant-agrawal** [comment]
@ramkiperiy FYI

**Comment by vasukulkarni** [comment]
verified ?

**Comment by sidhant-agrawal** [comment]
@ramkiperiy Can you please suggest which tier or specific test can be run for verifying this PR?

**Comment by sidhant-agrawal** [comment]
> PR validation [Job PASSED](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/947//testReport).

Deployment of AWS-UPI-3AZ-RHEL7-3M-3W passed.
This function is currently being used while deploying with RHEL worker nodes.

**Pull request merged**
