### PR TITLE
add --show-progress as default option to ocs-ci

### PR DESCRIPTION
**Pull request by vavuthu**
Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Review by petr-balogh — APPROVED** [review]

**Comment by vavuthu** [comment]
> PR validation on existing cluster
> 
> Cluster Name: vavuthusp1 Cluster Configuration: PR Test Suite: acceptance PR Test Path: tests/ Additional Test Params: OCP VERSION: 4.16 OCS VERSION: 4.16 tested against branch: master
> 
> [Job UNSTABLE](https://url.corp.redhat.com/0542724) (some or all tests failed).

4 TC's are failed which is not related to this PR.

logs the TC's progress in job as expected.

```
2024-06-14 10:44:43  _ 27 of 34 completed, 19 Pass, 4 Fail, 4 Skip, 0 XPass, 0 XFail, 0 Error, 0 ReRun _
```

**Review by jilju — APPROVED** [review]

**Pull request merged**
