### PR TITLE
Eliminate use of ibm storage cluster yaml

### PR DESCRIPTION
**Pull request by lukebrowning**
Use default ocs-ci storage cluster yaml instead.  The IBM yaml has
two problems: 1) includes node placement for each device set.  2) has
three devicesets one per worker node and storage is not replicated.

With OCS 4.7 the OCS deployment fails.  I ran an experiment just removing
the node bindings / affinity and cluster create succeeded, so there is a
conflict in the use of node bindings between it and the calling code osd
prepare / manager code.

Secondary goal here is to minimize IBM Power specific code.

Signed-off-by: Luke Browning <lukebrowning@us.ibm.com>

### CODE REVIEW

**Comment by lukebrowning** [comment]
@zmc @vasukulkarni @sapillai 

Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1934668

**Comment by gitsridhar** [comment]
@lukebrowning looks good to me, looking at the changes, you have removed all custom logic for constants.IBM_POWER_PLATFORM in the OCS deployment.

**Comment by lsmcfadden** [comment]
@RazTamir who from your team should review?

**Comment by lsmcfadden** [comment]
@zmc @vasukulkarni @clacroix12 any review comments?

**Comment by lukebrowning** [comment]
Just rebased to latest master

**Review by clacroix12 — COMMENTED** [review]
I'm not seeing any glaring issues with the changes but we should do some deployment testing to ensure things are good. I think we should test both the IBM Power deployment and a standard deployment to AWS or VSphere

**Comment by lsmcfadden** [comment]
@clacroix12 so will you be doing some deployment testing (esp AWS/VSphere) or you are asking us to test and upload results here?

**Comment by lukebrowning** [comment]
I have tested this on a power server using ocs-ci to deploy ocs on a ocp 4.7 cluster based on KVM/libvirt VMs. 
[luke@nx143-ahv single]$ oc get cephcluster --namespace openshift-storage
NAME                             DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH
ocs-storagecluster-cephcluster   /var/lib/rook     3          16m   Ready   Cluster created successfully   HEALTH_OK
[luke@nx143-ahv single]$ oc get csv -A
NAMESPACE                              NAME                                           DISPLAY                       VERSION                 REPLACES   PHASE
openshift-local-storage                local-storage-operator.4.7.0-202103060100.p0   Local Storage                 4.7.0-202103060100.p0              Succeeded
openshift-operator-lifecycle-manager   packageserver                                  Package Server                0.17.0                             Succeeded
openshift-storage                      ocs-operator.v4.7.0-299.ci                     OpenShift Container Storage   4.7.0-299.ci                       Succeeded
[luke@nx143-ahv single]$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.2     True        False         54m     Cluster version is 4.7.2

**Comment by clacroix12** [comment]
> @clacroix12 so will you be doing some deployment testing (esp AWS/VSphere) or you are asking us to test and upload results here?

This is generally under the responsibilities of the PR author to do. However, I can kick off a vsphere deployment test that will comment with the results.

**Review by clacroix12 — APPROVED** [review]

**Comment by lukebrowning** [comment]
@vasukulkarni Please review this PR.   It has been tested now.

**Review by vasukulkarni — APPROVED** [review]

**Comment by lsmcfadden** [comment]
> > @clacroix12 so will you be doing some deployment testing (esp AWS/VSphere) or you are asking us to test and upload results here?
> 
> This is generally under the responsibilities of the PR author to do. However, I can kick off a vsphere deployment test that will comment with the results.

Thanks for explaining it to me.

**Comment by petr-balogh** [comment]
Opened issue for that

**Pull request merged**
