### PR TITLE
Updated requests dependency version to 2.23.0

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #2086 

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
Please run tier1 tests too just to be sure.

**Comment by clacroix12** [comment]
> Please run tier1 tests too just to be sure.

I'm running a deployment test to exercise the `requests` library and ensure we can execute requests without issue. Do we really need to run all of tier1 as well?

**Comment by vasukulkarni** [comment]
> > Please run tier1 tests too just to be sure.
> 
> I'm running a deployment test to exercise the `requests` library and ensure we can execute requests without issue. Do we really need to run all of tier1 as well?

I think its worth running for library changes, not sure AWS class uses its but we can be sure.

**Comment by clacroix12** [comment]
@vasukulkarni as per our discussion and given this is blocking executions Im marking this as verified. We can continue to monitor tier1 and address any issues this change might bring up.

**Pull request merged**
