### PR TITLE
Adding retry mechanism for setup_persistent_monitoring

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #4787 

Signed-off-by: vavuthu <vavuthu@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
Thanks for the PR @vavuthu , how much waiting time in total this adds?

@umangachapagain

**Comment by agarwal-mudit** [comment]
@ebenahar @vasukulkarni Can we please merge it quickly, this blocks ci for ODF 4.9

**Comment by vavuthu** [comment]
> Thanks for the PR @vavuthu , how much waiting time in total this adds?
> 
> @umangachapagain

In total 93 sec, 5 retries with delay of 3 seconds ( so each retry it will double the delay like 3, 6, 12, 24, 48 ). Not sure if that sufficient or not. I have triggered verification job here: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/5621/console

**Comment by agarwal-mudit** [comment]
> > Thanks for the PR @vavuthu , how much waiting time in total this adds?
> > @umangachapagain
> 
> In total 93 sec, 5 retries with delay of 3 seconds ( so each retry it will double the delay like 3, 6, 12, 24, 48 ). Not sure if that sufficient or not. I have triggered verification job here: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/5621/console

It should be good enough

**Comment by umangachapagain** [comment]
looks good to me.

will keep an eye on validation test.

**Comment by vavuthu** [comment]
> > > Thanks for the PR @vavuthu , how much waiting time in total this adds?
> > > @umangachapagain
> > 
> > 
> > In total 93 sec, 5 retries with delay of 3 seconds ( so each retry it will double the delay like 3, 6, 12, 24, 48 ). Not sure if that sufficient or not. I have triggered verification job here: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/5621/console
> 
> It should be good enough

my bad, its 46 sec ( 1, 3, 6, 12, 24, )

**Comment by agarwal-mudit** [comment]
> 
> my bad, its 46 sec ( 1, 3, 6, 12, 24, )
Would be the best if we can make it ~ 1 minute

**Comment by vavuthu** [comment]
> > my bad, its 46 sec ( 1, 3, 6, 12, 24, )
> > Would be the best if we can make it ~ 1 minute

done

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Review by ebenahar — APPROVED** [review]

**Review by shyRozen — APPROVED** [review]

**Pull request merged**
