### PR TITLE
Add second attempt to fetch the mountpoints from the node

### PR DESCRIPTION
**Pull request by jilju**
Workaround the issue #7837 by adding a second attempt to get the mountpoints from a node using a different command.
Reduced timeout to avoid more delay in waiting.

The test cases that fails are present in release-4.15 and older release branches only.

### CODE REVIEW

**Comment by jilju** [comment]
Tests that are fixed by this PR:
1. tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
2. tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py

**Comment by jilju** [comment]
> PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: tier4c PR Test Path: tests/ Additional Test Params: OCP VERSION: 4.15 OCS VERSION: 4.15 tested against branch: release-4.15
> 
> [Job UNSTABLE](https://url.corp.redhat.com/342ebb3) (some or all tests failed).

This is entire tier4c run. The failures are not related to the change and are matching the tier4c production runs.

There are instances in this run to verify this PR
```
2024-08-28 14:48:30  05:18:30 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc debug nodes/compute-2 --to-namespace=openshift-storage -- df
2024-08-28 14:50:36  05:20:30 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc debug nodes/compute-2 --to-namespace=openshift-storage -- mount
2024-08-28 14:50:36  05:20:31 - MainThread - ocs_ci.utility.utils - WARNING  - Command stderr: Starting pod/compute-2-debug-gxfp6 ...
2024-08-28 14:50:36  To use host binaries, run `chroot /host`
2024-08-28 14:50:36  
2024-08-28 14:50:36  Removing debug pod ...
2024-08-28 14:50:36  
2024-08-28 14:50:36  05:20:31 - MainThread - tests.functional.pv.pv_services.test_resource_deletion_during_pvc_pod_creation_and_io - INFO  - Verified: mount points are removed from nodes after deleting the pods
```
The second attempt using 'mount' did not timeout.

**Review by vavuthu — APPROVED** [review]

**Pull request merged**
