### PR TITLE
Adjust send_rpc_query to send RPC requests via the NooBaa CLI

### PR DESCRIPTION
**Pull request by sagihirshfeld**
In 4.14 the URL that was used to make NooBaa RPC requests has been removed, so this PR adjusts the method that was used to make these calls, so it uses the NooBaa CLI instead.

See this google chat thread for details:
https://url.corp.redhat.com/c4c3508

### CODE REVIEW

**Review by mashetty330 — DISMISSED** [review]
lgtm

**Review by ebenahar — APPROVED** [review]

**Comment by vavuthu** [comment]
@sagihirshfeld Could you test deployment for both 4.14 and 4.13

**Review by vavuthu — APPROVED** [review]

**Review by petr-balogh — APPROVED** [review]
Can you please create also an issue for W/A ? To track it and don't forget to remove a W/A ?

**Comment by sagihirshfeld** [comment]
> Can you please create also an issue for W/A ? To track it and don't forget to remove a W/A ?

Is https://github.com/red-hat-storage/ocs-ci/issues/7803 ok? I'm not sure what's the right procedure for tracking W/A's

**Comment by sagihirshfeld** [comment]
@vavuthu I tested both 4.13 and 4.14 deployments with this PR's branch:

- 4.13: https://url.corp.redhat.com/1c011b7
- 4.14: https://url.corp.redhat.com/fad0c03

Both deployments were successful

**Pull request merged**
