### PR TITLE
Fix version comparison for more modules

### PR DESCRIPTION
**Pull request by petr-balogh**
I am opening the second PR with more modules changed here:
https://github.com/red-hat-storage/ocs-ci/pull/4872/

The first PR I will let only few commits related to deployment and version module

### CODE REVIEW

**Review by ramkiperiy — DISMISSED** [review]
LGTM

**Comment by clacroix12** [comment]
@petr-balogh Maybe I'm missing something but if the `version` utility module and its corresponding unit tests were added in #4872 why are they also in this PR?

**Comment by petr-balogh** [comment]
> @petr-balogh Maybe I'm missing something but if the `version` utility module and its corresponding unit tests were added in #4872 why are they also in this PR?

@clacroix12 this PR was based on previous one where I didn't touch the original commits as this has to be dependent on that. As commits are same github/git should merge only relevant commits out of this PR. I can do rebase as the previous PR got merged so UI will not show the commits which are already merged from previous one.

**Comment by petr-balogh** [comment]
I just did rebase on the master now, checked the verification job and doesn't look like it's related to the change.

**Review by dahorak — APPROVED** [review]

**Review by ramkiperiy — APPROVED** [review]
LGTM

**Pull request merged**
