### PR TITLE
Skip test_automated_recovery_from_stopped_node_and_start failed on Compact mode deployments

### LINKED ISSUE #10088: test_automated_recovery_from_stopped_node_and_start failed on VSphere-IPI Compact Mode deployments
Multiple failures seen on the above config.
https://url.corp.redhat.com/1a85353
https://url.corp.redhat.com/952aee3

Returns
```
machine_set = None


def get_ready_replica_count(machine_set):
    """
    Get replica count which are in ready state in a machine set

    Args:
        machine_set (str): Machineset name

    Returns:
        ready_replica (int): replica count which are in ready state
    """
    machinesets_obj = OCP(
        kind=constants.MACHINESETS, namespace=constants.OPENSHIFT_MACHINE_API_NAMESPACE
    )
    return (

      machinesets_obj.get(resource_name=machine_set)
        .get("status")
        .get("readyReplicas")
    )
E       AttributeError: 'NoneType' object has no attribute 'get'



ocs_ci/ocs/machine.py:1044: AttributeError


2024-05-17 05:22:39
```

### PR DESCRIPTION
**Pull request by am-agrawa**
fixes #10088

### CODE REVIEW

**Comment by am-agrawa** [comment]
Skipped here- https://url.corp.redhat.com/d9e570f

**Review by prsurve — APPROVED** [review]

**Review by vavuthu — APPROVED** [review]

**Comment by am-agrawa** [comment]
4.15 backport [pr](https://github.com/red-hat-storage/ocs-ci/pull/10231)

**Comment by am-agrawa** [comment]
4.16 backport [pr](https://github.com/red-hat-storage/ocs-ci/pull/10255)

**Pull request merged**
