### PR TITLE
WIP: Reduce IO during upgrade

### PR DESCRIPTION
**Pull request by fbalak**
Signed-off-by: Filip Balak <fbalak@redhat.com>

### CODE REVIEW

**Review by ebenahar — APPROVED** [review]

**Comment by ebenahar** [comment]
@fbalak should we also remove the skip decorator from the corresponding test cases?

**Review by petr-balogh — APPROVED** [review]

**Comment by petr-balogh** [comment]
> @fbalak should we also remove the skip decorator from the corresponding test cases?

I guess it can be done in different PR @ebenahar .
Also after your PR is merged.

**Comment by fbalak** [comment]
Sounds good. The skip is present only if --io-in-bg param is present.

**Review by AviadP — APPROVED** [review]

**Comment by petr-balogh** [comment]
I see that upgrade job failed anyway.. so probably this still not works even after reduce the numbers of jobs?

**Comment by petr-balogh** [comment]
Adding WIP prefix to prevent this to be merged for now till we will agree on merge it as it is or have some verification job passing.

**Comment by petr-balogh** [comment]
@fbalak any update on this? Have you proceeded with some testing on this? Anyway.. needs rebase.

**Pull request closed without merging**
