### PR TITLE
include back slash for url

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #10179 

Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Review by petr-balogh — APPROVED** [review]

**Comment by vavuthu** [comment]
both jobs which download GA version and nightly versions are successfully downloaded. 

```
2024-07-25 16:03:55  06:33:55 - MainThread - ocs_ci.utility.utils - INFO  - Downloading openshift client (4.17.0-0.nightly-2024-07-25-050214).
2024-07-25 16:03:55  06:33:55 - MainThread - ocs_ci.utility.utils - INFO  - Directory '/home/jenkins/bin' successfully created.
2024-07-25 16:03:55  06:33:55 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: ldd --version ldd
2024-07-25 16:03:56  06:33:56 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: tar xzvf openshift-client.tar.gz oc kubectl
2024-07-25 16:03:57  06:33:57 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: /home/jenkins/bin/oc version --client
2024-07-25 16:03:57  06:33:57 - MainThread - ocs_ci.utility.utils - INFO  - OpenShift Client version: Client Version: 4.17.0-0.nightly-2024-07-25-050214
2024-07-25 16:03:57  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

```
2024-07-25 16:05:34  06:35:34 - MainThread - ocs_ci.utility.utils - INFO  - Downloading openshift client (4.16.3).
2024-07-25 16:05:34  06:35:34 - MainThread - ocs_ci.utility.utils - INFO  - Directory '/home/jenkins/bin' successfully created.
2024-07-25 16:05:34  06:35:34 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: ldd --version ldd
2024-07-25 16:05:38  06:35:37 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: tar xzvf openshift-client.tar.gz oc kubectl
2024-07-25 16:05:39  06:35:39 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: /home/jenkins/bin/oc version --client
2024-07-25 16:05:39  06:35:39 - MainThread - ocs_ci.utility.utils - INFO  - OpenShift Client version: Client Version: 4.16.3
2024-07-25 16:05:39  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

Hence marking as verified

**Review by dahorak — APPROVED** [review]

**Pull request merged**
