### PR TITLE
Adding device size for production environments

### PR DESCRIPTION
**Pull request by vavuthu**
Adding device size for production environments

Signed-off-by: vavuthu <vavuthu@redhat.com>

### CODE REVIEW

**Comment by nehaberry** [comment]
@vavuthu looks good and reasonable.. So do we need to pass this conf file during deployment ?

**Comment by clacroix12** [comment]
@vavuthu Should this key/value be added to our already existing production configuration files as well?

**Comment by vavuthu** [comment]
> @vavuthu looks good and reasonable.. So do we need to pass this conf file during deployment ?

yes. we need to pass the conf during deployment incase if we need production device size

**Comment by vavuthu** [comment]
> @vavuthu Should this key/value be added to our already existing production configuration files as well?

Since we have different platforms and each platform has their own key/values, I think its good to maintain it as a separate file, so that if we have any changes in future, we can change it in one place.

**Comment by vavuthu** [comment]
Jenkins Job: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/1762/console

Volumes are created with production device_size:


vavuthu-ocsci-chjt4-dynamic-pvc-30ac0b9f-fa51-11e9-ba52-0a1df4dc53d4 | vol-08a72931d6d8b158a | 1024 GiB | gp2 | 3072 |   | October 29, 2019 at 7:07:04 PM UTC+5:30 | us-east-2a | in-use | None | i-0ee6c80bb2580691d (vavuthu-ocsci-chjt4-worker-us-east-2a-bbt9f):/dev/xvdbm (attached) |   | Okay | Encrypted | a05364b8-a0a4-46cc-9c9f-159015648822 | aws/ebs
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | vavuthu-ocsci-chjt4-dynamic-pvc-30aa7a6b-fa51-11e9-ba52-0a1df4dc53d4 | vol-0db0ab11cc819fe59 | 1024 GiB | gp2 | 3072 |   | October 29, 2019 at 7:07:03 PM UTC+5:30 | us-east-2c | in-use | None | i-018469a9621af3a2f (vavuthu-ocsci-chjt4-worker-us-east-2c-sb9lj):/dev/xvdbe (attached) |   | Okay | Encrypted | a05364b8-a0a4-46cc-9c9f-159015648822 | aws/ebs
  | vavuthu-ocsci-chjt4-dynamic-pvc-30a8dfb6-fa51-11e9-ba52-0a1df4dc53d4 | vol-088269985f7761109 | 1024 GiB | gp2 | 3072 |   | October 29, 2019 at 7:07:03 PM UTC+5:30 | us-east-2b

```
$ oc get pvc -n openshift-storage
NAME                          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
db-noobaa-core-0              Pending                                                                        rook-ceph-ceph-rbd   19m
example-deviceset-0-0-bkztl   Bound     pvc-30a8dfb6-fa51-11e9-ba52-0a1df4dc53d4   1Ti        RWO            gp2                  16m
example-deviceset-1-0-gj9bc   Bound     pvc-30aa7a6b-fa51-11e9-ba52-0a1df4dc53d4   1Ti        RWO            gp2                  16m
example-deviceset-2-0-r6vkj   Bound     pvc-30ac0b9f-fa51-11e9-ba52-0a1df4dc53d4   1Ti        RWO            gp2                  16m
rook-ceph-mon-a               Bound     pvc-dba8966c-fa50-11e9-ba52-0a1df4dc53d4   10Gi       RWO            gp2                  19m
rook-ceph-mon-b               Bound     pvc-df00fed1-fa50-11e9-ba52-0a1df4dc53d4   10Gi       RWO            gp2                  18m
rook-ceph-mon-c               Bound     pvc-e20a58b7-fa50-11e9-ba52-0a1df4dc53d4   10Gi       RWO            gp2                  18m
$ 
```

Its failed with known bug. Hence marking as verified.

**Comment by vasukulkarni** [comment]
@tiffanyn108 @SvetlanaRedHat  FYI

**Pull request merged**
