### PR TITLE
General function to check test results

### PR DESCRIPTION
**Pull request by Avilir**
This PR making the function which checking the test results an pushing them to the performance dashboard as general function to prevent code duplication.
it also implement it in the pod_attache_time test (as the first test to implement) to verify it is working.

### CODE REVIEW

**Comment by Avilir** [comment]
from the test log we can see that the results pushed to the dashboard
```
2022-02-28 19:19:49  -------------------------------- live log call ---------------------------------
2022-02-28 19:19:49  17:19:49 - MainThread - ocs_ci.ocs.perftests - INFO - Check results for [test_pod_start_time] in : /home/jenkins/current-cluster-dir/logs/ocs-ci-logs-1646068155/tests/e2e/performance/csi_tests/test_pvc_attachtime.py/TestPodStartTime/test_pod_start_time/all_results.txt
2022-02-28 19:19:49  17:19:49 - MainThread - ocs_ci.ocs.perftests - INFO - All test finished OK, and the results can be found at :
2022-02-28 19:19:49  17:19:49 - MainThread - ocs_ci.ocs.perftests - INFO - http://10.0.78.167:9200/pvc_attach_time_fullres/_search?q=uuid:5636842bb845455785d91877a5eb605b
2022-02-28 19:19:49  17:19:49 - MainThread - ocs_ci.ocs.perftests - INFO - http://10.0.78.167:9200/pvc_attach_time_fullres/_search?q=uuid:c4f3888738484412aba2629045ba7169
2022-02-28 19:19:49  17:19:49 - MainThread - ocs_ci.utility.perf_dash.dashboard_api - INFO - Creating DB connector and connect to it
2022-02-28 19:19:49  17:19:49 - MainThread - ocs_ci.ocs.perftests - INFO - Full version is : 4.10.0-171
2022-02-28 19:19:49  17:19:49 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get node  --selector=topology.kubernetes.io/zone -o yaml
2022-02-28 19:19:50  17:19:49 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get StorageCluster  -n openshift-storage -o yaml
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get namespace openshift-local-storage -o yaml
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): namespaces "openshift-local-storage" not found
2022-02-28 19:19:50  
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: openshift-local-storage of kind: namespace, selector: None, Error: Error during execution of command: oc get namespace openshift-local-storage -o yaml.
2022-02-28 19:19:50  Error is Error from server (NotFound): namespaces "openshift-local-storage" not found
2022-02-28 19:19:50  
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.ocs.ocp - WARNING - Number of attempts to get resource reached!
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get cephblockpool  -n openshift-storage -o yaml
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.ocs.perftests - INFO - Trying to push :version=4.10.0,build=171,platform=vsphere,topology=1-AZ,test=PVC Attach Time,eslink=http://10.0.78.167:9200/pvc_attach_time_fullres/_search?q=uuid:5636842bb845455785d91877a5eb605b,http://10.0.78.167:9200/pvc_attach_time_fullres/_search?q=uuid:c4f3888738484412aba2629045ba7169, logfile=None
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.utility.perf_dash.dashboard_api - INFO - Test results pushed to the DB!
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.ocs.perftests - INFO - Full results report can be found at : http://10.0.78.167:8080/index.php?version1=14&build1=45&platform1=8&az_topology1=3&test_name%5B%5D=9&submit=Choose+options
2022-02-28 19:19:50  17:19:50 - MainThread - ocs_ci.utility.perf_dash.dashboard_api - INFO - Closing the DB connection
2022-02-28 19:19:50  PASSED                                                                   [100%]
```

**Review by ramkiperiy — APPROVED** [review]
LGTM

**Review by ypersky1980 — APPROVED** [review]
LGTM

**Review by ypersky1980 — APPROVED** [review]
LGTM

**Pull request merged**
