### PR TITLE
Add retry to setup fio function

### PR DESCRIPTION
**Pull request by petr-balogh**
Fixes: #1200

This adds retry the setup function for fio.
Currently upgrade is failing on this issue and we need unblock upgrade
jobs ASAP hence adding retry as quick fix here.

For sure Vasus propsed PR to use preinstalled images is still valid but
this setup is executed all the time as well to make sure we have the
fio package.

Signed-off-by: Petr Balogh <pbalogh@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
Running verification here:  https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/3451/console

**Comment by petr-balogh** [comment]
I see that the verification job already passed the upgrade phase and continue to run tier1 which we didn't have success before. So if possible, let's merge this one as it's verified and we can start executing upgrade jobs which will continue to execute tier1. Thanks

**Comment by petr-balogh** [comment]
Summary

5 tests ran in 5545.01 seconds.

5 passed, 0 skipped, 0 failed, 0 errors, 0 expec ted failures, 0 unexpected passes

Result | Test | Description | Duration
-- | -- | -- | --
Passed | tests/ecosystem/upgrade/test_configuration.py::test_load_crush_map | Load CRUSH map. | 0.00
Passed | tests/ecosystem/upgrade/test_resources.py::test_start_pre_upgrade_pod_io | Confirm that there are pods created before upgrade. | 0.00
Passed | tests/ecosystem/upgrade/test_upgrade.py::test_upgrade | None | 305.69
Passed | tests/ecosystem/upgrade/test_configuration.py::test_crush_map_unchanged | Test that CRUSH map loaded before upgrade is the same as CRUSH map after upgrade. | 2.46
Passed | tests/ecosystem/upgrade/test_resources.py::test_pod_io | Test IO on multiple pods at the same time and finish IO on pods that were created before upgrade. | 1344.04

**Comment by vasukulkarni** [comment]
I am fine,  The setup function for fio will be noop after my PR is merged.

**Pull request merged**
