### PR TITLE
Add multus baremetal configuration

### PR DESCRIPTION
**Pull request by clacroix12**
Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Review by vavuthu — DISMISSED** [review]

**Review by shylesh — APPROVED** [review]
LGTM

**Comment by clacroix12** [comment]
Need to add `multus_public_network_interface` in `ENV_DATA` before merging this since the network interface is different for baremetal than it is for vsphere.

**Comment by clacroix12** [comment]
@shylesh @vavuthu @sidhant-agrawal I've added the interface for baremetal, please take another look when you get a chance.

**Review by shylesh — APPROVED** [review]
LGTM

**Review by petr-balogh — APPROVED** [review]

**Pull request merged**
