### PR TITLE
Bulk attach improvement

### PR DESCRIPTION
**Pull request by Avilir**
This PR reduce the runtime of the test from ~4.5 Hours to ~1 Hour

### CODE REVIEW

**Comment by Avilir** [comment]
from the PR validation job :
```
2022-04-20 18:12:08  ================== 5 passed, 6 warnings in 2660.53s (0:44:20) ==================
```

The test runtime is : **44 Min.**  while before this PR the test took **4 Hours and 40 Min**

from previous run logs 
```
2022-04-20 14:51:34  ================= 5 passed, 5 warnings in 16850.73s (4:40:50) ==================
```

Warnings in the TC are OK, it on none secure Elastic search connections

**Review by ramkiperiy — APPROVED** [review]
LGTM

**Review by pintojoy — APPROVED** [review]
LGTM

**Review by ypersky1980 — APPROVED** [review]
LGTM

**Pull request merged**
