### PR TITLE
ignore rook-ceph-detect-version pods if FIPS checking

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #10239

Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Comment by vavuthu** [comment]
triggered verification: https://url.corp.redhat.com/af8e562

**Review by dahorak — APPROVED** [review]

**Review by petr-balogh — APPROVED** [review]

**Comment by vavuthu** [comment]
> triggered verification: https://url.corp.redhat.com/af8e562

upgrade job passed succesfully

**Pull request merged**
