### PR TITLE
[WIP] Modify the test case test_rolling_shutdown_and_recovery to run on MS

### PR DESCRIPTION
**Pull request by jilju**
Modified the test case given below to run on Managed services platform.

tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery.py::TestRollingWorkerNodeShutdownAndRecovery::test_rolling_shutdown_and_recovery

Node operations should be done on provider. Added the marker "runs_on_provider" to switch the cluster context to provider before the start of the test case and switch back to  the initial cluster context after completing the test case.
Switching to consumer cluster context is done before creating PVC, pods etc.
The finalizer which is intended to recover the nodes should run on provider cluster.

Signed-off-by: Jilju Joy <jijoy@redhat.com>

### CODE REVIEW

**Comment by jilju** [comment]
Verified : http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jijoy-bug-c1/jijoy-bug-c1_20220630T114214/multicluster/logs/test_report_1656667689.html

**Comment by jilju** [comment]
ROSA doesn't yet support shutdown of full ROSA cluster or shutdown of a single node. Decision pending on skipping this test.

**Review by ebenahar — APPROVED** [review]

**Comment by yitzhak12** [comment]
Let us skip the test and create a similar test for the Managed Service, which will be as follow:
Shutdown all nodes one after the other, but in a controlled fashion(ceph health OK before shutting down next node).
Thread link: https://chat.google.com/room/AAAABfd8ivI/oTXGyoT8VrU

**Comment by jilju** [comment]
> Let us skip the test and create a similar test for the Managed Service, which will be as follow: Shutdown all nodes one after the other, but in a controlled fashion(ceph health OK before shutting down next node). Thread link: https://chat.google.com/room/AAAABfd8ivI/oTXGyoT8VrU


Yes, we can close this PR.

**Pull request closed without merging**
