### PR TITLE
Drop debug-level logging for openshift-install

### PR DESCRIPTION
**Pull request by zmc**
I expect that some people will rather make this configurable than to simply drop `--log-level debug` entirely. I'll be willing to do that work *if* we want it. I also wouldn't be surprised if nobody would actually miss that output, though, so I'm starting with this.

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@zmc this should be configurable, for jenkins as well as folks in deployment team for them to debug, can you add the option please. thanks

**Comment by clacroix12** [comment]
@zmc @vasukulkarni should we just hook into the log level set for pytest to keep things consistent?

**Comment by vasukulkarni** [comment]
> @zmc @vasukulkarni should we just hook into the log level set for pytest to keep things consistent?

That makes sense to me, but there is a current problem with 'debug' that is causing huge logs in couple of tests due to which installer's debug will have to suffer :(

**Comment by clacroix12** [comment]
@zmc @vasukulkarni I opened #395 which makes it so the openshift-installer will use pytest's `log_cli_level`.

**Comment by vasukulkarni** [comment]
I think we can drop this due to #395

**Comment by clacroix12** [comment]
Closing due to #395

**Pull request closed without merging**
