### PR TITLE
include IndexError while collect upgrade marks

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #10682

### CODE REVIEW

**Review by petr-balogh — APPROVED** [review]

**Comment by petr-balogh** [comment]
Oded recently did this change here:
https://github.com/red-hat-storage/ocs-ci/pull/10595

This was cherrypicked till 4.13 from what I see - 4.12 automatic cherry-pick failed - so I think we need to cherrypick this to all relevant branches as well please.

**Review by dahorak — APPROVED** [review]

**Pull request merged**
