### PR TITLE
[WIP] use kubeadmin as default for login function

### PR DESCRIPTION
**Pull request by fbalak**
Signed-off-by: Filip Balak <fbalak@redhat.com>

### CODE REVIEW

**Comment by ebenahar** [comment]
Fixes https://github.com/red-hat-storage/ocs-ci/issues/2391?

**Comment by fbalak** [comment]
@ebenahar Yes, this is done because of IBM cloud deployment have different cluster dir structure and doesn't contain `kubeadmin-password` file but it seems to be more complicated than I originally thought: It seems that `kubeadmin` user has to be logged in via password, `system:admin`has no token generated for API calls and service account can not be logged in via kubeconfig. I will probably have to generate a proper user for API communication.

**Comment by ebenahar** [comment]
Hi @fbalak what's the current status with this change?

**Comment by fbalak** [comment]
Hi @ebenahar. I am closing this PR as this is not a way (as described in my previous comment). I opened https://github.com/red-hat-storage/ocs-ci/pull/2766 to add user management into our framework. With this I will add a new Prometheus user in another PR.

**Pull request closed without merging**
