### PR TITLE
Add produciton config for AWS IPI with m5.4xlarge

### PR DESCRIPTION
**Pull request by petr-balogh**
Fixes: #696 

This config will be used for production runs

Signed-off-by: Petr Balogh <pbalogh@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
I guess no need for verification as this is just simple config file which is not used anywhere yet.

**Comment by vasukulkarni** [comment]
why not test it once with deployment to confirm?

**Comment by vasukulkarni** [comment]
Verified locally ?

**Comment by petr-balogh** [comment]
yep

**Pull request merged**
