### PR TITLE
Adding rgw annotation to bucket_size test if upgraded from OCS 4.6

### PR DESCRIPTION
**Pull request by parikshithb**
Signed-off-by: Parikshith Byregowda <pbyregow@redhat.com>

### CODE REVIEW

**Review by Akarsha-rai — APPROVED** [review]

**Review by PrasadDesala — DISMISSED** [review]

**Comment by parikshithb** [comment]
Test skipped on upgraded 4.7 cluster:

+ run-ci --color=yes tests/manage/rgw/test_object_bucket_size.py -m tier1 -k '' --ocs-version 4.7 --ocp-version 4.7 --ocsci-conf=/tmp/YL6I78TS6N0H '--ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml' --ocsci-conf=conf/ocsci/vsphere_upi.yaml --collect-logs --collect-logs-on-success-run --cluster-name pbyregow-vm --cluster-path /home/jenkins/current-cluster-dir/openshift-cluster-dir --junit-xml /home/jenkins/current-cluster-dir/logs/test_results_1620289339.xml -o junit_suite_name=pbyregow-vm '--html=~/current-cluster-dir/logs/test_report_1620289339.html' --self-contained-html --bugzilla --email=pbyregow@redhat.com --squad-analysis
2021-05-06 08:24:31,171 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - INFO - Dump of the consolidated config file is located here: /home/jenkins/current-cluster-dir/logs/run-1620289468-config.yaml
Collecting Cluster versions
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-5.3.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci, inifile: pytest.ini
plugins: logger-0.5.1, metadata-1.11.0, html-2.1.1, marker-bugzilla-0.9.4, ordering-0.6, reportportal-1.10.3
Checking for bugzilla-related tests
..
Checking for bugzilla-related tests has finished
2 bug marker sets found.

----------------------------- live log collection ------------------------------
08:24:40 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-marketplace get CatalogSource ocs-catalogsource -n openshift-marketplace -o yaml
08:24:40 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
08:24:41 - MainThread - ocs_ci.ocs.resources.ocs - INFO - Check if OCS operator: ocs-operator.v4.7.0-377.ci is in Succeeded phase.
08:24:41 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get csv ocs-operator.v4.7.0-377.ci -n openshift-storage -o yaml
08:24:41 - MainThread - ocs_ci.ocs.ocp - INFO - Resource ocs-operator.v4.7.0-377.ci is in phase: Succeeded!
08:24:41 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get csv ocs-operator.v4.7.0-377.ci -n openshift-storage -o yaml
08:24:42 - MainThread - tests.conftest - INFO - Test: <Function test_object_bucket_size> will be skipped because the OCS cluster is upgraded from one of these versions: ['4.6']
---------------------------- live log sessionfinish ----------------------------
08:24:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get csv  -n openshift-storage -o yaml
08:24:43 - MainThread - ocs_ci.utility.utils - INFO - testrun_name: OCS4-7-Downstream-OCP4-7-VSPHERE-UPI-1AZ-RHCOS-3M-3W-tier1
08:24:43 - MainThread - ocs_ci.utility.utils - INFO - Results have been emailed to ['pbyregow@redhat.com']
collected 1 item

- generated xml file: /home/jenkins/current-cluster-dir/logs/test_results_1620289339.xml -
- generated html file: file:///home/jenkins/current-cluster-dir/logs/test_report_1620289339.html -
============================ no tests ran in 2.38s =============================

**Comment by MeridianExplorer** [comment]
@parikshithb - Why does the test need to be skipped?

After I read BZ1952848 it seemed like the correct solution would be to patch in an annotation, no?

**Review by Akarsha-rai — APPROVED** [review]

**Comment by parikshithb** [comment]
> @parikshithb - Why does the test need to be skipped?
> 
> After I read BZ1952848 it seemed like the correct solution would be to patch in an annotation, no?

Ack, removed the skip and added annotation.

**Comment by parikshithb** [comment]
^^ Verified on ocs 4.6 to 4.7 upgraded cluster.

**Review by Akarsha-rai — APPROVED** [review]

**Review by PrasadDesala — APPROVED** [review]

**Pull request merged**
