### PR TITLE
deployment: remove checks for rbd-thick sc

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Thick provisioning is being deprecated, removing the storage class
check and tests. Complete code cleanup is still pending.

Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
I have just removed the deployment checks so that ci passes and the acceptance tests do not fail when we start building 4.10 Code cleanup is still required if QE wants to do that.

@jilju @vavuthu

**Comment by ebenahar** [comment]
Thanks @agarwal-mudit for the PR. 
There are a few more test files to handle for RBD thick provisioning deprecation:
* tests/manage/pv_services/test_rbd_thick_provisioning.py
* tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
* tests/manage/pv_services/test_verify_thick_pvc_utilization.py

**Review by vavuthu — DISMISSED** [review]

**Review by ebenahar — APPROVED** [review]

**Comment by agarwal-mudit** [comment]
> Thanks @agarwal-mudit for the PR. There are a few more test files to handle for RBD thick provisioning deprecation:
> 
>     * tests/manage/pv_services/test_rbd_thick_provisioning.py
> 
>     * tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
> 
>     * tests/manage/pv_services/test_verify_thick_pvc_utilization.py

@ebenahar I hope QE team will work on this as these tests were written later for thick provisioning. Do you want me to take care of this as well?

**Comment by ebenahar** [comment]
> @ebenahar I hope QE team will work on this as these tests were written later for thick provisioning. Do you want me to take care of this as well?

We will track it with https://github.com/red-hat-storage/ocs-ci/issues/5059

**Comment by agarwal-mudit** [comment]
ok, thanks
Please approve the PR again, had to reformat because of the failing ci
@ebenahar @vavuthu

**Review by vavuthu — APPROVED** [review]

**Review by ebenahar — APPROVED** [review]

**Pull request merged**
