### PR TITLE
PR to fix scale pvc expand test

### PR DESCRIPTION
**Pull request by ramkiperiy**
Existing Scale Pvc expand test is skipped due to changes in scale_lib function for memory issue.
with the changes/enhancements in this PR code will support pvc_expand tests and other tests
we should not observe any memory failures since code is using kube_job for creating PVCs and PODs

Signed-off-by: Ramakrishnan <rperiyas@redhat.com>

### CODE REVIEW

**Review by Avilir — DISMISSED** [review]
LGTM

**Review by AviadP — DISMISSED** [review]

**Review by tiffanyn108 — APPROVED** [review]
LGTM.

**Comment by ramkiperiy** [comment]
> PR validation
> 
> Cluster Name:
> Cluster Configuration:
> PR Test Suite: scale
> PR Test Path: tests/e2e/scale/test_scale_pvc_expand.py
> Additional Test Params:
> OCP VERSION: 4.8
> OCS VERSION: 4.8
> 
> [Job UNSTABLE](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1434//testReport) (some or all tests failed).

Jenkins failed for Index list out of range error.

**Comment by ramkiperiy** [comment]
Patch cmd execution for expanding the PVC is taking 2hr and 15mins for 1500 PVC sequentially this can be enhanced.

**Comment by vasukulkarni** [comment]
great improvement @ramkiperiy :+1:

**Comment by ramkiperiy** [comment]
> PR validation
> 
> Cluster Name:
> Cluster Configuration:
> PR Test Suite: scale
> PR Test Path: tests/e2e/scale/test_scale_pvc_expand.py
> Additional Test Params:
> OCP VERSION: 4.8
> OCS VERSION: 4.8
> 
> [Job PASSED](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1451//testReport).

TC passed 
image

**Comment by ramkiperiy** [comment]
Started a regression Jenkins validation job

**Review by tiffanyn108 — APPROVED** [review]

**Review by vasukulkarni — APPROVED** [review]

**Review by Avilir — APPROVED** [review]
lgtm

**Pull request merged**
