### PR TITLE
Defaulting ocs-ci to ODF 4.13

### PR DESCRIPTION
**Pull request by vavuthu**
Signed-off-by: vavuthu <vavuthu@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
Can you change version to 4.13.0 here as well as part of this PR:
https://github.com/red-hat-storage/ocs-ci/blob/master/setup.py#L12

**Comment by vavuthu** [comment]
> Can you change version to 4.13.0 here as well as part of this PR: https://github.com/red-hat-storage/ocs-ci/blob/master/setup.py#L12

It  was updated in https://github.com/red-hat-storage/ocs-ci/pull/7038

**Comment by petr-balogh** [comment]
> > Can you change version to 4.13.0 here as well as part of this PR: https://github.com/red-hat-storage/ocs-ci/blob/master/setup.py#L12
> 
> 
> 
> It  was updated in https://github.com/red-hat-storage/ocs-ci/pull/7038

Here we did 4.12 to have this in release 4.12 branch. Here it will ho to master and stable once we merge after creating 4.12 release branch

**Comment by vavuthu** [comment]
verified locally

```
venv1) [vavuthu@vavuthu ocs-ci](defaulting_to_odf_413)$ run-ci tests -m deployment --cluster-name vavuthuodf4131 --cluster-path /home/vavuthu/VJ/clusterdirs/vavuthuodf4131 --ocsci-conf ~/VJ/VMWARE/UPLOAD/new/new/vSphere7-DC-PS_VC1 --ocsci-conf=conf/ocsci/vsphere_upi.yaml  --ocsci-conf skips_downloads.yaml --deploy
The kubeconfig file /home/vavuthu/VJ/clusterdirs/vavuthuodf4131/auth/kubeconfig doesn't exist!
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.8, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/vavuthu/VJ/projects/ocs-ci, configfile: pytest.ini, testpaths: tests
plugins: logger-0.5.1, metadata-1.11.0, html-3.1.1, marker-bugzilla-0.9.4, ordering-0.6, flaky-3.7.0, repeat-0.9.1
collecting ... 


11:15:14 - MainThread - ocs_ci.utility.utils - INFO  - OpenShift Installer version: /home/vavuthu/VJ/projects/ocs-ci/bin/openshift-install 4.13.0-0.nightly-2023-02-02-150419
built from commit 610a121833c72b31e8155db476afc5c9f7b11bf2
release image registry.ci.openshift.org/ocp/release@sha256:ae86902653839e769594d289b30b45e4841f9adffed9ad879f5b523235f7e613
release architecture amd64

11:15:14 - MainThread - ocs_ci.utility.utils - INFO  - Downloading terraform version 1.0.11
11:15:16 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: unzip -o terraform_1.0.11_linux_amd64.zip
11:15:16 - MainThread - ocs_ci.utility.utils - INFO  - Downloading terraform ignition provider version v2.1.2

11:50:53 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:50:59 - MainThread - ocs_ci.ocs.resources.packagemanifest - INFO  - package manifest odf-operator found!
11:50:59 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:51:07 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get csv odf-operator.v4.13.0-58.stable -n openshift-storage -o yaml
11:51:08 - MainThread - ocs_ci.ocs.ocp - INFO  - Resource odf-operator.v4.13.0-58.stable is in phase: Succeeded!
11:51:08 - MainThread - ocs_ci.ocs.resources.packagemanifest - INFO  - Waiting for a resource(s) of kind packagemanifest identified by name ''
11:51:08 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:51:13 - MainThread - ocs_ci.ocs.resources.packagemanifest - INFO  - package manifest ocs-operator found!
11:51:13 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:51:19 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get csv ocs-operator.v4.13.0-58.stable -n openshift-storage -o yaml
11:51:21 - MainThread - ocs_ci.ocs.ocp - INFO  - Resource ocs-operator.v4.13.0-58.stable is in phase: Succeeded!
11:51:21 - MainThread - ocs_ci.ocs.resources.packagemanifest - INFO  - Waiting for a resource(s) of kind packagemanifest identified by name ''
11:51:21 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:51:26 - MainThread - ocs_ci.ocs.resources.packagemanifest - INFO  - package manifest mcg-operator found!
11:51:26 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:51:32 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get csv mcg-operator.v4.13.0-58.stable -n openshift-storage -o yaml
11:51:33 - MainThread - ocs_ci.ocs.ocp - INFO  - Resource mcg-operator.v4.13.0-58.stable is in phase: Succeeded!
11:51:33 - MainThread - ocs_ci.ocs.resources.packagemanifest - INFO  - Waiting for a resource(s) of kind packagemanifest identified by name ''
11:51:33 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:51:39 - MainThread - ocs_ci.ocs.resources.packagemanifest - INFO  - package manifest odf-csi-addons-operator found!
11:51:39 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-marketplace get packagemanifest  -n openshift-marketplace --selector=ocs-operator-internal=true -o yaml
11:51:46 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get csv odf-csi-addons-operator.v4.13.0-58.stable -n openshift-storage -o yaml
11:51:47 - MainThread - ocs_ci.ocs.ocp - INFO  - Resource odf-csi-addons-operator.v4.13.0-58.stable is in phase: Succeeded!


12:07:15 - MainThread - tests.ecosystem.deployment.test_deployment - INFO  - Verifying ceph health after deployment
12:07:15 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc wait --for condition=ready pod -l app=rook-ceph-tools -n openshift-storage --timeout=300s
12:07:16 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get pod -l 'app=rook-ceph-tools' -o jsonpath='{.items[0].metadata.name}'
12:07:17 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage exec rook-ceph-tools-645cc7d555-c4b9c -- ceph health
12:07:20 - MainThread - ocs_ci.utility.utils - INFO  - Ceph cluster health is HEALTH_OK.
PASSED
-------------------------------------------------------------------------------------
```

**Review by petr-balogh — APPROVED** [review]

**Review by dahorak — APPROVED** [review]

**Pull request merged**
