### PR TITLE
Remove test_azureutil_init_invalidcredentials

### PR DESCRIPTION
**Pull request by zmc**
Fixes: #3578

### CODE REVIEW

**Review by andrewschoen — APPROVED** [review]
Looks good to me. This test has been keeping us from using the master branch for some time now downstream. I'm a bit curious why we're requesting URLs like this within unit tests anyway.

**Comment by vasukulkarni** [comment]
@mbukatov since its blocking the dev, we can move ahead with this, and you can later add skips?

**Review by vasukulkarni — APPROVED** [review]

**Comment by zmc** [comment]
Thanks @vasukulkarni 

To be clear, unit tests should access any network.

**Comment by mbukatov** [comment]
Right. We can move it to libtest.

**Pull request merged**
