### PR TITLE
remove ceph crashes after upgrade

### PR DESCRIPTION
**Pull request by petr-balogh**
remove ceph crashes after upgrade due to bug
https://bugzilla.redhat.com/show_bug.cgi?id=2249844 and Ceph bug:
https://bugzilla.redhat.com/show_bug.cgi?id=2249814

### CODE REVIEW

**Comment by petr-balogh** [comment]
Verification job triggered here:
https://url.corp.redhat.com/ee41b3a

**Review by vavuthu — DISMISSED** [review]

**Comment by petr-balogh** [comment]
New verification triggered here:
https://url.corp.redhat.com/915ffa7

**Review by vavuthu — DISMISSED** [review]

**Comment by petr-balogh** [comment]
New verification:
https://url.corp.redhat.com/1c86b2f

**Review by shivamdurgbuns — DISMISSED** [review]

**Review by clacroix12 — APPROVED** [review]

**Review by shylesh — APPROVED** [review]
LGTM

**Review by OdedViner — DISMISSED** [review]

**Comment by petr-balogh** [comment]
New verification:
https://url.corp.redhat.com/03ff5ae

**Review by shylesh — DISMISSED** [review]
LGTM

**Review by dahorak — APPROVED** [review]

**Review by shylesh — DISMISSED** [review]
LGTM

**Review by vavuthu — DISMISSED** [review]

**Comment by petr-balogh** [comment]
New verification:
 https://url.corp.redhat.com/d7f6243

**Comment by petr-balogh** [comment]
as from last approval there was just doc indention issue fixed, I will merge as is now to be able to run upgrade pipelines for new build with this W/A.

Issue to revert this is already opened here:
https://github.com/red-hat-storage/ocs-ci/issues/8856

**Pull request merged**
