### PR TITLE
Implement the OSD cache droping into the SmallFiles benchmark

### PR DESCRIPTION
**Pull request by Avilir**
In this PR i am implementing the ability to drop the OSD cache between test samples for more consistency results

### CODE REVIEW

**Review by keesturam — DISMISSED** [review]
Nice implementation Avi.

**Review by ypersky1980 — DISMISSED** [review]

**Review by keesturam — APPROVED** [review]
Looks good to me.

**Review by ypersky1980 — APPROVED** [review]

**Comment by ypersky1980** [comment]
@Avilir  Please note that one of the PR checks ( 3.8) did not pass.

**Comment by Avilir** [comment]
this is old PR and some changes have been done in the small_files benchmark, so i am closing this PR, and will send new one if needed.

**Pull request closed without merging**
