### PR TITLE
Green squad test directory re-structure

### PR DESCRIPTION
**Pull request by jilju**
Current directory structure of the identified green squad test cases:

```
1. tests/manage/pv_services/
2. tests/manage/storageclass/
3. tests/manage/add_metadata_feature/
4. tests/ui/test_create_pool_block_pool.py
5. tests/ui/test_pvc_ui.py
6. tests/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
7. tests/encryption/
```

New structure:
```
* tests/functional/pv/
 - space_reclaim   (directory moved from tests/manage/pv_services/space_reclaim)
 - pv_services   (all test cases that were directly under the directory tests/manage/pv_services/)
 - pv_encryption    (directory moved from tests/manage/pv_services/pv_encryption)
 - pvc_snapshot   (directory moved from tests/manage/pv_services/pvc_snapshot)
 - pvc_resize   (directory moved from tests/manage/pv_services/pvc_resize)
 - pvc_clone    (directory moved from tests/manage/pv_services/pvc_clone)
 - add_metadata_feature   (directory moved from tests/manage/add_metadata_feature)
 - conftest.py   (file moved from tests/manage/pv_services/)
 
* tests/functional/storageclass/   (directory moved from tests/manage/storageclass)
* tests/functional/ui/test_create_pool_block_pool.py   (file moved from tests/ui/test_create_pool_block_pool.py)
* tests/functional/ui/test_pvc_ui.py   (file moved from tests/ui/test_pvc_ui.py)
* tests/functional/ui/test_creation_and_deletion_of_sc_and_rbdpool.py   (file moved from tests/ui/test_creation_and_deletion_of_sc_and_rbdpool.py)

* tests/functional/encryption/ (directory moved from tests/encryption)
```

### CODE REVIEW

**Comment by paraggit** [comment]
@jilju  One more  move I would suggest `tests/encryption` to `tests/functional/encryption`.

**Review by ebenahar — APPROVED** [review]

**Comment by jilju** [comment]
> @jilju One more move I would suggest `tests/encryption` to `tests/functional/encryption`.



> @jilju One more move I would suggest `tests/encryption` to `tests/functional/encryption`.

Done

**Review by keemano — APPROVED** [review]
LGTM

**Comment by jilju** [comment]
Rebased.

**Comment by jilju** [comment]
> PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: tier1 PR Test Path: tests/functional/pv/ tests/functional/storageclass/ tests/functional/ui/ tests/functional/encryption/ Additional Test Params: --ignore=tests/manage/pv_services/test_write_to_cephfs_pvc_with_nonroot_user.py OCP VERSION: 4.15 OCS VERSION: 4.15 tested against branch: master
> 
> [Job UNSTABLE](https://url.corp.redhat.com/d8941f3) (some or all tests failed).

There are some failure in tier1 run. The erros are not related to the cahnge introducted in this PR.

**Review by paraggit — APPROVED** [review]

**Comment by jilju** [comment]
rebase

**Review by paraggit — APPROVED** [review]

**Review by OdedViner — APPROVED** [review]

**Review by ebenahar — APPROVED** [review]

**Pull request merged**
