### PR TITLE
Run parallel must gather for ocp, ocs and mcg

### PR DESCRIPTION
**Pull request by shylesh**

### CODE REVIEW

**Comment by shylesh** [comment]
Single cluster parallel ocp/ocs must-gather logs  https://url.corp.redhat.com/parallel-mustgather-single

**Review by prsurve — APPROVED** [review]

**Review by vavuthu — APPROVED** [review]

**Comment by shylesh** [comment]
Another run from which nooba and ocs logs were parallely collected.

https://url.corp.redhat.com/noobaaocsparallel

**Comment by shylesh** [comment]
Regression run: https://url.corp.redhat.com/regression-parallel

**Review by petr-balogh — APPROVED** [review]

**Pull request merged**
