### PR TITLE
Refactor tests hierarchy

### LINKED ISSUE #2939: Refactor tests dir hierarchy
There are a few problems with the current structure: 
- The current e2e dir includes tests of both QPAS and E2E team
- The current manage dir should include also customer defects test cases, which are being automated by E2E team memers
- Flow based test cases are currently under e2e dir which includes both perf, scale and workloads

### PR DESCRIPTION
**Pull request by ebenahar**
Fixes #2939

Signed-off-by: Elad Ben Aharon <ebenahar@redhat.com>

### CODE REVIEW

**Comment by ebenahar** [comment]
With this PR, the new proposed structure is as follows:
Screenshot from 2020-09-14 18-04-40

**Comment by vasukulkarni** [comment]
This will require all tier testing, since the pytest runs based on alphabetical order of the folder names and also needs documentation updates.

**Comment by ebenahar** [comment]
> This will require all tier testing, since the pytest runs based on alphabetical order of the folder names and also needs documentation updates.

+1

**Comment by petr-balogh** [comment]
Closing due to inactivity on this PR, feel free to re-open, or send the new PR.

**Pull request closed without merging**
