### PR TITLE
Ignore leftovers post OCP upgrade

### PR DESCRIPTION
**Pull request by ebenahar**
Signed-off-by: Elad Ben Aharon <ebenahar@redhat.com>

### CODE REVIEW

**Comment by AviadP** [comment]
most pods in openshift-storage namespace restarting during upgrade, so we should ignore leftovers

**Comment by vasukulkarni** [comment]
WIP will block the CI merge.

**Comment by ebenahar** [comment]
Following a conversation with @AviadP, ignore leftovers is needed in OCP upgrade test since all cluster pods are being stopped and new ones are started instead

**Comment by ebenahar** [comment]
Verified in https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6198/

**Pull request merged**
