### PR TITLE
Python 3.10 support

### PR DESCRIPTION
**Pull request by clacroix12**

### CODE REVIEW

**Review by petr-balogh — APPROVED** [review]

**Comment by clacroix12** [comment]
Verified ODF deployment to AWS locally using python 3.10 venv.

**Comment by clacroix12** [comment]
PR Check requirements will be updated just before merging as this needs to happen on the github side.

**Review by dahorak — APPROVED** [review]

**Review by vavuthu — APPROVED** [review]

**Comment by petr-balogh** [comment]
@clacroix12 can you please do cherry-picks to all relevant supported branches? So only then we can enforce pr_check for 3.10 in release branches. Vijay has noticed that you have required this for release branches as well, but till we don't have the PR cherry-picked in all release branches, we cannot enforce PR check for 3.10 if it's not there.

Thanks

**Comment by clacroix12** [comment]
Cherry picked to `release-4.12` manually here: https://github.com/red-hat-storage/ocs-ci/pull/10023

**Comment by clacroix12** [comment]
> @clacroix12 can you please do cherry-picks to all relevant supported branches? So only then we can enforce pr_check for 3.10 in release branches. Vijay has noticed that you have required this for release branches as well, but till we don't have the PR cherry-picked in all release branches, we cannot enforce PR check for 3.10 if it's not there.
> 
> Thanks

@petr-balogh Cherry picks to release branches 4.12 - 4.15 have been merged and the branch rules have been updated to expect 4.9 and 4.10 PR checks.

**Pull request merged**
