### PR TITLE
Polarion upgrade fix

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #2803

### CODE REVIEW

**Comment by clacroix12** [comment]
I've removed the "old" polarion IDs for upgrade test cases and added three new configuration files which should represent the "common" upgrade scenarios described by @nehaberry here: https://docs.google.com/document/d/1rw8Ghl4ij-7Ufw8HfvfP_Shf4es3S5qVTegN75QY1WY/edit?ts=5f52313c

@petr-balogh if there is something that needs to be in these config files that I'm missing please let me know.

**Review by petr-balogh — APPROVED** [review]
@clacroix12 this require change in our jobs. I would merge this together with the change you are going to do in our jobs. Sounds OK?

**Comment by clacroix12** [comment]
> @clacroix12 this require change in our jobs. I would merge this together with the change you are going to do in our jobs. Sounds OK?

Yes, I'm leaving it as WIP until I have the jobs MR up and ready.

**Comment by clacroix12** [comment]
Related MR: https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/348

**Review by shylesh — APPROVED** [review]
+1

**Pull request merged**
