### PR TITLE
Use Prometheus user for alerting tests

### PR DESCRIPTION
**Pull request by fbalak**
This should allow alerting tests to work on setups without kubeadmin-password file (IBM cloud).

### CODE REVIEW

**Review by ebenahar — APPROVED** [review]
Great work Filip

**Review by mbukatov — DISMISSED** [review]

**Comment by fbalak** [comment]
@Akarsha-rai Can you please take a look at results of [last verification job](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2929//testReport)? I tried to update your tests to use `prometheus_user` fixture and some tests failed. Are those failures related to changes done in this PR?

**Review by mbukatov — DISMISSED** [review]

**Comment by fbalak** [comment]
[First verification](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2900//testReport) job failed because htpasswd was not installed on jenkins slave. This is resolved now.
[Verification job](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2911//testReport) on test path `tests/manage/monitoring/` has 2 failed tests because of https://github.com/red-hat-storage/ocs-ci/issues/3005 and BZ 1779336 but there was no problem with Prometheus authentication.
[Verification job ](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2929//testReport) on test path `tests/e2e/monitoring/`: It seems that communication with Prometheus API works but there are few errors. @Akarsha-rai @vavuthu can you please take a look?

**Review by ebenahar — DISMISSED** [review]

**Comment by petr-balogh** [comment]
@fbalak I am running the tier1 execution on newly created ROKS cluster on IBM Cloud here:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/13576/console

But I see it's failing right at the start of the execution on user things...  It's worth to have talk with IBM Guys, I can setup mtg for next week as I think they have some special authentication in ROKS cluster as if I am trying to even open openshift-console web UI it's redirect me directly to IBM Cloud login page.

**Comment by fbalak** [comment]
@petr-balogh Thank you, that would be helpful.

**Review by mbukatov — APPROVED** [review]

**Comment by fbalak** [comment]
Method for allowing Prometheus API communication on IBM Cloud changed several times during developing this fix and this PR became confusing.
Working fix: https://github.com/red-hat-storage/ocs-ci/pull/3246

**Pull request closed without merging**
