### PR TITLE
Remove unsupported ocp/ocs version config files

### PR DESCRIPTION
**Pull request by clacroix12**
Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
Remove also: https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/main.py#L109-L122

**Comment by clacroix12** [comment]
Updated to remove all versions prior to 4.12 as the latest code will only support 4.12 and 4.13

**Review by petr-balogh — APPROVED** [review]

**Comment by petr-balogh** [comment]
Please inform team about this via email before merge. So people will know that they have to change the branch locally before running older version and will not be surprised.

@b-ranto do you have changes in engineering pipeline ready for using release branches? As it can affect the build process for older builds than 4.12.

Not sure if there needs to be also update in cpaas pipelines?

**Comment by vavuthu** [comment]
updated the title to WIP since MS pipeline has to update @dahorak

**Comment by dahorak** [comment]
@clacroix12 @petr-balogh There will be problem with MS, because it always uses (quite) older OCP version (e.g. 4.10 right now) and it have lot of patches coming to this repository every week, so it doesn't make much sense to backport them all to the respective branch.
I'm not sure now, what will be the best approach here?

**Comment by clacroix12** [comment]
Updated to remove versions prior to 4.10 to support MS on the master/stable branches.

**Review by petr-balogh — APPROVED** [review]

**Review by shylesh — APPROVED** [review]
LGTM

**Comment by b-ranto** [comment]
LGTM

**Review by b-ranto — APPROVED** [review]

**Pull request merged**
