### PR TITLE
Fix for Issue-317

### PR DESCRIPTION
**Pull request by nehaberry**
This PR addressed #317 

Corresponding changes doen in helpers.py as well.

Tested following:

1. Fresh deployment (due tochanges in rbac files and operator-openshift-with-csi.yaml)
2. Create sc, secret (admin user) , pvc and pod

### CODE REVIEW

**Comment by nehaberry** [comment]
**1. Deployment Run result**

```
17:06:19 - MainThread - tests.conftest - INFO - HEALTH_OK, install successful.
--------------------------------------------- live log call ---------------------------------------------
17:06:19 - MainThread - ocs_ci.ocs.openshift_ops - INFO - Testing access to cluster with /home/nberry/aws-install/jul1-2/auth/kubeconfig
17:06:19 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc cluster-info
17:06:21 - MainThread - ocs_ci.ocs.openshift_ops - INFO - Access to cluster is OK!
PASSED                                                                                            [100%]

============================== 1 passed, 26 deselected in 2785.97 seconds ===============================
```


PVC creation for RBD and cephFS

```
Every 2.0s: oc get pvc; oc get pods                                  Mon Jul  1 19:03:37 2019

NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES
   STORAGECLASS                   AGE
claimvol-cephfs   Bound    pvc-196a9c65-9c02-11e9-82b4-0a7add96096a   2Gi        RWO
   storageclass-test-0118431927   19m
claimvol-rbd	  Bound    pvc-3ba8b3e2-9c02-11e9-9715-02fd1fed661a   2Gi        RWO
   storageclass-test-0118430944   18m
NAME                        READY   STATUS	RESTARTS   AGE
cirrosvol-cephfs-1-deploy   0/1     Completed   0          19m
cirrosvol-cephfs-1-gz2j2    1/1     Running     0          19m
cirrosvol-rbd-1-9s997       1/1     Running     0          18m
cirrosvol-rbd-1-deploy      0/1     Completed   0          18m


```

**Comment by sidhant-agrawal** [comment]
LGTM

**Comment by vasukulkarni** [comment]
Commit message can be amended to include more information, Overall LGTM but I guess we have to wait for the rook PR to be merged here.

**Comment by nehaberry** [comment]
> Commit message can be amended to include more information, Overall LGTM but I guess we have to wait for the rook PR to be merged here.

Sure Vasu, next time will try to add better commit message.

As regards rook PR for merge, that was the initial plan, but the changes are already IN csi builds , hence CSI expects them but rook hasn't changed them yet. Due to this, we were facing the pvc provisioning issues.
Confirmed with Madhu and he said its ok to use the FIles from [PR-3358](https://github.com/rook/rook/pull/3358/files) to unblock oursleves.

**Comment by vasukulkarni** [comment]
@nehaberry np thanks, we could have waited for PR-3358 but I guess for future we can add Depends on PR so that both will block each other.

**Pull request merged**
