### PR TITLE
Change worker instance type for all IBM Cloud deployments to bx2-16x64

### PR DESCRIPTION
**Pull request by clacroix12**

### CODE REVIEW

**Comment by clacroix12** [comment]
Testing deployment: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/22667/

**Comment by petr-balogh** [comment]
I guess it will require cherry-picks ;)

**Comment by clacroix12** [comment]
Deployment testing passed, marked as verified.

**Review by shylesh — APPROVED** [review]
LGTM

**Pull request merged**
