### PR TITLE
Recreate DNS record at the time of BM Install

### PR DESCRIPTION
**Pull request by prsurve**
Signed-off-by: Pratik Surve <prsurve@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
How was the record updated before? I dont see that diff? What is the issue link for this PR?

**Comment by prsurve** [comment]
> How was the record updated before? I dont see that diff? What is the issue link for this PR?

Before this PR we were manually editing bootstrap or worker IP in aws route53 by this PR we will remove manual work

**Review by vasukulkarni — APPROVED** [review]

**Comment by vasukulkarni** [comment]
Please show logs that delete is also working and no stale records exists

**Review by jilju — APPROVED** [review]

**Comment by prsurve** [comment]
> Please show logs that delete is also working and no stale records exists

DEBUG Logs:- 
http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jnk-pr4124-b549/jnk-pr4124-b549_20210419T154524/logs/ocs-ci-logs-1618847689/tests/ecosystem/deployment/test_deployment.py/test_deployment/logs

Console Logs:-
http://pastebin.test.redhat.com/957186

Note:- We are not deleting complete hosted zone we are just deleting entry like `api.` `api-int` and `*.apps.`

**Pull request merged**
