### PR TITLE
Support python 3.11

### PR DESCRIPTION
**Pull request by clacroix12**

### CODE REVIEW

**Comment by clacroix12** [comment]
I tested this locally with `tox` and with an aws deployment using a python 3.11 venv. Deployment, verification, and teardown were all successful. Still want to test on our jenkins agents however, hence the needs deployment testing label.

**Review by dahorak — APPROVED** [review]

**Review by shylesh — APPROVED** [review]
lgtm

**Comment by petr-balogh** [comment]
@clacroix12 can we cherry-pick to all relevant release branches or there is some known issue please?

**Pull request merged**
