### PR TITLE
Update the rosa version with 1.2.1

### PR DESCRIPTION
**Pull request by suchita-g**
Fixes issue #5804
ROSA CLI release 1.2.1 with the provider part is planned for April 28th
https://issues.redhat.com/browse/CLOUDDST-13002

Signed-off-by: suchita.gatfane <sgatfane@redhat.com>

### CODE REVIEW

**Comment by suchita-g** [comment]
Added Do not merge flag , this is applicable till the time https://issues.redhat.com/browse/CLOUDDST-13002 get resolved

**Comment by ebenahar** [comment]
@suchita-g should we close?

**Comment by suchita-g** [comment]
This PR is absolute and hence closing this PR

**Comment by suchita-g** [comment]
> @suchita-g should we close?

Closed Now

**Pull request closed without merging**
