### PR TITLE
Added support for a custom column name in wait_for_resource()

### PR DESCRIPTION
**Pull request by gklein**
Signed-off-by: Gil Klein <gklein@users.noreply.github.com>

### CODE REVIEW

**Comment by ebenahar** [comment]
@gklein This PR touches a sensitive area which many tests use. I suggest running more than tier1 for verification

**Comment by gklein** [comment]
> @gklein This PR touches a sensitive area which many tests use. I suggest running more than tier1 for verification

I agree. What do you think would be considered "enough testing" for this change?

**Comment by ebenahar** [comment]
@gklein tier1 + tier4 to see there are no regressions

**Comment by gklein** [comment]
Rerunning the CI jobs due to my failed attempt to runs both Tier 1 and Tier 4 concurrently

**Comment by mbukatov** [comment]
> I agree. What do you think would be considered "enough testing" for this change?

If you would like to seriously evaluate the impact here, I suggest to run the tests with this PR and compare it with a run of latest commit from master branch present in your RP via xml export files as I did there https://github.com/red-hat-storage/ocs-ci/pull/663#issuecomment-526157497 assuming the same version of OCS cluster is used in both cases. It would help you to distinguish failures which you are not responsible for (the same error and traceback in both runs) from these which could be caused by this PR.

On the other hand, nobody is actually doing this.

**Comment by mbukatov** [comment]
Btw this is fixing https://github.com/red-hat-storage/ocs-ci/issues/792

**Comment by mbukatov** [comment]
When this pull request is merged, I will rebase branch bz-1729853 and create a pull request out of it.

**Comment by mbukatov** [comment]
When I compare [result of validation job](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/644/testReport/) with [official ci results](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-ds-tier1-tests-master/200/testReport/) for tier1 test, I see this:

```
$ junit2html --summary-matrix test_results.*.xml 

Matrix Test Report
===================
                                                                                                                                     test_results.ds-tier1-tests-master.200.xml
                                                                                                                                     | test_results.test-pr-1077.644.xml
                                                                                                                                     | | 
tests.manage.mcg.test_write_to_bucket.TestBucketIO  
- test_data_reduction                                                                                                                / /  / Passed
- test_write_file_to_bucket                                                                                                          / /  / Passed
tests.manage.cluster.cluster_expansion.test_node_expansion.TestAddNode  
- test_add_node                                                                                                                      / /  / Passed
tests.manage.pv_services.test_dynamic_pvc_accessmodes_with_reclaim_policies.TestRWODynamicPvc  
- test_rwo_dynamic_pvc[CephBlockPool-Delete]                                                                                         / /  / Passed
- test_rwo_dynamic_pvc[CephBlockPool-Retain]                                                                                         / /  / Passed
- test_rwo_dynamic_pvc[CephFileSystem-Delete]                                                                                        / /  / Passed
- test_rwo_dynamic_pvc[CephFileSystem-Retain]                                                                                        / /  / Passed
tests.manage.mcg.test_bucket_deletion.TestBucketDeletion  
- test_cli_bucket_delete                                                                                                             / /  / Passed
- test_oc_bucket_delete                                                                                                              / /  / Passed
- test_s3_bucket_delete                                                                                                              / /  / Passed
tests.manage.storageclass.test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.TestVerifyAllFieldsInScYamlWithOcDescribe  
- test_verify_all_fields_in_sc_yaml_with_oc_describe[CEPHFS]                                                                         / /  / Passed
- test_verify_all_fields_in_sc_yaml_with_oc_describe[RBD]                                                                            / /  / Passed
tests.manage.cluster.test_must_gather.TestMustGather  
- test_must_gather                                                                                                                   f f  F Total Failure
tests.manage.storageclass.test_create_storageclass_with_same_name.TestCreateSCSameName  
- test_create_storageclass_with_same_name                                                                                            / /  / Passed
tests.manage.mcg.test_bucket_creation.TestBucketCreation  
- test_bucket_creation[3-CLI]                                                                                                        / f  X Partial Failure
- test_bucket_creation[3-OC]                                                                                                         / f  X Partial Failure
- test_bucket_creation[3-S3]                                                                                                         / f  X Partial Failure
tests.manage.pv_services.test_dynamic_pvc_accessmodes_with_reclaim_policies.TestRWXDynamicPvc  
- test_rwx_dynamic_pvc[CephFileSystem-Delete]                                                                                        / /  / Passed
- test_rwx_dynamic_pvc[CephFileSystem-Retain]                                                                                        / /  / Passed
tests.manage.mcg.test_multi_region.TestMultiRegion  
- test_multiregion_bucket_creation                                                                                                   / /  / Passed
tests.manage.pv_services.test_pv_creation.TestPvCreation  
- test_pv_creation                                                                                                                   / /  / Passed
tests.manage.pv_services.test_pvc_rwx_writeable_after_pod_deletions.TestRWXMountPoint  
- test_pvc_rwx_writeable_after_pod_deletions                                                                                         f /  X Partial Failure
tests.e2e.logging.test_openshift-logging.Test_openshift_logging_on_ocs  
- test_create_new_project_to_verify_logging                                                                                          / /  / Passed
tests.manage.mcg.test_object_integrity.TestBucketIntegrity  
- test_check_object_integrity                                                                                                        / /  / Passed
tests.manage.cluster.nodes.test_nodes_maintenance.TestNodesMaintenance  
- test_node_maintenance[master]                                                                                                      f f  F Total Failure
- test_node_maintenance[worker]                                                                                                      f f  F Total Failure
tests.manage.pv_services.test_change_reclaim_policy_of_pv.TestChangeReclaimPolicyOfPv  
- test_change_reclaim_policy_of_pv[CephBlockPool-Delete]                                                                             / /  / Passed
- test_change_reclaim_policy_of_pv[CephBlockPool-Retain]                                                                             / /  / Passed
- test_change_reclaim_policy_of_pv[CephFileSystem-Delete]                                                                            / /  / Passed
- test_change_reclaim_policy_of_pv[CephFileSystem-Retain]                                                                            / /  / Passed
tests.manage.cluster.test_add_mds_to_cluster.TestCephFilesystemCreation  
- test_cephfilesystem_creation                                                                                                       / /  / Passed
tests.manage.pv_services.test_pvc_delete_verify_size_is_returned_to_backendpool.TestPVCDeleteAndVerifySizeIsReturnedToBackendPool  
- test_pvc_delete_and_verify_size_is_returned_to_backend_pool                                                                        / /  / Passed
tests.manage.pv_services.test_pvc_assign_pod_node.TestPvcAssignPodNode  
- test_rwo_pvc_assign_pod_node[CephBlockPool]                                                                                        / /  / Passed
- test_rwo_pvc_assign_pod_node[CephFileSystem]                                                                                       / /  / Passed
- test_rwx_pvc_assign_pod_node                                                                                                       / /  / Passed
tests.manage.pv_services.test_verify_rwo_using_multiple_pods.TestRwoUsingMultiplePods  
- test_verify_rwo_using_multiple_pods[CephBlockPool]                                                                                 / /  / Passed
- test_verify_rwo_using_multiple_pods[CephFileSystem]                                                                                / /  / Passed
tests.manage.cluster.cluster_expansion.test_add_capacity.TestAddCapacity  
- test_add_capacity[3-2000Gi]                                                                                                        / /  / Passed
tests.manage.pv_services.test_raw_block_pv.TestRawBlockPV  
- test_raw_block_pv[Delete]                                                                                                          / /  / Passed
- test_raw_block_pv[Retain]                                                                                                          / /  / Passed
tests.manage.storageclass.test_rbd_csi_default_sc.TestBasicPVCOperations  
- test_ocs_347                                                                                                                       / /  / Passed
tests.manage.pv_services.test_reclaim_policy.TestReclaimPolicy  
- test_reclaim_policy_delete                                                                                                         / /  / Passed
- test_reclaim_policy_retain                                                                                                         / /  / Passed
tests.manage.pv_services.test_create_storage_class_pvc.TestOSCBasics  
- test_basics_cephfs                                                                                                                 / /  / Passed
- test_basics_rbd                                                                                                                    / /  / Passed

-------------------------------------------------------------------------------
Test Results:
  Failed       :     11
  Passed       :     80
```

Filtering out test cases which has different result in validation job of this PR compared to CI result:

```
$ junit2html --summary-matrix test_results.*.xml | grep Partial
- test_bucket_creation[3-CLI]                                                                                                        / f  X Partial Failure
- test_bucket_creation[3-OC]                                                                                                         / f  X Partial Failure
- test_bucket_creation[3-S3]                                                                                                         / f  X Partial Failure
- test_pvc_rwx_writeable_after_pod_deletions                                                                                         f /  X Partial Failure
```

This result mean that 3 MCG/NooBaa test failed in a validation job, while `test_pvc_rwx_writeable_after_pod_deletions` passed even though the same test failed in CI.

**Comment by mbukatov** [comment]
@petr-balogh could you check https://github.com/red-hat-storage/ocs-ci/pull/1077#issuecomment-562152773 and merge this PR if you are ok with the conclusion? If validation of other tiers are necessary as suggested by Elad, could you drive such evaluation (schedule the jobs, and run the comparison)?

**Comment by mbukatov** [comment]
@ebenahar Could you check tier1 test result evaluation https://github.com/red-hat-storage/ocs-ci/pull/1077#issuecomment-562152773? If you insist that checking tier2, tier3 and tier4 is necessary as well, you need to check it the same way.

**Comment by mbukatov** [comment]
Thank you for review Elad.

**Pull request merged**
