### PR TITLE
Use the function "get_ceph_tools_pod" in the utility "ceph_health_check_base" to make it more generic

### PR DESCRIPTION
**Pull request by yitzhak12**
In the pr, I implemented the following:

Use the function `get_ceph_tools_pod` in the utility `ceph_health_check_base`. That way, we can easily extend it for MS and FAAS clusters. Also, it will make the function `ceph_health_check_base` more generic.

Another three more small updates related to the change above:
- Update the function `get_ceph_tools_pod` to get the `namespace` param, and patch the MS consumer rook-ceph-tool deployment.
- Update the function `patch_consumer_toolbox` to get the rook-ceph-tools pod param if provided, and add a return value of the new pod object after patching the rook-ceph-tools deployment.
- Update the method `exec_ceph_cmd` to get two more additional parameters: `out_yaml_format`, `timeout`.

### CODE REVIEW

**Comment by yitzhak12** [comment]
I successfully deployed a Vspherer 4.14 cluster using the PR: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/26446/.

**Comment by yitzhak12** [comment]
The failure above does not relate to the pr changes. It's related to the BZ https://bugzilla.redhat.com/show_bug.cgi?id=2219355.

**Comment by jilju** [comment]
@yitzhak12 
I think wait option in the function get_ceph_tools_pod and consuming get_ceph_tools_pod function in ceph_health_check_base is sufficient.

```
$ git diff
diff --git a/ocs_ci/ocs/resources/pod.py b/ocs_ci/ocs/resources/pod.py
index 37a7ccd8..dcedf92b 100644
--- a/ocs_ci/ocs/resources/pod.py
+++ b/ocs_ci/ocs/resources/pod.py
@@ -687,13 +687,14 @@ def get_all_pods(
     return pod_objs
 
 
-def get_ceph_tools_pod(skip_creating_pod=False):
+def get_ceph_tools_pod(skip_creating_pod=False, wait_time=None):
     """
     Get the Ceph tools pod
 
     Args:
         skip_creating_pod (bool): True if user doesn't want to create new tool box
             if it doesn't exist
+        wait_time (int): Time in seconds to initially wait for the tools pod
 
     Returns:
         Pod object: The Ceph tools pod object
@@ -721,6 +722,8 @@ def get_ceph_tools_pod(skip_creating_pod=False):
         selector=constants.TOOL_APP_LABEL,
         cluster_kubeconfig=cluster_kubeconfig,
     )
+    if wait_time:
+        helpers.wait_for_resource_state(ocp_pod_obj, constants.STATUS_RUNNING, timeout=wait_time)
     ct_pod_items = ocp_pod_obj.data["items"]
     if not (ct_pod_items or skip_creating_pod):
         # setup ceph_toolbox pod if the cluster has been setup by some other CI
diff --git a/ocs_ci/utility/utils.py b/ocs_ci/utility/utils.py
index da24107a..d52b45ad 100644
--- a/ocs_ci/utility/utils.py
+++ b/ocs_ci/utility/utils.py
@@ -51,6 +51,7 @@ from ocs_ci.ocs.exceptions import (
     InteractivePromptException,
     NotFoundError,
 )
+from ocs_ci.ocs.resources.pod import get_ceph_tools_pod
 from ocs_ci.utility import version as version_module
 from ocs_ci.utility.flexy import load_cluster_info
 from ocs_ci.utility.retry import retry
@@ -2236,15 +2237,9 @@ def ceph_health_check_base(namespace=None):
     )
 
     namespace = namespace or config.ENV_DATA["cluster_namespace"]
-    run_cmd(
-        f"oc wait --for condition=ready pod "
-        f"-l app=rook-ceph-tools "
-        f"-n {namespace} "
-        f"--timeout=300s"
-    )
-    ceph_health_cmd = create_ceph_health_cmd(namespace)
+    tools_pod = get_ceph_tools_pod(wait_time=300)
     try:
-        health = run_cmd(ceph_health_cmd)
+        health = tools_pod.exec_ceph_cmd(ceph_cmd="ceph health")
     except CommandFailed as ex:
         if is_rados_connect_error_in_ex(ex) and is_ms_consumer_cluster():
             log.info("Patch the consumer rook-ceph-tools deployment")
```

**Comment by yitzhak12** [comment]
@jilju We can add the wait option in the function `get_ceph_tools_pod`. But we still need to add the namespace param in the function `get_ceph_tools_pod` and use this form: 

>  try:
        ct_pod = get_ceph_tools_pod(namespace=namespace)
    except (AssertionError, CephToolBoxNotFoundException) as ex:
        raise CommandFailed(ex)
    try:
        health = ct_pod.exec_ceph_cmd(
            ceph_cmd="ceph health", format=None, out_yaml_format=False, timeout=120
        )
    except CommandFailed as ex:
        if is_rados_connect_error_in_ex(ex) and is_ms_consumer_cluster():
            log.info("Patch the consumer rook-ceph-tools deployment")

So it returns a string and not a dict and waits 120 seconds for the ceph command instead of 600 seconds which is the default.

**Review by ebenahar — APPROVED** [review]

**Pull request merged**
