### PR TITLE
Adding option to skip downloading openshit-client

### PR DESCRIPTION
**Pull request by vavuthu**
Signed-off-by: vavuthu <vavuthu@redhat.com>

Fixes: #1583

### CODE REVIEW

**Comment by RazTamir** [comment]
Hi @vavuthu , is there anything to update in the docs?
Is there any new parameter to run-ci?

**Comment by petr-balogh** [comment]
@vavuthu I think that we can currently solve this issue by moving this line:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L572
in else block https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L580

If the client exists we do not care and do not expose nightly version because we don't want to download.

WDYT?

**Comment by vavuthu** [comment]
> Hi @vavuthu , is there anything to update in the docs?
> Is there any new parameter to run-ci?

There is no need to update doc. Its just an option to the end user ( NOT a cli parameter ) to skip the client download.

**Comment by vavuthu** [comment]
> @vavuthu I think that we can currently solve this issue by moving this line:
> https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L572
> in else block https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/utils.py#L580
> 
> If the client exists we do not care and do not expose nightly version because we don't want to download.
> 
> WDYT?
Above approach look good to me. only downside is when oc is exported into env variables and ocs-ci/bi/oc doesn't exist, we will end-up in same situation.

**Comment by vavuthu** [comment]
> Changed force_download_client to False and run the test case. It skips the client download as expected. see logs below 

2020-03-05 11:16:18,486 - INFO - tests.conftest.cluster.879 - All logs located at /tmp/ocs-ci-logs-1583387172
2020-03-05 11:16:18,487 - INFO - ocs_ci.deployment.factory.get_deployment.36 - Deployment key = aws_ipi
2020-03-05 11:16:18,487 - INFO - ocs_ci.deployment.factory.get_deployment.38 - Current deployment platform: AWS,deployment type: ipi
2020-03-05 11:16:18,488 - DEBUG - ocs_ci.utility.utils.get_openshift_client.577 - Client exists (/home/vavuthu/VJ/Gluster/automation/commits/MASTER/ocs-ci/bin/oc), skipping download.
2020-03-05 11:16:18,488 - INFO - ocs_ci.utility.utils.run_cmd.403 - Executing command: /home/vavuthu/VJ/Gluster/automation/commits/MASTER/ocs-ci/bin/oc version --client

> test  case passed even though site openshift-release.svc.ci.openshift.org and openshift-release-artifacts.svc.ci.openshift.org are not reachable.

``` 11:16:33 - Dummy-8 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/vavuthu/VJ/Gluster/automation/commits/MASTER/ocs-ci/ak/auth/kubeconfig get CephFileSystem  -A -o yaml
11:16:33 - Dummy-1 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/vavuthu/VJ/Gluster/automation/commits/MASTER/ocs-ci/ak/auth/kubeconfig get CephBlockPool  -A -o yaml
11:16:33 - Dummy-2 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/vavuthu/VJ/Gluster/automation/commits/MASTER/ocs-ci/ak/auth/kubeconfig get PersistentVolume  -A -o yaml
11:16:33 - Dummy-4 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/vavuthu/VJ/Gluster/automation/commits/MASTER/ocs-ci/ak/auth/kubeconfig get PersistentVolumeClaim  -A -o yaml
11:16:33 - Dummy-9 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/vavuthu/VJ/Gluster/automation/commits/MASTER/ocs-ci/ak/auth/kubeconfig get Namespace  -A -o yaml


===================================================================================== 1 passed in 23.50s =====================================================================================
(venv1) [vavuthu@localhost ocs-ci](fix_download_client)$```

**Pull request merged**
