### PR TITLE
Remove codespeed

### PR DESCRIPTION
**Pull request by Avilir**
Since we retired the codespeed (replaced by the performance-dashboard), removing it from the code.

Signed-off-by: Avi Layani <alayani@redhat.com>

### CODE REVIEW

**Review by pintojoy — APPROVED** [review]
LGTM

**Review by keesturam — APPROVED** [review]
LGTM. Thanks for cleaning this part of the code @Avilir

**Review by pintojoy — APPROVED** [review]
LGTM

**Review by ypersky1980 — COMMENTED** [review]
LGTM.

**Pull request merged**
