### PR TITLE
Pin ping3 version

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #9626 

Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Comment by vavuthu** [comment]
> Unknown PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: deployment PR Test Path: tests/ Additional Test Params: OCP VERSION: 4.16 OCS VERSION: 4.16 tested against branch: master
> 
> [Job](https://url.corp.redhat.com/d383858) state: ABORTED.

intentionally aborted the job since run started the successfully.

```
024-04-03 23:05:14  The kubeconfig file /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig doesn't exist!
2024-04-03 23:05:15  ============================= test session starts ==============================
2024-04-03 23:05:15  platform linux -- Python 3.8.16, pytest-6.2.5, py-1.11.0, pluggy-1.4.0
2024-04-03 23:05:15  rootdir: /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci, configfile: pytest.ini
2024-04-03 23:05:15  plugins: logger-0.5.1, metadata-1.11.0, html-3.1.1, marker-bugzilla-0.9.4, order-1.2.0, flaky-3.7.0, repeat-0.9.3
2024-04-03 23:05:15  
2024-04-03 23:05:15  ----------------------------- live log collection ------------------------------
2024-04-03 23:05:15  17:35:15 - MainThread - ocs_ci.utility.reporting - INFO  - polarion deployment_id: None
2024-04-03 23:05:16  17:35:16 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc get Node  --selector=node-role.kubernetes.io/worker -o yaml
2024-04-03 23:05:17  17:35:17 - MainThread - ocs_ci.utility.reporting - INFO  - polarion upgrade_id: None
2024-04-03 23:05:18  collected 1330 items / 1289 deselected / 41 selected
2024-04-03 23:05:18  
2024-04-03 23:05:18  tests/functional/deployment/test_deployment.py::test_deployment 
2024-04-03 23:05:18  -------------------------------- live log setup --------------------------------
2024-04-03 23:05:18  17:35:18 - MainThread - ocs_ci.utility.utils - INFO  - testrun_name: OCS4-16-Downstream-OCP4-16-VSPHERE-UPI-1AZ-RHCOS-3M-3W-deployment
2024-04-03 23:05:18  17:35:18 - MainThread - ocs_ci.utility.utils - INFO  - testrun_name: OCS4-16-Downstream-OCP4-16-VSPHERE-UPI-1AZ-RHCOS-3M-3W-deployment
2024-04-03 23:05:18  17:35:18 - MainThread - ocs_ci.utility.utils - INFO  - Retrieving the authentication config dictionary
```

Hence marking as verified

**Review by shylesh — APPROVED** [review]
Lgtm

**Review by clacroix12 — APPROVED** [review]

**Pull request merged**
