### PR TITLE
Add initial README and update as more work gets done.

### PR DESCRIPTION
**Pull request by vasukulkarni**
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by mbukatov** [comment]
Shouldn't you note somewhere in the README that the repository is based on https://github.com/red-hat-storage/cephci?

**Comment by clacroix12** [comment]
LGTM

**Comment by vasukulkarni** [comment]
> Shouldn't you note somewhere in the README that the repository is based on https://github.com/red-hat-storage/cephci?

Sure, I will mention that.

**Comment by vasukulkarni** [comment]
> Maybe you can separate the prerequisites to the different platforms - AWS deployment prerequisites, BM deployment prerequisites, etc.

@ebenahar this is merged , I will add a trello and address the comments.

**Pull request merged**
