### PR TITLE
Couchbase workload new implementation - 4.8 (#5108)

### PR DESCRIPTION
**Pull request by PrasadDesala**
backport couchbase new implementation to 4.8
Fixes: #5127 

Signed-off-by: Prasad Desala <tdesala@redhat.com>

### CODE REVIEW

**Comment by PrasadDesala** [comment]
Couple of tests in the couchbase test suite failed with some temp issue. Considering that the Couchbase tests were running using the new code and the changes in this PR is not affecting these tests, marking this PR as verified.

**Comment by PrasadDesala** [comment]
This is a backport PR and currently we do not have an option to test PR validation job against a release branch.
So, built an cluster on my fork and backport branch and validated this PR.

PR job: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/7950/

Added label verified.

**Comment by petr-balogh** [comment]
@PrasadDesala I see one of the test case failed:
```
>               assert num_events_pre_reboot[node.name] < len(
                    node.ocp.exec_oc_cmd(reboot_events_cmd)["items"]
                ), f"Reboot event not found on node {node.name}"
E               AssertionError: Reboot event not found on node compute-2
```
Is this ok?

**Comment by PrasadDesala** [comment]
> @PrasadDesala I see one of the test case failed:
> 
> ```
> >               assert num_events_pre_reboot[node.name] < len(
>                     node.ocp.exec_oc_cmd(reboot_events_cmd)["items"]
>                 ), f"Reboot event not found on node {node.name}"
> E               AssertionError: Reboot event not found on node compute-2
> ```
> 
> Is this ok?

Yes, some timing issue. The reboot event is not found in this test within the given time period. The node came reached ready state just after some sec. The cluster returned to healthy state and the next set of Couchbase test passed without any issues.

**Review by petr-balogh — APPROVED** [review]

**Review by Akarsha-rai — APPROVED** [review]

**Review by vavuthu — APPROVED** [review]

**Pull request merged**
