### PR TITLE
[WIP] Add a securityContext field for regaining root access on app pods

### PR DESCRIPTION
**Pull request by MeridianExplorer**
Fixes: #2368

### CODE REVIEW

**Comment by ebenahar** [comment]
@MeridianExplorer please also add this change to the yamls under ocs_ci/templates/workloads/fio

**Comment by MeridianExplorer** [comment]
@ebenahar - I added all YAMLs across the project.

**Comment by petr-balogh** [comment]
Updated first comment to Fixes: #issueNumber instead of Works around.  See https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue ;) @MeridianExplorer 

LGTM .

Do we need to open WA issue for this to track this issue still open with the link to the BZ to see if this is the solution or need to revert with other fix?

**Comment by MeridianExplorer** [comment]
Hey @petr-balogh - thanks for the review!
I actually didn't use `fixes` on purpose, since I wanted to use #2368 as a tracker for this solution, which might be a solution, or might be just a workaround. This is why I think we should leave the issue open, and track this solution (and the BZ) with it. What do you think?

**Comment by petr-balogh** [comment]
I think we should open new WA issue with the workaround label to track workaround and let this pr to close one issue we have now. I think we have this approach documented in our docs.

**Comment by petr-balogh** [comment]
https://github.com/red-hat-storage/ocs-ci/blob/master/docs/workarounds.md

**Comment by MeridianExplorer** [comment]
Deployment passed successfully.

After completing 30% of tier1 tests, we ran into a known MCG bug. While our code was trying to save the NooBaa DB dump, the command exited with code 137 and caused the entire test suite to fail. No idea why this would happen. I started another verification job.

**Comment by vasukulkarni** [comment]
we should change the label to verified after tier1 tests are clean.

**Comment by MeridianExplorer** [comment]
@vasukulkarni - Maybe we should run a more thorough check? I thought about adding at least tier1 of performance and workloads.
IIUC, tier1 doesn't include many of the pods changed in this PR, which might lead to unexpected results down the road.

**Comment by vasukulkarni** [comment]
> @vasukulkarni - Maybe we should run a more thorough check? I thought about adding at least tier1 of performance and workloads.
> IIUC, tier1 doesn't include many of the pods changed in this PR, which might lead to unexpected results down the road.

Sounds good to me, e2e should do as well.

**Comment by MeridianExplorer** [comment]
`level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply Terraform: failed to complete the change"`

An unrelated issue that we also hit on Jun 12 - retriggering.

**Comment by MeridianExplorer** [comment]
The one test that seemed to actually fail was `test_workload_rbd_cephfs_10g`.
Apparently, the added securityContext prevented the job from being created successfully.
Thus, I removed all securityContexts that were added to Jobs.

**Comment by ebenahar** [comment]
> @ebenahar - I added all YAMLs across the project.

I don't see changes under ocs_ci/templates/workloads

**Comment by MeridianExplorer** [comment]
@ebenahar - I reverted the change via d3ee063. It caused several failures, and cannot be used as part of those pods.

**Comment by MeridianExplorer** [comment]
Closed due to the NB SCC change being reverted

**Pull request closed without merging**
