### PR TITLE
[DNM]: Updating terraform version to 0.12.31

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #5592 

Change terraform version from  0.12.26 to 0.12.31

Signed-off-by: vavuthu <vavuthu@redhat.com>

### CODE REVIEW

**Comment by mbukatov** [comment]
Don't we need update terraform version on other places as well? In the issue, I noticed 3 different versions in multiple places.

**Comment by mbukatov** [comment]
This is what I see in cc9f04eb8:

```
$ rg terraform_version: | cat
ocs_ci/framework/conf/default_config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.9-ga-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-config.yaml:  terraform_version: "0.11.15"
ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-config.yaml:  terraform_version: "0.11.15"
ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-minus1-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.6-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.5-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-minus1-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-minus1-config.yaml:  terraform_version: "0.11.14"
ocs_ci/framework/conf/ocp_version/ocp-4.3-config.yaml:  terraform_version: "0.11.15"
ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-config.yaml:  terraform_version: "0.11.15"
ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.2-config.yaml:  terraform_version: "0.11.15"
ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.4-config.yaml:  terraform_version: "0.11.15"
ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-minus1-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.9-ga-minus1-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-minus1-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-minus1-config.yaml:  terraform_version: "0.11.14"
ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-minus1-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-config.yaml:  terraform_version: "0.12.26"
ocs_ci/framework/conf/ocp_version/ocp-4.11-config.yaml:  terraform_version: "0.12.26"
$ rg -I terraform_version: | sort | uniq -c
      2   terraform_version: "0.11.14"
      6   terraform_version: "0.11.15"
     20   terraform_version: "0.12.26"
```

I would suggest to replace all occurrences of `0.12.26` in these ocp_version config files, assuming the older ones with 0.11.z won't be actually deployed again so it's safe to leave it as it is.

**Review by jimdevops19 — APPROVED** [review]

**Review by petr-balogh — DISMISSED** [review]

**Review by clacroix12 — APPROVED** [review]

**Review by mbukatov — APPROVED** [review]

**Comment by mbukatov** [comment]
Hmm, the [verification job](https://github.com/red-hat-storage/ocs-ci/pull/5701#pullrequestreview-941851916) failed on this:

```
2022-04-14 06:34:15,507 - MainThread - INFO - ocs_ci.utility.utils.exec_cmd.572 - Executing command: /home/jenkins/bin/terraform init /home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/
2022-04-14 06:34:19,801 - MainThread - DEBUG - ocs_ci.utility.utils.exec_cmd.585 - Command stdout: [0m[1mInitializing modules...[0m
- bootstrap in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/vm
- compute_a_records in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/host_a_record
- compute_vm in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/vm
- control_plane_a_records in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/host_a_record
- control_plane_vm in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/vm
- dns_cluster_domain in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/cluster_domain
- ipam_bootstrap in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/ipam
- ipam_compute in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/ipam
- ipam_control_plane in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/ipam
- ipam_lb in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/ipam
- lb in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/lb
- lb_a_records in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/host_a_record
- lb_vm in ../../../workspace/qe-deploy-ocs-cluster/ocs-ci/external/installer/upi/vsphere/vm

[0m[1mInitializing the backend...[0m

[0m[1mInitializing provider plugins...[0m
- Checking for available provider plugins...
- Downloading plugin for provider "http" (hashicorp/http) 2.1.0...
- Downloading plugin for provider "null" (hashicorp/null) 3.1.1...
- Downloading plugin for provider "aws" (hashicorp/aws) 4.9.0...

2022-04-14 06:34:19,803 - MainThread - WARNING - ocs_ci.utility.utils.exec_cmd.591 - Command stderr: [31m
[0m[1m[31mProvider "vsphere" v2.1.1 is not compatible with Terraform 0.12.31.[0m[31m

Provider version 1.19.0 is the latest compatible version. Select it with 
the following constraint:

    version = "~> 1.19"

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.

Alternatively, upgrade to the latest version of Terraform for compatibility with newer provider releases.
[0m[0m
[31m
[1m[31mError: [0m[0m[1mincompatible provider version[0m

[0m[0m[0m

2022-04-14 06:34:19,803 - MainThread - DEBUG - ocs_ci.utility.utils.exec_cmd.594 - Command return code: 1
```

**Comment by vavuthu** [comment]
> PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: deployment PR Test Path: tests/ Additional Test Params: OCP VERSION: 4.10 OCS VERSION: 4.10 tested against branch: master
> 
> [Job FAILED](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/2703//testReport) (installation failed, tests not executed).

I will consider this as PASS as it failed in ```ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN Reduced data availability: 1 pg inactive, 3 pgs peering``` which is not related to this PR

**Review by petr-balogh — APPROVED** [review]

**Review by clacroix12 — APPROVED** [review]

**Review by mbukatov — APPROVED** [review]

**Pull request closed without merging**
