### PR TITLE
Set a fixed PVC size for cluster load with external cluster

### PR DESCRIPTION
**Pull request by ebenahar**
Signed-off-by: Elad Ben Aharon <ebenahar@redhat.com>

### CODE REVIEW

**Review by shylesh — APPROVED** [review]
+1

**Review by sidhant-agrawal — APPROVED** [review]

**Comment by petr-balogh** [comment]
Is this just temporary workaround and we need to properly fix this: #2869 Or if this is fixes we should add 
`Fixes: #2869 `
To first comment in this PR.

**Comment by shylesh** [comment]
> PR validation
> 
> Cluster Name: shmohanextt
> Cluster Configuration: conf/ocsci/external_rhcs_cluster.yaml
> PR Test Suite: tier1
> PR Test Path: tests/
> Additional Test Params:
> OCP VERSION: 4.5
> OCS VERSION: 4.5
> 
> [Job FAILED](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2784//testReport) (installation failed, tests not executed).

Ignore this failures, external cluster details not propagated properly for PR verification job

**Comment by ebenahar** [comment]
> @ebenahar is this just temporary workaround and we need to properly fix this: #2869 Or if this is fixes we should add
> `Fixes: #2869 `
> To first comment in this PR.

This is not a temp fix

**Comment by ebenahar** [comment]
Verification wasn't done on an external cluster

**Pull request merged**
