### PR TITLE
Ignore env checker for deployment and destroy.

### PR DESCRIPTION
**Pull request by petr-balogh**
Fixing issue #246

### CODE REVIEW

**Comment by petr-balogh** [comment]
Verification succeed:

```bash
(.venv) pbalogh@MacBook-Pro ocs-ci (ignore-env-checker-for-deployment) $ run-ci -m deployment --cluster-name=pbalogh-check --cluster-path=/Users/pbalogh/tmp/cluseters/pbalogh-check tests/

11:24:57 - MainThread - utility.utils - INFO - Executing command: oc wait --for condition=ready pod -l app=rook-discover -n openshift-storage --timeout=120s
11:24:58 - MainThread - ocs.utils - INFO - Creating rook resource from cluster.yaml
11:24:58 - MainThread - utility.utils - INFO - Executing command: oc --kubeconfig /Users/pbalogh/tmp/cluseters/pbalogh-check/auth/kubeconfig create -f /Users/pbalogh/tmp/cluseters/pbalogh-check/cluster.yaml -o yaml
11:24:59 - MainThread - ocs.utils - INFO - Creating rook resource from toolbox.yaml
11:24:59 - MainThread - utility.utils - INFO - Executing command: oc --kubeconfig /Users/pbalogh/tmp/cluseters/pbalogh-check/auth/kubeconfig create -f /Users/pbalogh/tmp/cluseters/pbalogh-check/toolbox.yaml -o yaml
11:25:00 - MainThread - tests.ecosystem.deployment.test_ocs_basic_install - INFO - Waiting 15 seconds...
11:25:15 - MainThread - ocs.utils - INFO - Creating rook resource from storage-manifest.yaml
11:25:15 - MainThread - utility.utils - INFO - Executing command: oc --kubeconfig /Users/pbalogh/tmp/cluseters/pbalogh-check/auth/kubeconfig create -f /Users/pbalogh/tmp/cluseters/pbalogh-check/storage-manifest.yaml -o yaml
11:25:16 - MainThread - ocs.utils - INFO - Creating rook resource from service-monitor.yaml
11:25:16 - MainThread - utility.utils - INFO - Executing command: oc --kubeconfig /Users/pbalogh/tmp/cluseters/pbalogh-check/auth/kubeconfig create -f /Users/pbalogh/tmp/cluseters/pbalogh-check/service-monitor.yaml -o yaml
11:25:16 - MainThread - ocs.utils - INFO - Creating rook resource from prometheus-rules.yaml
11:25:16 - MainThread - utility.utils - INFO - Executing command: oc --kubeconfig /Users/pbalogh/tmp/cluseters/pbalogh-check/auth/kubeconfig create -f /Users/pbalogh/tmp/cluseters/pbalogh-check/prometheus-rules.yaml -o yaml
11:25:17 - MainThread - tests.ecosystem.deployment.test_ocs_basic_install - INFO - Waiting 15 seconds...
11:25:32 - MainThread - tests.ecosystem.deployment.test_ocs_basic_install - INFO - Done creating rook resources, waiting for HEALTH_OK
11:25:32 - MainThread - utility.utils - INFO - Executing command: oc wait --for condition=ready pod -l app=rook-ceph-tools -n openshift-storage --timeout=120s
11:25:33 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage get pod -l 'app=rook-ceph-tools' -o jsonpath='{.items[0].metadata.name}'
11:25:34 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-76c7d559b6-7t8zj ceph health
11:25:36 - MainThread - tests.ecosystem.deployment.test_ocs_basic_install - INFO - HEALTH_OK, install successful.
PASSED                                                                                                                                                                                                                                 [100%]

================================================================================================= 1 passed, 17 deselected in 1989.70 seconds =================================================================================================
```

**Comment by petr-balogh** [comment]
> Seems to work. But for a test class methods, the marker needs to be applied on a class level.

Yes, the fixture is class level from what I saw in the code so makes sense to me to mark class

**Comment by ksandha** [comment]
Hitting this issue again. with latest commits of 24th June.  Deployment failing when the "oc cluster-info" is running before the cluster is deployed.  
```
(.venv) [ksandha@ksandha ocs-ci]$ run-ci -m deployment --ocsci-conf conf/ocsci/default_config.yaml --cluster-conf conf/ocs_basic_install.yml --cluster-name ksandha-ocs-deployment --cluster-path /home/ksandha/Documents/workspace/ tests/ --deploy
CMD error:: Unable to connect to the server: dial tcp: lookup api.ksandha-ocs-deployment.qe.rh-ocs.com on 10.75.5.25:53: no such host

Cluster is not ready to use: Error during execution of command: ['oc', 'cluster-info'].
Error is Unable to connect to the server: dial tcp: lookup api.ksandha-ocs-deployment.qe.rh-ocs.com on 10.75.5.25:53: no such host

==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /home/ksandha/Documents/workspace/ocs-ci, inifile: pytest.ini
plugins: reportportal-1.0.5
collected 20 items / 19 deselected / 1 selected                                                                                                                                              

tests/ecosystem/deployment/test_ocs_basic_install.py::test_cluster_is_running 
--------------------------------------------------------------------------------------- live log setup ---------------------------------------------------------------------------------------
14:26:15 - MainThread - root - INFO - All logs are located under /tmp/logs
14:26:15 - MainThread - tests.conftest - INFO - Running OCS basic installation
14:26:15 - MainThread - oc.openshift_ops - INFO - Testing access to cluster with /home/ksandha/Documents/workspace/auth/kubeconfig
14:26:15 - MainThread - utility.utils - INFO - Executing command: oc cluster-info
14:26:15 - MainThread - utility.utils - ERROR - CMD error:: Unable to connect to the server: dial tcp: lookup api.ksandha-ocs-deployment.qe.rh-ocs.com on 10.75.5.25:53: no such host
14:26:15 - MainThread - oc.openshift_ops - ERROR - Cluster is not ready to use: Error during execution of command: ['oc', 'cluster-info'].
                                                   Error is Unable to connect to the server: dial tcp: lookup api.ksandha-ocs-deployment.qe.rh-ocs.com on 10.75.5.25:53: no such host
14:26:15 - MainThread - tests.conftest - INFO - A testing cluster will be deployed and cluster information stored at: /home/ksandha/Documents/workspace/
14:26:15 - MainThread - tests.conftest - INFO - Generating install-config
14:26:15 - MainThread - utility.utils - INFO - Executing command: mkdir -p /home/ksandha/Documents/workspace/

```

**Comment by petr-balogh** [comment]
>  --ocsci-conf conf/ocsci/default_config.yaml --cluster-conf conf/ocs_basic_install.yml

Hey,
just tried to run and I see that installation just started to run without this issue on my machine.

I see you are using those params ` --ocsci-conf conf/ocsci/default_config.yaml --cluster-conf conf/ocs_basic_install.yml`.

`--ocsci-conf conf/ocsci/default_config.yaml` this you don't have to pass at all, this file is auto loaded and shouldn't be passed anywhere. 

The second one param `--cluster-conf conf/ocs_basic_install.yml` if you don't have any own configuration inside this file it's also just example file which in original state doesn't provide any change on top of default one.

Please recheck once more and if you still see this issue try to debug a bit with ipdb and provide more info in some new issue opened about this bug. This PR is already closed so not update here please.

**Pull request merged**
