### PR TITLE
Approve csrs

### PR DESCRIPTION
**Pull request by clacroix12**
Jira: [OCSQE-321](https://projects.engineering.redhat.com/browse/OCSQE-321)

### CODE REVIEW

**Comment by clacroix12** [comment]
Verified in [this deployment job](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/6920/console) that the CSRs are approved:

```
02:17:43 - MainThread - ocs_ci.utility.csr - INFO - Approving CSRs
02:17:43 - MainThread - ocs_ci.utility.csr - INFO - Retrieving CSR data
02:17:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get csr  -n default -o yaml
02:17:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6
02:17:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f
02:17:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f csr-hx4m8
02:17:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn
02:17:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn csr-w5fg2
02:17:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn csr-w5fg2 csr-wnzzw
02:17:44 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn csr-w5fg2 csr-wnzzw csr-wtbj7
02:17:44 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn csr-w5fg2 csr-wnzzw csr-wtbj7 csr-xfms7
02:17:44 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig adm certificate approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn csr-w5fg2 csr-wnzzw csr-wtbj7 csr-xfms7 csr-xqtxf
02:17:44 - MainThread - ocs_ci.utility.csr - INFO - Checking for Pending CSRs
02:17:44 - MainThread - ocs_ci.utility.csr - INFO - Retrieving CSR data
02:17:44 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n default --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get csr  -n default -o yaml
02:17:45 - MainThread - ocs_ci.utility.csr - INFO - All CSRs approved
```

The deployment failed however it still proves that the logic here is working as intended so I'm marking as verified.

**Comment by petr-balogh** [comment]
@clacroix12 what I do not understand is why the command is executed each time with one more item:
```
 approve csr-7lkn6
 approve csr-7lkn6 csr-bzx7f 
 approve csr-7lkn6 csr-bzx7f csr-hx4m8
 approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn
```
From the logic I see that you are iterating over the items and just getting the name 
`cmd = f"{cmd} {item.get('metadata').get('name')}"`

So do not understand why there is always one more. Will try to debug once I will have cluster for verification for other fix which will try to do this approve once more.

**Comment by RazTamir** [comment]
> @clacroix12 what I do not understand is why the command is executed each time with one more item:
> 
> ```
>  approve csr-7lkn6
>  approve csr-7lkn6 csr-bzx7f 
>  approve csr-7lkn6 csr-bzx7f csr-hx4m8
>  approve csr-7lkn6 csr-bzx7f csr-hx4m8 csr-t2bhn
> ```
> 
> From the logic I see that you are iterating over the items and just getting the name
> `cmd = f"{cmd} {item.get('metadata').get('name')}"`
> 
> So do not understand why there is always one more. Will try to debug once I will have cluster for verification for other fix which will try to do this approve once more.

I was actually reviewed the same :)

The issue is here:
https://github.com/red-hat-storage/ocs-ci/pull/1896/files#diff-14072d12d253c891ce29bf52dcda7ac5R21-R23
```
cmd = "adm certificate approve"
    csr_conf = get_csr_resource()
    for item in csr_conf.data.get('items'):
        cmd = f"{cmd} {item.get('metadata').get('name')}"
        csr_conf.exec_oc_cmd(cmd)
```
using cmd parameter for the "adm certificate approve" command and also in the expanding of it:
cmd = f"{cmd} {item.get('metadata').get('name')}".
So first time it will be:
1) cmd = f'"adm certificate approve" {item.get('metadata').get('name')}'
2) cmd = f'"adm certificate approve" {item.get('metadata').get('name')}' {item.get('metadata').get('name')}'

and so on

**Comment by petr-balogh** [comment]
Yep @RazTamir I realized it when I looked at this more closely again in the code on my laptop and fixed in https://github.com/red-hat-storage/ocs-ci/pull/1898 .

Finally looks like we have unblocked OCP 4.4 deployment on VmWare once we will merge ^.

**Pull request merged**
