### PR TITLE
Make test_jenkins_simulation work on all architectures

### LINKED ISSUE #4027: arch-specific acceptance test: test_jenkins_simulation
This test always fails on non-amd64 platforms because `quay.io/ocsci/git-alpine-image` isn't multi-arch. We should either:

* Use a different image
* Build the image on all arches
* Exclude the test from platforms it won't run on
* Remove the acceptance marker from the test

### PR DESCRIPTION
**Pull request by zmc**
This fixes #4027. I just had tests on ppc64le pass.

### CODE REVIEW

**Comment by zmc** [comment]
Before: https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci-kvm/220/testReport/
After: https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci-kvm/229/testReport/

**Comment by vasukulkarni** [comment]
Prasad was planning to update the image in quay.io/ocsci, but I think we can consume from here until its done, The issue is fio install on x86 that keeps failing..

**Review by vasukulkarni — APPROVED** [review]

**Comment by zmc** [comment]
The nice thing about this is it removes the need to maintain the image yourselves. Where can I find out more about the fio issue?

**Comment by vasukulkarni** [comment]
> The nice thing about this is it removes the need to maintain the image yourselves. Where can I find out more about the fio issue?

Sorry the issue is with the git, https://github.com/red-hat-storage/ocs-ci/issues/3895 , The PR that closed it preinstalled git to avoid this one, I believe we will start seeing 3895 in x86..

**Comment by zmc** [comment]
ah, thanks for linking that. I was unaware of that history. Well, this will use the Alpine image and not Debian, so it may just not fail in the same way. Try:
`podman run --rm mirror.gcr.io/library/alpine sh -c "apk add git fio && which git && which fio"`

I haven't seen it fail, and it takes only 2-10s where I've run it (my amd64 laptop and a ppc64le test machine)

**Comment by vasukulkarni** [comment]
> `podman run --rm mirror.gcr.io/library/alpine sh -c "apk add git fio && which git && which fio"`

can confirm it works and its fast!, so lets see :+1:

**Review by clacroix12 — APPROVED** [review]

**Pull request merged**
