### PR TITLE
Default snapshot class name in external mode

### PR DESCRIPTION
**Pull request by jilju**
Update helpers.default_volumesnapshotclass to select volume snapshot class name in external mode cluster
Signed-off-by: Jilju Joy <jijoy@redhat.com>

### CODE REVIEW

**Review by wusui — DISMISSED** [review]
Looks good

**Review by rachael-george — APPROVED** [review]
LGTM

**Comment by jilju** [comment]
@red-hat-storage/top-level-reviewers Please review.

**Review by rachael-george — APPROVED** [review]
LGTM

**Review by wusui — APPROVED** [review]
LGTM

**Review by vasukulkarni — APPROVED** [review]

**Pull request merged**
