### PR TITLE
Rename ocs_operator_image to ocs_registry_image

### PR DESCRIPTION
**Pull request by petr-balogh**
Fixes: #891

Signed-off-by: Petr Balogh <pbalogh@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
@andrewschoen @zmc can you please test this in your CI if I didn't miss anything?
Thanks

@clacroix12 this will help with you parameter in the our jenkins, can you please verify this with your job MR?

**Comment by clacroix12** [comment]
I have kicked off a deployment test [here](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/1443/)

As it's simply using the default config with this branch and the [ocs4-jenkins branch](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/merge_requests/77) for adding this, the default behavior should be that no key/value is added to the custom config generated for jenkins. I've confirmed this behavior in the [config](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/clacroix-pr-893/clacroix-pr-893_20191011T180024/ocsci_conf.yaml).

Once the ocs4-jenkins branch that adds this param to the jenkins jobs is merged and applied we can actually pass a value through and test the value is read in properly.

**Comment by clacroix12** [comment]
Kicked off another [deployment test](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/1500/) since a fix for #895 has been merged.

**Comment by petr-balogh** [comment]
> Kicked off another [deployment test](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/1500/) since a fix for #895 has been merged.
> 
> Edit: This will need a rebase before the fix will take effect.

Thanks @clacroix12 , can you please ping @zmc or @andrewschoen if the see some conflict with their CI? I've already mentioned them but probably missed the comment. Thans

**Comment by petr-balogh** [comment]
Verified here:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/1534/console
You can see that passed image from parameter was passed to the yaml and was used.
```
12:28:26 - MainThread - ocs_ci.utility.templating - INFO - apiVersion: v1
                                                           kind: Namespace
                                                           metadata:
                                                             labels:
                                                               openshift.io/cluster-monitoring: 'true'
                                                             name: openshift-storage
                                                           spec: {}
                                                           ---
                                                           apiVersion: v1
                                                           kind: Namespace
                                                           metadata:
                                                             name: local-storage
                                                           spec: {}
                                                           ---
                                                           apiVersion: operators.coreos.com/v1
                                                           kind: OperatorGroup
                                                           metadata:
                                                             name: openshift-storage-operatorgroup
                                                             namespace: openshift-storage
                                                           spec:
                                                             serviceAccount:
                                                               metadata:
                                                                 creationTimestamp: null
                                                             targetNamespaces:
                                                             - openshift-storage
                                                           ---
                                                           apiVersion: operators.coreos.com/v1
                                                           kind: OperatorGroup
                                                           metadata:
                                                             name: local-operator-group
                                                             namespace: local-storage
                                                           spec:
                                                             serviceAccount:
                                                               metadata:
                                                                 creationTimestamp: null
                                                             targetNamespaces:
                                                             - openshift-storage
                                                           ---
                                                           apiVersion: operators.coreos.com/v1alpha1
                                                           kind: CatalogSource
                                                           metadata:
                                                             name: local-storage-manifests
                                                             namespace: openshift-marketplace
                                                           spec:
                                                             description: An operator to manage local volumes
                                                             displayName: Local Storage Operator
                                                             icon:
                                                               base64data: ''
                                                               mediatype: ''
                                                             image: quay.io/gnufied/local-registry:v4.2.0
                                                             publisher: Red Hat
                                                             sourceType: grpc
                                                           ---
                                                           apiVersion: operators.coreos.com/v1alpha1
                                                           kind: CatalogSource
                                                           metadata:
                                                             name: ocs-catalogsource
                                                             namespace: openshift-marketplace
                                                           spec:
                                                             displayName: Openshift Container Storage
                                                             icon:
                                                               base64data: ''
                                                               mediatype: ''
                                                             image: quay.io/rhceph-dev/ocs-registry:4.2-143.3c517a0.release_4.2
                                                             publisher: Red Hat
                                                             sourceType: grpc
12:28:26 - MainThread - ocs_ci.utility.templating - INFO - apiVersion: operators.coreos.com/v1alpha1
                                                           kind: Subscription
                                                           metadata:
                                                             name: ocs-subscription
                                                             namespace: openshift-storage
                                                           spec:
                                                             channel: alpha
                                                             name: ocs-operator
                                                             source: ocs-catalogsource
                                                             sourceNamespace: openshift-marketplace
12:28:26 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get node  -o yaml
12:28:27 - MainThread - ocs_ci.deployment.deployment - INFO - Label nodes: ip-10-0-143-158.us-east-2.compute.internal ip-10-0-152-120.us-east-2.compute.internal ip-10-0-169-236.us-east-2.compute.internal with label: cluster.ocs.openshift.io/openshift-storage=''
12:28:27 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig label nodes ip-10-0-143-158.us-east-2.compute.internal ip-10-0-152-120.us-east-2.compute.internal ip-10-0-169-236.us-east-2.compute.internal cluster.ocs.openshift.io/openshift-storage=''
12:28:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc create -f /tmp/olm_manifest9_8imsep
12:28:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-marketplace --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get CatalogSource ocs-catalogsource -n openshift-marketplace -o yaml
12:28:28 - MainThread - ocs_ci.ocs.resources.catalog_source - INFO - Problem while reading state status of catalog source ocs-catalogsource, data: {'apiVersion': 'operators.coreos.com/v1alpha1', 'kind': 'CatalogSource', 'metadata': {'creationTimestamp': '2019-10-16T12:28:29Z', 'generation': 1, 'name': 'ocs-catalogsource', 'namespace': 'openshift-marketplace', 'resourceVersion': '15538', 'selfLink': '/apis/operators.coreos.com/v1alpha1/namespaces/openshift-marketplace/catalogsources/ocs-catalogsource', 'uid': '75643621-f010-11e9-9e24-06c7467007ea'}, 'spec': {'displayName': 'Openshift Container Storage', 'icon': {'base64data': '', 'mediatype': ''}, 'image': 'quay.io/rhceph-dev/ocs-registry:4.2-143.3c517a0.release_4.2', 'publisher': 'Red Hat', 'sourceType': 'grpc'}, 'status': {'registryService': {'createdAt': '2019-10-16T12:28:29Z', 'port': 
```

**Pull request merged**
