### PR TITLE
Add multus prod configs

### PR DESCRIPTION
**Pull request by clacroix12**
Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by clacroix12** [comment]
@petr-balogh @vavuthu I only found two polarion IDs related to multus, one for UI deployment and the other for CLI. This is why the polarion IDs are identical across these deployment configs.

I have created vsphere upi configs for both RHEL and RHCOS, as well as VSAN and VMFS. Please let me know if I'm missing any scenarios or if we don't need all of these. I'm unsure exactly which scenarios we need to cover with prod configs.

**Review by vavuthu — APPROVED** [review]

**Review by Akarsha-rai — APPROVED** [review]

**Comment by sidhant-agrawal** [comment]
@vavuthu @clacroix12 there are three configuration possible with multus
- If only the public selector is specified
- If only the cluster selector is specified
- If both public and cluster selectors are specified

Do we plan to include those configurations as well?

**Comment by clacroix12** [comment]
@sidhant-agrawal currently we only have the one configuration option `enable_multus` so I created prod configs that use that. This only creates the NAD for the public network. If we also need to support the private network we may want to refactor `enable_multus` to `enable_multus_public` and create a new config option for `enable_multus_private`. We can then create the corresponding NADs using those config options and adjust verification using them as well. @vavuthu thoughts?

**Comment by vavuthu** [comment]
public network is mandatory. either we have ONLY public network or public network + cluster network.

currently we have tested public network. I am not sure about public network + cluster network. @sidhant-agrawal could you please confirm here.

Once we have automation/infra ready, we need to refactor and have separate configs.

**Comment by sidhant-agrawal** [comment]
>I don't think there is a "private cluster selector only" scenario according to this since the public network is mandatory. Can you confirm?

> public network is mandatory. either we have ONLY public network or public network + cluster network.
> 

@clacroix12 @vavuthu 
`public network is mandatory` -> this is no longer true.
Please refer to [multus section](https://rook.io/docs/rook/v1.6/ceph-cluster-crd.html#multus) in docs for more information and possible configurations.

> currently we have tested public network. I am not sure about public network + cluster network. @sidhant-agrawal could you please confirm here.
> 
We have tested `public network + cluster network` on BareMetal setup.

**Pull request merged**
