### PR TITLE
Make sure pvc and pod names are unique.

### PR DESCRIPTION
**Pull request by wusui**
Avoids AlreadyExists exceptions.

Signed-off-by: wusui <wusui@redhat.com>

### CODE REVIEW

**Review by tiffanyn108 — APPROVED** [review]
LGTM.

**Review by ramkiperiy — APPROVED** [review]

**Comment by ramkiperiy** [comment]
Fix for github issue https://github.com/red-hat-storage/ocs-ci/issues/3835

**Comment by Avilir** [comment]
LGTM

**Comment by tiffanyn108** [comment]
This PR will fix the issue which is failing on IBM cluster.
https://github.com/red-hat-storage/ocs-ci/issues/3835

**Review by vasukulkarni — APPROVED** [review]

**Pull request merged**
