### PR TITLE
Filter tests from report if its skipped because of ocs version mismatch

### PR DESCRIPTION
**Pull request by shylesh**
Signed-off-by: Shylesh Kumar Mohan <shmohan@redhat.com>

### CODE REVIEW

**Comment by shylesh** [comment]
Verified locally

**Comment by petr-balogh** [comment]
Please update pytest.ini file skipif_ocs_version

**Comment by shylesh** [comment]
> @shylesh have you tested it or verified locally on some of examples? You can do some testing with --collect-only param so you should see if those were collected I hope.

@petr-balogh ,
Before adding pytest.ini change I did local testing, however along with pytest.ini I did a rebase on master. I can test it again if you want.

**Comment by shylesh** [comment]
> @shylesh How did you verify locally? If you were able to use `--collect-only` would you be able to paste the output here in the PR?

**Comment by shylesh** [comment]
Sorry accidentally closed the PR, reopening now.

**Comment by shylesh** [comment]
```
Always decorator applied to 
<Module tests/temp/test_fio_another.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>

Case1: 
@skipif_ocs_version("<4.3")
    def test_fio_with_block_storage(self):

Result
======
$ run-ci --collect-only tests/temp --ocs-version 4.3
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
11:13:28 - MainThread - tests.conftest - INFO - ('<4.3',)  =====>CONDITION
collected 2 items                                                              
<Module tests/temp/test_fio_another.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>


Case 2
======
run-ci --collect-only tests/temp --ocs-version 4.2
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
11:13:32 - MainThread - tests.conftest - INFO - ('<4.3',)  =====>CONDITION
11:13:32 - MainThread - tests.conftest - INFO - Test: <Function test_fio_with_block_storage> will be skipped due to ('<4.3',)
collected 2 items                                                              
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>

run-ci --collect-only tests/temp --ocs-version 4.3
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
13:15:47 - MainThread - tests.conftest - INFO - (['<4.5', '>=4.3'],)   ======>CONDITION
13:15:47 - MainThread - tests.conftest - INFO - Test: <Function test_fio_with_block_storage> will be skipped due to (['<4.5', '>=4.3'],)
collected 2 items                                                              
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>

 run-ci --collect-only tests/temp --ocs-version 4.2
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
13:15:54 - MainThread - tests.conftest - INFO - (['<4.5', '>=4.3'],)  ====>CONDITION
collected 2 items                                                              
<Module tests/temp/test_fio_another.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>

**Comment by shylesh** [comment]
> @shylesh How did you verify locally? If you were able to use `--collect-only` would you be able to paste the output here in the PR?

Sorry, I missed an issue in the previous commit, pushed and tested now.

**Comment by shylesh** [comment]
TESTS
========
CASE1
=====
```python
1. class TestFIOWorkload(ManageTest):

    @skipif_ocs_version(['<4.5', '>=4.3'])
    def test_fio_with_block_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')

2. class TestFIOWorkload(ManageTest):

    def test_fio_with_object_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')
```

Command Ran:
===========
run-ci --collect-only tests/temp --ocs-version 4.3


Tests Collected
================
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
```python
13:49:29 - MainThread - tests.conftest - INFO - (['<4.5', '>=4.3'],)
13:49:29 - MainThread - tests.conftest - INFO - Test: <Function test_fio_with_block_storage> will be skipped due to (['<4.5', '>=4.3'],)
collected 2 items                                                              
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_object_storage>
```

RESULT:
======
As expected test_fio_with_block_storage has been skipped and will not appear in the report.



CASE2
=====
```python
1.class TestFIOWorkload(ManageTest):

    @skipif_ocs_version(['<4.5', '>=4.3'])
    def test_fio_with_block_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')

2. class TestFIOWorkload(ManageTest):

    def test_fio_with_object_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')

```
Command Run:
==========
run-ci --collect-only tests/temp --ocs-version 4.2

TESTS COLLECTED:
=============
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
```python
13:52:01 - MainThread - tests.conftest - INFO - (['<4.5', '>=4.3'],)
collected 2 items                                                              
<Module tests/temp/test_fio_another.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_object_storage>

============================ no tests ran in 0.02s =============================
```

RESULT:
======
As expected test_fio_with_block_storage has been selected



CASE3:
=====
```python
1. class TestFIOWorkload(ManageTest):

    @skipif_ocs_version('<4.3')
    def test_fio_with_block_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')

2. class TestFIOWorkload(ManageTest):

    def test_fio_with_object_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')
```
Command Run:
==========
run-ci --collect-only tests/temp --ocs-version 4.2


TESTS COLLECTED:
==============
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
```python
13:55:11 - MainThread - tests.conftest - INFO - ('<4.3',)
13:55:11 - MainThread - tests.conftest - INFO - Test: <Function test_fio_with_block_storage> will be skipped due to ('<4.3',)
collected 2 items                                                              
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_object_storage>

============================ no tests ran in 0.02s =============================
```

RESULT:
=======
As expected test_fio_with_block_storage has been skipped and dropped from report



CASE4
=====
```python
1.
class TestFIOWorkload(ManageTest):

    @skipif_ocs_version('<4.3')
    def test_fio_with_block_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')

2. class TestFIOWorkload(ManageTest):

    def test_fio_with_object_storage(self):
        name = 'test_workload'
        spec = self.pod_obj.data.get('spec')
```
Command Run:
==========
run-ci --collect-only tests/temp --ocs-version 4.3

TESTS COLLECTED:
==============
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /mnt/shmohan/Downloads/git/ocs-ci, inifile: pytest.ini
plugins: metadata-1.8.0, logger-0.5.1, reportportal-1.0.5, ordering-0.6, html-2.0.1, marker-bugzilla-0.9.4
collecting ... 
--------------------------------------------------------- live log collection ----------------------------------------------------------
```python
13:56:33 - MainThread - tests.conftest - INFO - ('<4.3',)
collected 2 items                                                              
<Module tests/temp/test_fio_another.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_block_storage>
<Module tests/temp/test_fio_workload.py>
  <Class TestFIOWorkload>
      <Function test_fio_with_object_storage>

============================ no tests ran in 0.02s =============================
```

RESULT:
======
As expected all tests are selected

**Comment by shylesh** [comment]
Sorry for being unclear in the earlier output, I have updated in detail. Thanks @clacroix12 for making me realize.

**Pull request merged**
