### PR TITLE
Read file before passing to loader for local yaml files

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #851 

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by clacroix12** [comment]
Local testing output with fix:

```
In [1]: from ocs_ci.utility.templating import load_yaml

In [2]: y = load_yaml('test.yaml', multi_document=True)

In [3]: type(y)
Out[3]: generator

In [4]: for i in y:
   ...:     print(i)
   ...:
{'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'openshift-storage'}, 'spec': {}}
{'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'local-storage'}, 'spec': {}}
{'apiVersion': 'operators.coreos.com/v1', 'kind': 'OperatorGroup', 'metadata': {'name': 'openshift-storage-operatorgroup', 'namespace': 'openshift-storage'}, 'spec': {'serviceAccount': {'metadata': {'creationTimestamp': None}}, 'targetNamespaces': ['openshift-storage']}}
{'apiVersion': 'operators.coreos.com/v1', 'kind': 'OperatorGroup', 'metadata': {'name': 'local-operator-group', 'namespace': 'local-storage'}, 'spec': {'serviceAccount': {'metadata': {'creationTimestamp': None}}, 'targetNamespaces': ['openshift-storage']}}
{'apiVersion': 'operators.coreos.com/v1alpha1', 'kind': 'CatalogSource', 'metadata': {'name': 'local-storage-manifests', 'namespace': 'openshift-marketplace'}, 'spec': {'description': 'An operator to manage local volumes', 'displayName': 'Local Storage Operator', 'icon': {'base64data': '', 'mediatype': ''}, 'image': 'quay.io/gnufied/local-registry:v4.2.0', 'publisher': 'Red Hat', 'sourceType': 'grpc'}}
{'apiVersion': 'operators.coreos.com/v1alpha1', 'kind': 'CatalogSource', 'metadata': {'name': 'ocs-catalogsource', 'namespace': 'openshift-marketplace'}, 'spec': {'displayName': 'Openshift Container Storage', 'icon': {'base64data': '', 'mediatype': ''}, 'image': 'quay.io/ocs-dev/ocs-registry:latest', 'publisher': 'Red Hat', 'sourceType': 'grpc'}}
{'apiVersion': 'operators.coreos.com/v1alpha1', 'kind': 'Subscription', 'metadata': {'name': 'ocs-subscription', 'namespace': 'openshift-storage'}, 'spec': {'channel': 'alpha', 'name': 'ocs-operator', 'source': 'ocs-catalogsource', 'sourceNamespace': 'openshift-marketplace'}}
```

**Comment by vasukulkarni** [comment]
The examples I looked at show usage of with both file - open and open + read() , but if read is working better than just open so be it :)

**Comment by clacroix12** [comment]
> The examples I looked at show usage of with both file - open and open + read()

Do you have a link to an example of passing the file directly? The ones I looked at were iterating over the generator inside of the `with` block, so the file was still open. Since we are returning the generator to the caller in our code, we are outside of the context manager and the file is closed before we try to iterate.

**Comment by vasukulkarni** [comment]
> > The examples I looked at show usage of with both file - open and open + read()
> 
> Do you have a link to an example of passing the file directly? The ones I looked at were iterating over the generator inside of the `with` block, so the file was still open. Since we are returning the generator to the caller in our code, we are outside of the context manager and the file is closed before we try to iterate.

Here: https://www.programcreek.com/python/example/60272/yaml.safe_load_all

**Comment by clacroix12** [comment]
@vasukulkarni yeah it looks like in any scenario where the raw file is passed the generator is used while the file is open. Since we are returning the generator to the caller, reading the content is simple enough and seems to work.

**Comment by clacroix12** [comment]
I should clarify that this fixes an issue specifically with `multi_document=True` but the change applies to all local files passed to `load_yaml`. I will update the title.

**Pull request merged**
