### PR TITLE
for testing ci failures

### PR DESCRIPTION
**Pull request by vasukulkarni**
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
this is not for merge, just testing the CI merging will be blocked for failed tests.

**Comment by RazTamir** [comment]
> this is not for merge, just testing the CI merging will be blocked for failed tests.

And? found anything?
I am still not sure how it passed all the checks

**Comment by vasukulkarni** [comment]
@RazTamir can you add a approval, I am thinking multiple pushes might have caused the github to not reset the status.

**Comment by vasukulkarni** [comment]
Merge button is Green!

**Comment by RazTamir** [comment]
> Merge button is Green!

So I almost sure something changed as I remember I used to see a grayed button saying that I can still merge as admin but not a green button for sure

**Comment by vasukulkarni** [comment]
I am fixing this but "Name already protected: master", Trying to add one more rule

**Comment by vasukulkarni** [comment]
Fixed!

**Comment by vasukulkarni** [comment]
> > Merge button is Green!
> 
> So I almost sure something changed as I remember I used to see a grayed button saying that I can still merge as admin but not a green button for sure

My fault too here :)

**Pull request closed without merging**
