### PR TITLE
Cluster prefix duplication fix

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #1643

### CODE REVIEW

**Comment by clacroix12** [comment]
@petr-balogh verified that this doesn't affect our deployment, however this does add a caveat that if we are using one of the special aws prefixes that the second part of the cluster name is used as the prefix for determining uniqueness. for example:

cluster_name = lr1-clacroix-test

since `lr1` is a special rule, use the next part of the cluster_name so..

prefix = `clacroix`

**Comment by vasukulkarni** [comment]
> @petr-balogh verified that this doesn't affect our deployment, however this does add a caveat that if we are using one of the special aws prefixes that the second part of the cluster name is used as the prefix for determining uniqueness. for example:
> 
> cluster_name = lr1-clacroix-test
> 
> since `lr1` is a special rule, use the next part of the cluster_name so..
> 
> prefix = `clacroix`

We can check for the special rule to exist in any part of the cluster name as discussed?

**Comment by clacroix12** [comment]
@vasukulkarni i think i'd like to keep it as prefixes because they are referenced as prefixes in the aws code as well as here. Also to avoid the chance of someone hitting one of our 'prefixes' in the middle of the cluster name and causing the cleanup to miss resources. Even if we did use `in` as opposed to `startswith` i think we'd still have to determine the actual "prefix" here since we don't want to check uniqueness based on any of the special rule prefixes.

**Comment by vasukulkarni** [comment]
> @vasukulkarni i think i'd like to keep it as prefixes because they are referenced as prefixes in the aws code as well as here. Also to avoid the chance of someone hitting one of our 'prefixes' in the middle of the cluster name and causing the cleanup to miss resources. Even if we did use `in` as opposed to `startswith` i think we'd still have to determine the actual "prefix" here since we don't want to check uniqueness based on any of the special rule prefixes.

'jnk', 'dnd' are the only one that one could hit, and I dont recall anyone having that prefix as their username, we could just expand and make it 'jenkins', 'no-delete', I rather like the flexibility than stick to the prefix rule that is making other things harder.

**Comment by clacroix12** [comment]
@vasukulkarni i think we are keeping the prefixes short because we can only use so many characters for the resource names in aws. We end up having to truncate and we want most of the name to be descriptive. Its also not about having those specific prefixes as the cluster name but it could be within someones username. I've seen instances of some peoples usernames including their middle initial as well so something like `jnkennedy` would end up getting read in as a special use case and passed over for cleanup. Point is we avoid all of that if we explicitly match the actual prefix. I don't think using prefixes to define these rules makes anything more difficult now that this change will address the issue we had with uniqueness.

**Comment by vasukulkarni** [comment]
> @vasukulkarni i think we are keeping the prefixes short because we can only use so many characters for the resource names in aws. We end up having to truncate and we want most of the name to be descriptive. Its also not about having those specific prefixes as the cluster name but it could be within someones username. I've seen instances of some peoples usernames including their middle initial as well so something like `jnkennedy` would end up getting read in as a special use case and passed over for cleanup. Point is we avoid all of that if we explicitly match the actual prefix. I don't think using prefixes to define these rules makes anything more difficult now that this change will address the issue we had with uniqueness.

As I said, expanding is not really a big issue like 'jenkins' and 'no-delete',  even for the hypotical case like username 'jnkennedy', the current pr may strip the first part and use 'jnkkennedy' as prefix causing it to match the standard prefix 'jnk', we can worry about the corner case with 3 letter prefix or expand and solve it to make it more flexible.

**Comment by clacroix12** [comment]
The fix in this PR splits with `"-"` so unless it was `jnk-ennedy` it wouldn't be matched to a special prefix.

**Comment by vasukulkarni** [comment]
> The fix in this PR splits with `"-"` so unless it was `jnk-ennedy` it wouldn't be matched to a special prefix.

So I am now missing how does the PR once it removes the prefix is still able to cleanup?

**Comment by clacroix12** [comment]
> > The fix in this PR splits with `"-"` so unless it was `jnk-ennedy` it wouldn't be matched to a special prefix.
> 
> So I am now missing how does the PR once it removes the prefix is still able to cleanup?

The prefix isn't being removed, we are simply using the next part of the cluster name to detect other clusters using the same 'prefix'.

For example:

A cluster exists in aws named `dnd-vasu-test`

I'm trying to spin up a cluster named `dnd-clacroix-test`

Currently, we would grab the prefix `dnd` and check AWS for other clusters using that prefix to determine if there already exists a cluster using the prefix and then stops the user from creating a new one. This functionality is intended to stop people from spinning up multiple clusters with the same username to conserve AWS resources. The issue is that the prefix in my example isn't the username, it's the special prefix to control how the cluster is cleaned up by our aws cleanup job.

With my changes here, if the prefix (`dnd`) is found in the list of aws cleanup prefixes, we will grab the next part of the name (after splitting on '-') so the prefix would be `clacroix`. It would then check AWS for other clusters with `clacroix` in the name and let me create the cluster.

We don't actually remove the prefix from the cluster name, we simply use the next part of the name to determine if we are creating a cluster using the same "prefix" as another cluster in aws to stop us from creating multiple clusters per user.

Hopefully that makes sense.

**Comment by vasukulkarni** [comment]
> > > The fix in this PR splits with `"-"` so unless it was `jnk-ennedy` it wouldn't be matched to a special prefix.
> > 
> > 
> > So I am now missing how does the PR once it removes the prefix is still able to cleanup?
> 
> The prefix isn't being removed, we are simply using the next part of the cluster name to detect other clusters using the same 'prefix'.
> 
> For example:
> 
> A cluster exists in aws named `dnd-vasu-test`
> 
> I'm trying to spin up a cluster named `dnd-clacroix-test`
> 
> Currently, we would grab the prefix `dnd` and check AWS for other clusters using that prefix to determine if there already exists a cluster using the prefix and then stops the user from creating a new one. This functionality is intended to stop people from spinning up multiple clusters with the same username to conserve AWS resources. The issue is that the prefix in my example isn't the username, it's the special prefix to control how the cluster is cleaned up by our aws cleanup job.
> 
> With my changes here, if the prefix (`dnd`) is found in the list of aws cleanup prefixes, we will grab the next part of the name (after splitting on '-') so the prefix would be `clacroix`. It would then check AWS for other clusters with `clacroix` in the name and let me create the cluster.
> 
> We don't actually remove the prefix from the cluster name, we simply use the next part of the name to determine if we are creating a cluster using the same "prefix" as another cluster in aws to stop us from creating multiple clusters per user.
> 
> Hopefully that makes sense.

Now makes sense! 👍

**Pull request merged**
