### PR TITLE
Add HCI_PROVIDER_CLIENT_PLATFORMS adjustment for existing MS Conditions.

### PR DESCRIPTION
**Pull request by suchita-g**
Signed-off-by: suchita-g <sgatfane@redhat.com>

Enable use of ceph pod from provider from pod disruptions helps

### CODE REVIEW

**Comment by suchita-g** [comment]
verification" https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/2132/

**Review by amr1ta — APPROVED** [review]
Looking good

**Comment by suchita-g** [comment]
Verification Job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/2133/

**Review by amr1ta — APPROVED** [review]

**Comment by suchita-g** [comment]
Verification Job:  https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-odf-multicluster/2140/testReport/
Tier4a: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/31576/

**Review by jilju — APPROVED** [review]

**Review by jilju — APPROVED** [review]

**Review by petr-balogh — APPROVED** [review]

**Pull request merged**
