### PR TITLE
[WIP] Remove CI testing on python 3.6 to reduce travis-ci credit use

### PR DESCRIPTION
**Pull request by vasukulkarni**
This is to help reduce credit use from the new travis-ci.org

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by mbukatov** [comment]
Configuration for travis environment is here: https://github.com/red-hat-storage/ocs-ci/blob/master/.travis.yml the defaults from tox are used only when tox is used locally.

**Comment by vasukulkarni** [comment]
> Configuration for travis environment is here: https://github.com/red-hat-storage/ocs-ci/blob/master/.travis.yml the defaults from tox are used only when tox is used locally.

Thanks, removed from travis, I think removing from tox will also make sense for local environment.

**Review by vavuthu — APPROVED** [review]

**Comment by vasukulkarni** [comment]
Depends on Jenkins slave migration to CentOS 8

**Review by AviadP — APPROVED** [review]

**Comment by petr-balogh** [comment]
As we moved to github actions and we already have deleted python 3.6 from our matrix I am closing this one PR.
https://github.com/red-hat-storage/ocs-ci/blob/master/.travis.yml

**Pull request closed without merging**
