### PR TITLE
config namespace reference is set to every odf cli call

### PR DESCRIPTION
**Pull request by DanielOsypenko**
Pull request to address issue [#10445](https://github.com/red-hat-storage/ocs-ci/issues/10445)

### CODE REVIEW

**Comment by DanielOsypenko** [comment]
verification run https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/44539

**Comment by DanielOsypenko** [comment]
all test modifications passed https://url.corp.redhat.com/5b76434

**Comment by DanielOsypenko** [comment]
additional tests from the dir bellow Passed:
tests/functional/odf-cli/test_get_commands.py::TestGetCommands
link - https://url.corp.redhat.com/3238bee

**Comment by DanielOsypenko** [comment]
tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py::TestSubvolumesCommand - all Passed
console log - https://url.corp.redhat.com/0999eb8

**Review by AviadP — APPROVED** [review]

**Review by ebenahar — APPROVED** [review]

**Pull request merged**
