### PR TITLE
Fix for Issue #592 : "InvalidValue: [Errno 22] error in setxattr" error while creating CephFS based PVC

### PR DESCRIPTION
**Pull request by sidhant-agrawal**
Fixes: #592

Signed-off-by: Sidhant Agrawal <sagrawal@redhat.com>

### CODE REVIEW

**Comment by sidhant-agrawal** [comment]
> @sidhant-agrawal I think it would be better if we don't workaround this bug

In fixtures.py [L124](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/fixtures.py#L124) we are using helpers function to get the CephFS data pool name dynamically, here in factory fixtures we are not getting the CephFS name instead of data pool name through ceph_pool_factory name, so need to append '-data0' in the cephfs name

**Comment by vasukulkarni** [comment]
@sidhant-agrawal do you want to call the same function here as well helpers.get_cephfs_data_pool_name() for assignment?

**Comment by vasukulkarni** [comment]
good find!

**Comment by sidhant-agrawal** [comment]
@vasukulkarni 
`helpers.get_cephfs_data_pool_name()` seems more dynamic as it directly fetches name from the  Ceph.
For now, according to current convention appending '-data0' in the CephFS name also works.

**Comment by clacroix12** [comment]
I agree with Vasu, I think we should be consistent and use `helpers.get_cephfs_data_pool_name()`. This also makes it easier to fix if appending `-data0` stops working for some reason, we can change the function logic to apply it everywhere as opposed to fixing multiple places in the code.

**Comment by sidhant-agrawal** [comment]
Done.
Now using `interface_name = helpers.get_cephfs_data_pool_name()` for fetching CephFS data pool

**Pull request merged**
