### PR TITLE
Remove fixed version for DS deployment

### PR DESCRIPTION
**Pull request by petr-balogh**

### CODE REVIEW

**Comment by petr-balogh** [comment]
Verified here: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/1056/console

**Comment by nehaberry** [comment]
The install worked as seen in [[1]](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/1056/console) , hence approving.

**Comment by zmc** [comment]
Is there some background on why this was needed?

**Comment by petr-balogh** [comment]
> Is there some background on why this was needed?
@zmc sorry that I wasn't much talkative here this was discussed on Monday on our ocs-qe google hangout channel that even if the downstream operator build supposed to be fixed we were failing cause I forgot remove this from config when I tested the PR https://github.com/red-hat-storage/ocs-ci/pull/713 if it also work with specified image.

So was just quick fix on Monday morning to enable our jobs to run with really latest downstream build to verify the BZ with LVM issue was really fixed.

We don't want to have specific tag in our default config as if it's not specified it will take automatically the specific tag from latest tag.

We will specify it in our configuration only when triggering with UMB to make sure that we are running against built which sent UMB. But if someone would like to just run the latest DS build no need to specify any image.

**Pull request merged**
