### PR TITLE
exclude NOOBAA_PSQL_12_IMAGE for image verification after upgrade

### PR DESCRIPTION
**Pull request by vavuthu**
Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Comment by vavuthu** [comment]
verified upgrade from 4.14 to ocs-registry:4.15.8-2  : https://url.corp.redhat.com/69a5f04

```
2024-10-24 14:05:25  04:35:25 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod noobaa-operator-7b54864bf6-f426x -n openshift-storage -o yaml
2024-10-24 14:05:25  04:35:25 - MainThread - ocs_ci.ocs.ocp - INFO  - deleting noobaa_psql_12 image from current images for noobaa-operator-7b54864bf6-f426x
2024-10-24 14:05:25  04:35:25 - MainThread - ocs_ci.ocs.ocp - INFO  - All the images: {'noobaa_cor': 'registry.redhat.io/odf4/mcg-core-rhel9@sha256:d7850a19009aac05f8ebb48bac8fb1ba8f4f0c75189c15eb99d4ee2ae25c9206', 'noobaa_db': 'registry.redhat.io/rhel9/postgresql-15@sha256:92808c81661c3289ff027a06f6acd40b3937c43c3ba8e69b6d808b48e2e083ba', 'noobaa-operator': 'registry.redhat.io/odf4/mcg-rhel9-operator@sha256:8b2e0765760d0e4f896ab26d9b8dd5dc13926ccee4d338be0985428790a07ee6'} were successfully upgraded in: noobaa-operator-7b54864bf6-f426x!
```

**Review by petr-balogh — APPROVED** [review]

**Review by petr-balogh — APPROVED** [review]

**Review by shivamdurgbuns — APPROVED** [review]

**Pull request merged**
