### PR TITLE
Test add capacity pre upgrade

### PR DESCRIPTION
**Pull request by ebenahar**
Signed-off-by: Elad Ben Aharon <ebenahar@redhat.com>

### CODE REVIEW

**Comment by ebenahar** [comment]
From https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7140/console
Add capacity test passed here pre upgrade:

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacity::test_add_capacity 

18:53:43 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
PASSED                                                                   [ 50%]



The failure is on test_noobaa_postupgrade.

@fbalak could you please have a look?

**Comment by RazTamir** [comment]
@ebenahar with this PR, it means that all post upgrade tests will run on a cluster with more capacity.
Is this what we want?

**Comment by petr-balogh** [comment]
And we need to make sure that there won't be an issue if this test will run again in tier1 after upgrade.

**Comment by ebenahar** [comment]
> @ebenahar with this PR, it means that all post upgrade tests will run on a cluster with more capacity.
> Is this what we want?

Even if this is not what we explicitly intended with having add capacity tested pre-upgrade, I think that it is very likely that for customers, a cluster would be expanded at some point in its life and then be upgraded

**Comment by ebenahar** [comment]
@fbalak @petr-balogh please note that the above PR validation job was done with OCP upgrade

**Comment by fbalak** [comment]
> From https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/7140/console
> Add capacity test passed here pre upgrade:
> 
> tests/manage/z_cluster/cluster_expansion/test_add_capacity.py::TestAddCapacity::test_add_capacity
> 
> 18:53:43 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
> PASSED [ 50%]
> 
> The failure is on test_noobaa_postupgrade.
> 
> @fbalak could you please have a look?

This looks like an error in test. I will try to debug more and provide a fix. Issue for it: https://github.com/red-hat-storage/ocs-ci/issues/1956

**Pull request merged**
