### PR TITLE
[WIP] Fix MCG NSFS tests in disconnected deployments

### PR DESCRIPTION
**Pull request by sagihirshfeld**
Fixes: #7339

### CODE REVIEW

**Review by dahorak — APPROVED** [review]

**Review by tiffanyn108 — APPROVED** [review]
LGTM

**Comment by sagihirshfeld** [comment]
The PR validation job shows the original issue was fixed since the ubi8 container was created successfully:
```
2023-03-16 19:25:37  17:25:37 - MainThread - ocs_ci.ocs.resources.ocs - INFO  - Adding Deployment with name deployment-nsfs-interface-7789f789fd1841
...
...
2023-03-16 19:25:37  kind: Deployment
2023-03-16 19:25:37  metadata:
2023-03-16 19:25:37    name: deployment-nsfs-interface-7789f789fd1841
...
...
2023-03-16 19:25:37      spec:
2023-03-16 19:25:37        containers:
2023-03-16 19:25:37        - command:
2023-03-16 19:25:37          - /bin/sh
2023-03-16 19:25:37          image: ec2-18-116-13-187.us-east-2.compute.amazonaws.com:5000/ubi8/ubi:8.5-214
2023-03-16 19:25:37          imagePullPolicy: IfNotPresent
2023-03-16 19:25:37          name: ubi8
...
...
2023-03-16 19:25:37  17:25:37 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage create -f /tmp/Deployment1pdt9s_x -o yaml
...
...
2023-03-16 19:26:00  17:26:00 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc -n openshift-storage get Pod deployment-nsfs-interface-7789f789fd1841-84c87fc5bd-b9qb5 -n openshift-storage
2023-03-16 19:26:00  17:26:00 - MainThread - ocs_ci.ocs.resources.pod - INFO  - All the pods reached status running!
```
However, the tests still failed because of #7339. I suggest merging this PR and solving that issue separately @keesturam

**Comment by sagihirshfeld** [comment]
I separated the first part of the fix regarding ubi8 to #7707

**Comment by sagihirshfeld** [comment]
https://url.corp.redhat.com/68c285b shows that https://github.com/red-hat-storage/ocs-ci/pull/7707 was enough to fix NSFS in d/c deployments.

**Pull request closed without merging**
