### PR TITLE
Relocate remaining ecosystem tests to the functional test directory

### PR DESCRIPTION
**Pull request by clacroix12**

### CODE REVIEW

**Comment by clacroix12** [comment]
Basically a drag and drop relocation of the ecosystem tests, as well as some upgrade tests owned by other squads.

The only real "change" is the addition of the `__init__.py` in the new `upgrade` directory to get pytest to recognize it as an actual package.

`pytest --collect-only -m purple_squad` output:

```
<Package upgrade>
  <Module test_upgrade_ocp.py>
    <Class TestUpgradeOCP>
        <Function test_upgrade_ocp>
  <Module test_upgrade.py>
    <Function test_upgrade>
<Package deployment>
  <Module test_acm.py>
    <Function test_acm_import>
  <Module test_deployment.py>
    <Function test_deployment>
<Package upgrade>
  <Module test_upgrade.py>
    <Function test_worker_node_abrupt_shutdown>
    <Function test_worker_node_permanent_shutdown>
    <Function test_osd_reboot>
```
All of these tests are now under the `functional` test directory.

**Review by petr-balogh — APPROVED** [review]

**Comment by petr-balogh** [comment]
Thought of running all upgrade tests not just OCS upgrade. 
Scheduled here:
https://url.corp.redhat.com/041571c

**Review by OdedViner — DISMISSED** [review]

**Review by dahorak — APPROVED** [review]

**Review by vavuthu — APPROVED** [review]

**Comment by petr-balogh** [comment]
Please rebase and re-trigger test execution, I see latest failed on deployment of OCP @clacroix12

**Comment by petr-balogh** [comment]
@clacroix12 please have you check the failures if there is no one related to this change?

Also the upgrade to 4.15 should be unblocked from yesterday, so you can go ahead and schedule also upgrade job with all pre/post upgrade tests again.

**Comment by petr-balogh** [comment]
Actually I went ahead and re-scheduled upgrade run verification

**Review by petr-balogh — DISMISSED** [review]

**Review by OdedViner — APPROVED** [review]

**Comment by clacroix12** [comment]
@petr-balogh I took a look at the test results and the upgrade failed due to a noobaa issue. This was 4.14 -> 4.15 upgrade. Do we know if this upgrade working currently on master? If not we may want to try another upgrade scenario to test this PR.

**Review by vavuthu — APPROVED** [review]

**Review by petr-balogh — APPROVED** [review]

**Review by vavuthu — APPROVED** [review]

**Pull request merged**
