### PR TITLE
Fix deployment for IBM Cloud ROKS deployment with enabling Noobaa

### PR DESCRIPTION
**Pull request by petr-balogh**
Related bz:
https://bugzilla.redhat.com/show_bug.cgi?id=2258638

### CODE REVIEW

**Review by vavuthu — APPROVED** [review]

**Review by vavuthu — APPROVED** [review]

**Review by dahorak — APPROVED** [review]

**Comment by petr-balogh** [comment]
Verification job scheduled here:
https://url.corp.redhat.com/58447db

**Comment by petr-balogh** [comment]
Job failed on storage cluster version mismatch with CSV version which is the different issue caused because new check and that I ma running on master branch on 4.13. But I see noobaa is now deployed ok:

```console
pod/must-gather-t72mq-helper                                          1/1     Running     0          71s     172.22.22.40     10.243.128.153   <none>           <none>
pod/noobaa-core-0                                                     1/1     Running     0          3m59s   172.22.25.118    10.243.128.152   <none>           <none>
pod/noobaa-db-pg-0                                                    1/1     Running     0          3m59s   172.22.25.120    10.243.128.152   <none>           <none>
pod/noobaa-endpoint-5b64f4dd9-vjdpc                                   1/1     Running     0          3m11s   172.22.25.121    10.243.128.152   <none>           <none>
pod/noobaa-operator-7cd7596bf7-qbjl6                                  1/1     Running     0          10m     172.22.25.105    10.243.128.152   <none>           <none>
pod/ocs-metrics-exporter-5d6b88bff7-tr6vj                             1/1     Running     0          10m     172.22.22.23     10.243.128.153   <none>           <none>
```

And in storageCluster CR I see:

```yaml
    multiCloudGateway:
      reconcileStrategy: manage
```

**Pull request merged**
