### PR TITLE
Directory changes for performance io and csi tests

### PR DESCRIPTION
**Pull request by pintojoy**
Moving csi and io tests to "performance/csi_tests" and "performance/io_workload" directories
Signed-off-by: pintojoy <jopinto@redhat.com>

### CODE REVIEW

**Comment by Avilir** [comment]
you need to rebase this PR

**Review by keesturam — DISMISSED** [review]
LGTM

**Comment by keesturam** [comment]
@pintojoy is there any reason on why PR job validation is still not done?

**Review by Avilir — DISMISSED** [review]
LGTM

**Review by ramkiperiy — APPROVED** [review]
LGTM

**Comment by pintojoy** [comment]
> @pintojoy is there any reason on why PR job validation is still not done?

PR validation job is running as part of https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1776.  For some reason its not showing in this page

**Review by keesturam — APPROVED** [review]
LGTM

**Comment by keesturam** [comment]
Looks like Jenkins job fails as the underlying tests fail, but our intention of job validation for this PR is to see if all the tests are triggered after moving them into directories. This is working. Test failures needs to be addressed separately. so, merging this PR.

**Pull request merged**
