### PR TITLE
Openstack IPI platform configuration

### PR DESCRIPTION
**Pull request by brainfunked**

### CODE REVIEW

**Comment by sabose** [comment]
@ebenahar can someone review to make sure we can run Tier1 on OSP with this PR?

**Comment by renan-campos** [comment]
I'm taking over this PR for @brainfunked, so if there are any changes required before merging let me know and I can make a new PR with those changes.

**Comment by renan-campos** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/3489

**Comment by petr-balogh** [comment]
Closing this as this should be covered in new PR here:
https://github.com/red-hat-storage/ocs-ci/pull/3489

**Pull request closed without merging**
