### PR TITLE
fix mon count for upgrade in arbiter deployments

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #9370 

Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Review by petr-balogh — APPROVED** [review]

**Comment by petr-balogh** [comment]
Looks like will require more fixes:
```
ocs_ci/ocs/ocs_upgrade.py:721: in run_ocs_upgrade
    verify_image_versions(
ocs_ci/ocs/ocs_upgrade.py:190: in verify_image_versions
    verify_pods_upgraded(
ocs_ci/ocs/resources/pod.py:2174: in verify_pods_upgraded
    check_timeout_reached(start_time, timeout, info_message)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

start_time = 1709144749.3543267, timeout = 820
err_msg = 'Waiting for 3 pods with selector: app=rook-ceph-mon to be running and upgraded.'

    def check_timeout_reached(start_time, timeout, err_msg=None):
        """
        Check if timeout reached and if so raise the exception.
    
        Args:
            start_time (time): Star time of the operation.
            timeout (int): Timeout in seconds.
            err_msg (str): Error message for the exception.
    
        Raises:
            TimeoutException: In case the timeout reached.
    
        """
        msg = f"Timeout {timeout} reached!"
        if err_msg:
            msg += f" Error: {err_msg}"
    
        if timeout < (time.time() - start_time):
>           raise TimeoutException(msg)
E           ocs_ci.ocs.exceptions.TimeoutException: Timeout 820 reached! Error: Waiting for 3 pods with selector: app=rook-ceph-mon to be running and upgraded.

ocs_ci/utility/utils.py:2907: TimeoutException

```

Specifically here:

https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/ocs_upgrade.py#L190

We need to dynamically change here to 5 as well in case of arbiter deployment.

**Comment by vavuthu** [comment]
> Looks like will require more fixes:
> 
> ```
> ocs_ci/ocs/ocs_upgrade.py:721: in run_ocs_upgrade
>     verify_image_versions(
> ocs_ci/ocs/ocs_upgrade.py:190: in verify_image_versions
>     verify_pods_upgraded(
> ocs_ci/ocs/resources/pod.py:2174: in verify_pods_upgraded
>     check_timeout_reached(start_time, timeout, info_message)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> start_time = 1709144749.3543267, timeout = 820
> err_msg = 'Waiting for 3 pods with selector: app=rook-ceph-mon to be running and upgraded.'
> 
>     def check_timeout_reached(start_time, timeout, err_msg=None):
>         """
>         Check if timeout reached and if so raise the exception.
>     
>         Args:
>             start_time (time): Star time of the operation.
>             timeout (int): Timeout in seconds.
>             err_msg (str): Error message for the exception.
>     
>         Raises:
>             TimeoutException: In case the timeout reached.
>     
>         """
>         msg = f"Timeout {timeout} reached!"
>         if err_msg:
>             msg += f" Error: {err_msg}"
>     
>         if timeout < (time.time() - start_time):
> >           raise TimeoutException(msg)
> E           ocs_ci.ocs.exceptions.TimeoutException: Timeout 820 reached! Error: Waiting for 3 pods with selector: app=rook-ceph-mon to be running and upgraded.
> 
> ocs_ci/utility/utils.py:2907: TimeoutException
> ```
> 
> Specifically here:
> 
> https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/ocs_upgrade.py#L190
> 
> We need to dynamically change here to 5 as well in case of arbiter deployment.

Its already there , reason why its failed there is extra (:) in getting arbiter deployment, so it didn't update the mon count accordingly. pushed another commit ( removing extra colun)

**Review by petr-balogh — DISMISSED** [review]

**Review by dahorak — APPROVED** [review]

**Comment by vavuthu** [comment]
verification job: https://url.corp.redhat.com/1b8ff7d

**Comment by vavuthu** [comment]
verification job: https://url.corp.redhat.com/de79c6e

**Comment by vavuthu** [comment]
> verification job: https://url.corp.redhat.com/de79c6e

upgrade test passed successfully

```
2024-03-04 19:23:35  13:53:35 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO  - Noobaa root secrets are not public
2024-03-04 19:23:35  ------------------------------ live log logreport ------------------------------
2024-03-04 19:23:35  13:53:35 - MainThread - ocs_ci.framework.pytest_customization.reports - INFO  - duration reported by tests/functional/upgrade/test_upgrade.py::test_upgrade immediately after test execution: 881.42
2024-03-04 19:23:35  PASSED
2024-03-04 19:23:35  ------------------------------ live log teardown -------------------------------
```
BUILD ID: 4.15.0-150 RUN ID: 1709559473

```

Result | Test | Description | Duration | Links
-- | -- | -- | -- | --
Passed | tests/functional/upgrade/test_upgrade.py::test_upgrade | Tests upgrade procedure of OCS cluster | 2411.40 | Log File

Results
Result 	Test 	Description 	Duration 	Links
Passed 	tests/functional/upgrade/test_upgrade.py::test_upgrade 	Tests upgrade procedure of OCS cluster 	2411.40 	[Log File](http://dev/null)
```

**Review by dahorak — APPROVED** [review]

**Review by Akarsha-rai — APPROVED** [review]

**Pull request merged**
