### PR TITLE
Python version bump

### PR DESCRIPTION
**Pull request by clacroix12**
Closes: #5997
Partially completes: #6158

### CODE REVIEW

**Review by zmc — APPROVED** [review]
This looks good and complete to me but I have _not_ tested it

**Review by vavuthu — APPROVED** [review]

**Review by shivamdurgbuns — APPROVED** [review]
LGTM

**Review by Avilir — APPROVED** [review]
LGTM

**Review by AviadP — APPROVED** [review]

**Review by petr-balogh — APPROVED** [review]

**Comment by clacroix12** [comment]
> PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: deployment PR Test Path: tests/ Additional Test Params: OCP VERSION: 4.11 OCS VERSION: 4.11 tested against branch: master
> 
> [Job FAILED](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/3133//testReport) (installation failed, tests not executed).

The deployment was actually successful, destroy failed on the first two attempts but third attempt was successful so it reported 'unstable' status.

**Comment by clacroix12** [comment]
@AviadP were there any particular tests you wanted run to ensure the scipy package is working as intended?

If so I can run those to ensure this is verified, otherwise I think we are good to disable the 3.7 pr check requirement on the repo and merge. @petr-balogh FYI

**Comment by AviadP** [comment]
> @AviadP were there any particular tests you wanted run to ensure the scipy package is working as intended?
> 
> If so I can run those to ensure this is verified, otherwise I think we are good to disable the 3.7 pr check requirement on the repo and merge. @petr-balogh FYI

There aren't any test, it failed me during setting up the env

**Pull request merged**
