### PR TITLE
Add the param 'allowVolumeExpansion: true' to allow resize OSD with GCP

### PR DESCRIPTION
**Pull request by yitzhak12**
See more details in the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2318494.

### CODE REVIEW

**Review by parth-gr — APPROVED** [review]
lgtm

**Review by petr-balogh — APPROVED** [review]

**Review by dahorak — APPROVED** [review]

**Comment by yitzhak12** [comment]
The deployment passed using the PR above: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/43609/. Also, I ran the OSD resize test twice, and it finished successfully.

**Pull request merged**
