### PR TITLE
Fix locators changed with patternfly 5

### PR DESCRIPTION
**Pull request by ebondare**

### CODE REVIEW

**Review by petr-balogh — DISMISSED** [review]

**Comment by DanielOsypenko** [comment]
what is this for? can you pls share what element it is? or screenshot of the element

.pf-v5-c-icon - is an css locator for the class, that means any new icon will make this locator non-unique. 
Can you pls specify this icon giving more presided loc please?

**Comment by ebondare** [comment]
> what is this for? can you pls share what element it is? or screenshot of the element
> 
> .pf-v5-c-icon - is an css locator for the class, that means any new icon will make this locator non-unique. Can you pls specify this icon giving more presided loc please?

The original locator was "input_value_validator_icon": (".pf-c-icon", By.CSS_SELECTOR), so it's basically the same as before, only for patternfly 5. I'll attach the screenshot.

**Comment by ebondare** [comment]
2024-04-02_check_icon
It's the icon for input value validation. It's the only one on the page

**Comment by DanielOsypenko** [comment]
> > what is this for? can you pls share what element it is? or screenshot of the element
> > .pf-v5-c-icon - is an css locator for the class, that means any new icon will make this locator non-unique. Can you pls specify this icon giving more presided loc please?
> 
> The original locator was "input_value_validator_icon": (".pf-c-icon", By.CSS_SELECTOR), so it's basically the same as before, only for patternfly 5. I'll attach the screenshot.

can you please add new locator to existing one one by comma, it was discussed on Black squad meeting. Similarly to 
  ```
  "show-default-projects": (
        ".pf-c-switch__toggle, .pf-v5-c-switch__toggle",
        By.CSS_SELECTOR,
    ),
```
 This really helps to stop producing new dicts and overall structure at views.py, additionally it will work also on release-4.14 and may be cherry-picked if needed. 

This is applicable to all Patternfly5 new locators

**Comment by petr-balogh** [comment]
please rebase on latest master when wi did pin the ping3 which is failing your tox now.

**Comment by ebondare** [comment]
TestErrorMessageImprovements tests passed: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/35907/

**Comment by ebondare** [comment]
> > > what is this for? can you pls share what element it is? or screenshot of the element
> > > .pf-v5-c-icon - is an css locator for the class, that means any new icon will make this locator non-unique. Can you pls specify this icon giving more presided loc please?
> > 
> > 
> > The original locator was "input_value_validator_icon": (".pf-c-icon", By.CSS_SELECTOR), so it's basically the same as before, only for patternfly 5. I'll attach the screenshot.
> 
> can you please add new locator to existing one one by comma, it was discussed on Black squad meeting. Similarly to
> 
> ```
> "show-default-projects": (
>       ".pf-c-switch__toggle, .pf-v5-c-switch__toggle",
>       By.CSS_SELECTOR,
>   ),
> ```
> 
> This really helps to stop producing new dicts and overall structure at views.py, additionally it will work also on release-4.14 and may be cherry-picked if needed.
> 
> This is applicable to all Patternfly5 new locators

Fixed

**Comment by ebondare** [comment]
> please rebase on latest master when wi did pin the ping3 which is failing your tox now.

Done

**Comment by ebondare** [comment]
Fixes https://github.com/red-hat-storage/ocs-ci/issues/9027

**Review by DanielOsypenko — APPROVED** [review]

**Review by am-agrawa — APPROVED** [review]

**Comment by ebondare** [comment]
Successful test run with the latest changes: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/35920/consoleFull

**Review by petr-balogh — APPROVED** [review]

**Pull request merged**
