### PR TITLE
Supporting multus deployment

### PR DESCRIPTION
**Pull request by vavuthu**
Signed-off-by: vavuthu <vavuthu@redhat.com>

### CODE REVIEW

**Comment by clacroix12** [comment]
I think we also want a config file to enable this in the config:

```yaml
ENV_DATA:
  is_multus_enabled: true
```

**Review by ebenahar — DISMISSED** [review]

**Comment by ebenahar** [comment]
Hi @vavuthu would this work over vSphere?

**Comment by vavuthu** [comment]
> Hi @vavuthu would this work over vSphere?

currently only on 1 DC. I am planning to enable on other DC's as well. I will team let team know once everything is done

**Comment by vavuthu** [comment]
> I think we also want a config file to enable this in the config:
> 
> ```yaml
> ENV_DATA:
>   is_multus_enabled: true
> ```

Added enable_multus.yaml

**Review by ebenahar — APPROVED** [review]

**Comment by vavuthu** [comment]
> PR validation
> 
> Cluster Name:
> Cluster Configuration: conf/ocsci/enable_multus.yaml
> PR Test Suite: deployment
> PR Test Path: tests/
> Additional Test Params:
> OCP VERSION: 4.8
> OCS VERSION: 4.8
> 
> [Job FAILED](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1024//testReport) (installation failed, tests not executed).

job failed due bug https://bugzilla.redhat.com/show_bug.cgi?id=1978722

hence marked as verified

**Review by clacroix12 — APPROVED** [review]

**Pull request merged**
