### PR TITLE
skipping of logging on ocp 4.8

### PR DESCRIPTION
**Pull request by Shrivaibavi**
Signed-off-by: Shrivaibavi Raghaventhiran <sraghave@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
OCP 4.7 is not GAed yet, so don't we have still that issue on OCP 4.7? @Shrivaibavi

**Comment by PrasadDesala** [comment]
@Shrivaibavi  OCP 4.7 is now GAed, please continue with this PR

**Review by PrasadDesala — DISMISSED** [review]

**Comment by clacroix12** [comment]
@PrasadDesala @Shrivaibavi won't this have to be skipped for 4.8 now?

**Comment by PrasadDesala** [comment]
> @PrasadDesala @Shrivaibavi won't this have to be skipped for 4.8 now (and any future versions)?

Yes, we should skip for 4.8 now. May be we can use the same PR with a change in title

**Comment by Shrivaibavi** [comment]
> @PrasadDesala @Shrivaibavi won't this have to be skipped for 4.8 now (and any future versions)?

Done

**Review by PrasadDesala — APPROVED** [review]

**Review by clacroix12 — APPROVED** [review]

**Comment by Shrivaibavi** [comment]
From OCP 4.7 logging has become standalone product and we dont have to skip for next next versions

Just mentioning "stable" as channel can help pull right images for logging >=4.7 but for 4.7< versions we need to provide right channels

hence closing this PR and will open a new PR for the above mentioned changes.

**Pull request closed without merging**
