### PR TITLE
fix osd tree verification for baremetalpsi platform

### PR DESCRIPTION
**Pull request by shylesh**
Signed-off-by: Shylesh Kumar Mohan <shmohan@redhat.com>

### CODE REVIEW

**Comment by clacroix12** [comment]
@shylesh has this been verified / does this need verification?

**Review by clacroix12 — DISMISSED** [review]

**Comment by shylesh** [comment]
> @shylesh has this been verified / does this need verification?

flexybaremetal from ocs-ci is currently not working because of RHCOS image issue, so I am taking help from Vimal (from interop qe) to verify this PR. I will update once I have the result.

**Review by vasukulkarni — DISMISSED** [review]

**Review by vavuthu — DISMISSED** [review]

**Review by petr-balogh — DISMISSED** [review]

**Comment by shylesh** [comment]
Verified from Vimal's job:- https://interop-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ocs-4.5-openshift-4-vipatel/10/




16:35:14 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO - Verifying OSDs are distributed evenly across worker nodes
16:35:14 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Pod  -n openshift-storage --selector=app=rook-ceph-osd -o yaml
16:35:14 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get storagecluster  -n openshift-storage -o yaml
16:35:14 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO - Verifying CSI driver object contains provisioner names.
16:35:14 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get CSIDriver  -o yaml
16:35:15 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO - Verifying node and provisioner secret names in storage class.
16:35:15 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get StorageClass ocs-storagecluster-ceph-rbd -n openshift-storage -o yaml
16:35:16 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get StorageClass ocs-storagecluster-cephfs -n openshift-storage -o yaml
16:35:16 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO - Verified node and provisioner secret names in storage class.
16:35:16 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO - Verifying ceph osd tree output and checking for device set PVC names in the output.
16:35:16 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get node  -o yaml
16:35:17 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-master-0
16:35:18 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node  -o yaml
16:35:19 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-master-1
16:35:19 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node  -o yaml
16:35:20 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-master-2
16:35:20 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node  -o yaml
16:35:21 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-worker-gtbf8
16:35:21 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node  -o yaml
16:35:22 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-worker-j777r
16:35:22 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node  -o yaml
16:35:23 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-worker-qlpn8
16:35:23 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node  -o yaml
16:35:25 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-worker-gtbf8 -o yaml
16:35:26 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-worker-j777r -o yaml
16:35:26 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Node vipatel-gyosf-chnv7-worker-qlpn8 -o yaml
16:35:27 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Pod  -n openshift-storage --selector=app=rook-ceph-tools -o yaml
16:35:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Pod rook-ceph-tools-7fcff79f44-b6mz4 -n openshift-storage
16:35:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig get Pod  -n openshift-storage -o yaml
16:35:34 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/cloud-user/vipatel-gyosf_install/auth/kubeconfig rsh rook-ceph-tools-7fcff79f44-b6mz4 ceph osd tree --format json
16:35:35 - MainThread - ocs_ci.ocs.resources.storage_cluster - INFO - Verified ceph osd tree output. Device set PVC names are given in the output.

**Review by vasukulkarni — APPROVED** [review]

**Review by clacroix12 — APPROVED** [review]
LGTM

**Pull request merged**
