### PR TITLE
Change of noobaa operator CSV

### PR DESCRIPTION
**Pull request by petr-balogh**
Fixes: #5080

Signed-off-by: Petr Balogh <pbalogh@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
Running 3 validation jobs:
For new naming:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1800/
Old naming:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1802/
Upgrade:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1803/

**Comment by petr-balogh** [comment]
I missed .ci in ocs registry image :(

Running another round of verification jobs:
Running 3 validation jobs:
For new naming:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1805/
Old naming:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1806/
Upgrade:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1807

**Comment by petr-balogh** [comment]
Found out that after subscription we mentioned that we should sleep for 15 seconds but we actually didn't.
Increased this to 30 seconds to be sure there will appear the CSV from which we can read the version.

Running another round of verification jobs:
For new naming:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1811/
Old naming:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1812/
Upgrade:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1813/

**Comment by petr-balogh** [comment]
re-triggering once more for old build here after increasing wait time after subscription to 90 seconds as we see 30 seconds is not enough to see ODF csv.
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1823/

Upgrade here:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/1824/

**Review by vavuthu — APPROVED** [review]

**Comment by petr-balogh** [comment]
I see that on older build it tried to verify noobaa-operator:
```
2021-11-11 11:28:43  10:28:43 - MainThread - ocs_ci.ocs.ocp - INFO - Resource noobaa-operator.v4.9.0 is in phase: Succeeded!
```

On newer build :
```
2021-11-11 00:28:04  23:28:04 - MainThread - ocs_ci.ocs.ocp - INFO - Resource mcg-operator.v4.9.0 is in phase: Succeeded!
```

So marking as verified.

**Review by dahorak — APPROVED** [review]

**Pull request merged**
