### PR TITLE
Require kubernetes 10.0.1 to satisfy latest openshift package requirement

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #1644

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by clacroix12** [comment]
Current fix is to hard code the version that's required by `openshift` however I'm now wondering why we specify the `kubernetes` package in our requirements at all. If it's a dependency of `openshift`, why don't we omit it from our requirements and have whatever version is supported by `openshift` get installed automatically? @petr-balogh @RazTamir @ebenahar Is there a good reason why we have `kubernetes` specified in our requirements or can we simply remove it?

**Comment by RazTamir** [comment]
Hi @Coady, if I remember correctly, we added this dependency in the early days of ocs where we explored the python-rest-client instead of OCP class.
I guess it is not needed anymore

**Comment by clacroix12** [comment]
@RazTamir alright I figured it was leftover from the earlier stages of development. I think removing it is the better call, as we can ensure that we won't have a disconnect like this since we'll just pull whatever `openshift` needs. 

Unrelated, I noticed the unit tests are failing for some reason. It looks like previous PRs didn't hit this issue so I'm not really sure what the cause of it is yet but I'm in the process of investigating.

**Comment by clacroix12** [comment]
Unit tests were broken because of a new pytest version. I have a workaround for it here: https://github.com/red-hat-storage/ocs-ci/pull/1647

Once the fix for the unit tests is merged I will update this PR and instead remove the `kubernetes` package from our requirements.

**Comment by vasukulkarni** [comment]
pod exec still uses kubernetes so you will have to run those tests as well, have you looked into fixing unit test with latest pytest, the CI errors actually looks bit misleading to me.

**Comment by clacroix12** [comment]
> pod exec still uses kubernetes so you will have to run those tests as well

we still get the `kubernetes` package if we remove it from our requirements because it's a dependency of `openshift`. However, if we delegate the version to whatever `openshift` supports we ensure that we don't hit this issue anymore.

> have you looked into fixing unit test with latest pytest, the CI errors actually looks bit misleading to me.

I wanted to get a workaround in first so things weren't entirely broken while we were looking into the fix.

**Comment by clacroix12** [comment]
@vasukulkarni for now I'm going to leave it in but hardcode the version to get around the dependency error. If we want to remove it to delegate the version to whatever `openshift` needs we can do it in another PR.

**Comment by vavuthu** [comment]
@clacroix12 this issue breaks all our jobs. have u run deployment checks local ?

**Comment by clacroix12** [comment]
@vavuthu I haven't run a deployment but I have created a new venv and installed our requirements successfully which is what is failing in our jobs.

**Comment by vavuthu** [comment]
I have kickstarted the destroy job with this job and it passed the stage where its failed before

Job link:  https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/3985/console

**Pull request merged**
