### PR TITLE
Fix stretchcluster_required mark

### PR DESCRIPTION
**Pull request by petr-balogh**

### CODE REVIEW

**Review by mashetty330 — APPROVED** [review]

**Comment by petr-balogh** [comment]
verified locally with collect only:

```
collected 1358 items / 1229 deselected / 129 selected

<Package sc_arbiter>
  <Module test_mon_osd_failures.py>
    <Class TestMonAndOSDFailures>
        <Function test_single_mon_failures>
        <Function test_both_mon_failure>
        <Function test_single_osd_failure>
  <Module test_netsplit.py>
    <Class TestNetSplit>
        <Function test_netsplit[Data-1-Data-2]>
        <Function test_netsplit[Arbiter-Data-1]>
        <Function test_netsplit[Arbiter-Data-1-and-Arbiter-Data-2]>
        <Function test_netsplit[Arbiter-Data-1-and-Data-1-Data-2]>
  <Module test_noobaa_in_stretch.py>
    <Function test_nb_endpoint_topology_spread_constraints>
  <Module test_rgw_in_stretch.py>
    <Function test_rgw_svc_annotations>
  <Module test_zone_shutdown_and_crash.py>
    <Class TestZoneShutdownsAndCrashes>
        <Function test_zone_shutdowns[Normal-Shutdown]>
        <Function test_zone_shutdowns[Immediate-Shutdown]>
        <Function test_zone_crashes[1-5]>
  <Module test_add_capacity.py>
    <Class TestAddCapacityStretchCluster>
        <Function test_cluster_expansion[3]>
        
```

**Review by dahorak — APPROVED** [review]

**Pull request merged**
