### PR TITLE
Remove kubernetes package from requirements 

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #1702 

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by clacroix12** [comment]
@vasukulkarni I have a deployment test running right now. Did you want me to run any tier tests or should deployment be good enough?

**Comment by vasukulkarni** [comment]
> @vasukulkarni I have a deployment test running right now. Did you want me to run any tier tests or should deployment be good enough?

It would be nice to run tier1 too. Thanks

**Comment by clacroix12** [comment]
> PR validation [Job PASSED](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/1330//testReport).

This was a deployment verification. I've kicked off a tier1 test as well

**Comment by clacroix12** [comment]
@vasukulkarni all tests passed besides these two:
```
tests.manage.mcg.test_multi_region.TestMultiRegion.test_multiregion_bucket_creation
tests.manage.z_cluster.test_must_gather.TestMustGather.test_must_gather
 ```

I think we are safe to merge this. It doesn't look like these errors are due to the kubernetes version being pulled by openshift but if that is the case we can open an issue for them.

**Pull request merged**
