### PR TITLE
Fix storageclass creation for cephfs

### PR DESCRIPTION
**Pull request by prsurve**
Fix for issue #231

### CODE REVIEW

**Comment by nehaberry** [comment]
@prsurve LGTM.  Though I would need to test it to be sure that no other issue is seen.

Thanks for working on this.

**Comment by prsurve** [comment]
----------------RBD_Storageclass----------------
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-test-1419342940
  namespace: openshift-storage
parameters:
  adminid: admin
  csi.storage.k8s.io/node-publish-secret-name: secret-test-1419335617
  csi.storage.k8s.io/node-publish-secret-namespace: openshift-storage
  csi.storage.k8s.io/provisioner-secret-name: secret-test-1419335617
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  imageFeatures: layering
  imageFormat: '2'
  monitors: rook-ceph-mon-a.openshift-storage.svc.cluster.local:6789,rook-ceph-mon-b.openshift-storage.svc.cluster.local:6789,rook-ceph-mon-c.openshift-storage.svc.cluster.local:6789
  pool: cbp-test-1419341584
provisioner: rbd.csi.ceph.com
reclaimPolicy: Delete

----------------CEPHFS_Storageclass----------------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-test-1419355229
  namespace: openshift-storage
parameters:
  csi.storage.k8s.io/node-stage-secret-name: secret-test-1419341086
  csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
  csi.storage.k8s.io/provisioner-secret-name: secret-test-1419341086
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  monitors: rook-ceph-mon-a.openshift-storage.svc.cluster.local:6789,rook-ceph-mon-b.openshift-storage.svc.cluster.local:6789,rook-ceph-mon-c.openshift-storage.svc.cluster.local:6789
  pool: cephfs-test-1419282530-data0
  provisionVolume: 'true'
provisioner: cephfs.csi.ceph.com
reclaimPolicy: Delete

**Comment by prsurve** [comment]
@nehaberry thanks for verifying it asap

**Comment by shreekarSS** [comment]
LGTM @prsurve

**Pull request merged**
