### PR TITLE
Update Azure machineset yaml and libraries for scale tests

### PR DESCRIPTION
**Pull request by ramkiperiy**
Update Azure machineset yaml and libraries for scale tests

Signed-off-by: Ramakrishnan <rperiyas@redhat.com>

### CODE REVIEW

**Comment by ramkiperiy** [comment]
this PR fixes issue https://github.com/red-hat-storage/ocs-ci/issues/6815

**Review by pintojoy — DISMISSED** [review]
LGTM

**Review by ypersky1980 — DISMISSED** [review]
LGTM.

**Comment by ramkiperiy** [comment]
> PR validation on existing cluster
> 
> Cluster Name: rperiyas-az15 Cluster Configuration: PR Test Suite: scale PR Test Path: tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py Additional Test Params: OCP VERSION: 4.13 OCS VERSION: 4.13 tested against branch: master
> 
> [Job UNSTABLE](https://url.corp.redhat.com/b13f414) (some or all tests failed).

4 Test case passed  and 2 failed for Reboot issue with worker and master node. the fix is to add machineset and to create additional nodes which worked, so adding Verified Label.

**Review by pintojoy — APPROVED** [review]
LGTM

**Review by tiffanyn108 — APPROVED** [review]
LGTM.

**Review by keesturam — APPROVED** [review]

**Pull request merged**
