### PR TITLE
Disconnected deployment fixes/enhancements

### PR DESCRIPTION
**Pull request by dahorak**
Fixes:
* https://github.com/red-hat-storage/ocs-ci/issues/9377
* https://github.com/red-hat-storage/ocs-ci/issues/9379

### CODE REVIEW

**Comment by dahorak** [comment]
Triggered verification job here: https://url.corp.redhat.com/4f1bac6

**Review by vavuthu — DISMISSED** [review]

**Comment by dahorak** [comment]
The verification job failed during OCP deployment via Flexy (the same case as described in https://github.com/red-hat-storage/ocs-ci/issues/9377) - but the error message is more descriptive:
```
2024-02-29 17:26:22  E           ocs_ci.ocs.exceptions.ConfigurationError: DEPLOYMENT["mirror_registry"] parameter not configured!
2024-02-29 17:26:22  E           This might be caused by previous failure in OCP deployment or wrong configuration.
```

I'll try to trigger another verification job and will hope, that the OCP deployment will pass, but Flexy is not maintained anymore and there is no chance to get it enhanced/updated/fixed to avoid this kind of issues.

**Review by vavuthu — APPROVED** [review]

**Comment by dahorak** [comment]
> I'll try to trigger [another verification job](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-aws-upi-disconnected-3az-rhcos-3m-3w-acceptance/177/) and will hope, that the OCP deployment will pass, but Flexy is not maintained anymore and there is no chance to get it enhanced/updated/fixed to avoid this kind of issues.

This second job failed during another mirroring process (via `oc image mirror ...` command), so I've updated the timeout also for this part and re-triggered another verification job: https://url.corp.redhat.com/0da79d7 > PASSED

**Review by shivamdurgbuns — APPROVED** [review]

**Pull request merged**
