### PR TITLE
Skip test_rgw_host_node_failure for vsphere IPI platform

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #4346 

Signed-off-by: vavuthu <vavuthu@redhat.com>

### CODE REVIEW

**Review by Akarsha-rai — DISMISSED** [review]

**Review by Avilir — APPROVED** [review]

**Review by Akarsha-rai — APPROVED** [review]

**Review by Avilir — APPROVED** [review]

**Comment by prsurve** [comment]
Instead of skipping it we need to make library to support VMware IPI

**Comment by vavuthu** [comment]
> Instead of skipping it we need to make library to support VMware IPI

we would like to skip it until that happens. @red-hat-storage/red-squad

**Comment by prsurve** [comment]
> > Instead of skipping it we need to make library to support VMware IPI
> 
> we would like to skip it until that happens. @red-hat-storage/red-squad
Is there any plan to support or skip all the test

**Comment by vavuthu** [comment]
> > > Instead of skipping it we need to make library to support VMware IPI
> > 
> > 
> > we would like to skip it until that happens. @red-hat-storage/red-squad
> 
> Is there any plan to support or skip all the test

please raise the issue and assign to  @red-hat-storage/ocs-qe-ecosystem team. 

I see there are 2 options here

1. Skip the test for particular platform
2. lets fail the test for every run and lets analyze the same failure for every run till fix is available.

@prsurve Option 1 is more appropriate here WDYT

**Review by MeridianExplorer — APPROVED** [review]

**Review by parikshithb — APPROVED** [review]

**Pull request merged**
