### PR TITLE
Install DFC offering in FaaS

### PR DESCRIPTION
**Pull request by jilju**
Install DFC offering in Faas.
Added workaround to create StorageClassClaim CRD. This will be later removed when fixed in the build.

### CODE REVIEW

**Review by suchita-g — APPROVED** [review]

**Comment by jilju** [comment]
Verified : https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/23813/
(failure in post deployment checks are not related to the change in this pr)

**Comment by jilju** [comment]
Installation on provider is not part of this PR but it is verifed to ensure that nothing is breaking.
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/23805/

**Review by fbalak — APPROVED** [review]
lgtm, you can create an issue to track a removal of the workaround

**Comment by jilju** [comment]
> lgtm, you can create an issue to track a removal of the workaround

Created https://github.com/red-hat-storage/ocs-ci/issues/7561

**Review by suchita-g — APPROVED** [review]

**Pull request merged**
