### PR TITLE
Remove storageclass check for provider cluster

### PR DESCRIPTION
**Pull request by ebondare**
Signed-off-by: Elena Bondarenko <ebondare@redhat.com>

### CODE REVIEW

**Review by jilju — DISMISSED** [review]

**Review by fbalak — DISMISSED** [review]

**Review by fbalak — COMMENTED** [review]
Are there no storageclasses to check on provider?

**Comment by jilju** [comment]
@ebondare 
Used this PR for provider cluster installation. Deployment failed because the storage class validation is not disabled.
```
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage get StorageClass ocs-storagecluster-ceph-rbd -n openshift-storage -o yaml.
Error is Error from server (NotFound): storageclasses.storage.k8s.io "ocs-storagecluster-ceph-rbd" not found
```

https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/13032/

**Comment by ebondare** [comment]
> Are there no storageclasses to check on provider?

From what I know, there are no storageclasses we should check for.

**Comment by ebondare** [comment]
Thank you! I fixed the issue, this time cluster deployment was successful:
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/13048/

**Review by dahorak — APPROVED** [review]

**Review by fbalak — APPROVED** [review]

**Pull request merged**
