### PR TITLE
add stage certificate to the cluster

### PR DESCRIPTION
**Pull request by dahorak**
Add certificate for `registry.stage.redhat.io` to the OCP cluster.

Signed-off-by: Daniel Horak <dahorak@redhat.com>

### CODE REVIEW

**Comment by vavuthu** [comment]
@dahorak is stage cert will work even for normal deployment ( not from stage )

**Comment by petr-balogh** [comment]
> @dahorak is stage cert will work even for normal deployment ( not from stage )

@vavuthu problem is that current RC4 build. Normal internal build pointing to the stage as well. So we decided to just add this cert as default.  See the info in the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1784732

So I want to test this if this help us even deploy RC4 build in vmware regular way.

**Comment by petr-balogh** [comment]
Verification job on vmware running here: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/3181/console

**Comment by petr-balogh** [comment]
Running new one verification here:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/3186/console

**Comment by dahorak** [comment]
> @dahorak is stage cert will work even for normal deployment ( not from stage )

It just add additional certificate used for validation against `registry.stage.redhat.io` - so it doesn't affect installation from other sources.

**Comment by petr-balogh** [comment]
Verified here:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/3186/parameters/

**Pull request merged**
