### PR TITLE
Disable add node for IBM Flash system

### PR DESCRIPTION
**Pull request by petr-balogh**
Fix for IBM Flash system
Fixes: #5044

Signed-off-by: Petr Balogh <pbalogh@redhat.com>

### CODE REVIEW

**Review by clacroix12 — DISMISSED** [review]

**Review by clacroix12 — APPROVED** [review]

**Comment by yitzhak12** [comment]
Please see my comment in the issue https://github.com/red-hat-storage/ocs-ci/issues/5044. 
While disabling the "add node" test can be a temporary solution, the right solution is to add a new class in the platform_nodes file https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/platform_nodes.py for adding a node with IBM Flash.

**Review by shylesh — APPROVED** [review]
+1

**Comment by petr-balogh** [comment]
> Please see my comment in the issue #5044. While disabling the "add node" test can be a temporary solution, the right solution is to add a new class in the platform_nodes file https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/platform_nodes.py for adding a node with IBM Flash.

I replied in the issue. This is just temp W/A for the issue and agree it should be fixed.

**Review by prsurve — APPROVED** [review]

**Comment by yitzhak12** [comment]
Okay, np.

**Pull request merged**
