### PR TITLE
Update test_pvc_assign_pod_node.py

### PR DESCRIPTION
**Pull request by sidhant-agrawal**
Update test_pvc_assign_pod_node.py based on changes made in #630 
 - Use pod.verify_node_name for checking node
 - Remove parametrize from test_rwx_pvc_assign_pod_node()
 - Minor enhancements

Update pod.py
 - Improved logging message in verify_node_name

Signed-off-by: Sidhant Agrawal <sagrawal@redhat.com>

### CODE REVIEW

**Comment by sidhant-agrawal** [comment]
Verified on local cluster
in which Rook Cluster using PV backed OSDs and MONs was deployed manually
```
======================================================= short test summary info ========================================================
PASSED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephBlockPool]
PASSED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwo_pvc_assign_pod_node[CephFileSystem]
PASSED tests/manage/pv_services/test_pvc_assign_pod_node.py::TestPvcAssignPodNode::test_rwx_pvc_assign_pod_node
[test_pvc_assign_pod_node_28Aug.log](https://github.com/red-hat-storage/ocs-ci/files/3549676/test_pvc_assign_pod_node_28Aug.log)

```

**Comment by RazTamir** [comment]
@sidhant-agrawal @ebenahar before merging this,
Do we have that functionality implemented in our deployment?
Wondering what will happen if this is still in progress and those test will start failing because of that

**Comment by sidhant-agrawal** [comment]
> @sidhant-agrawal @ebenahar before merging this,
> Do we have that functionality implemented in our deployment?
@RazTamir No. 
For pv based cluster we have to follow the steps mentioned in the  doc [Creating a Rook Cluster using PV backed OSDs and MONs](https://docs.google.com/document/d/1awQ2oXkKK3BZ8SJqi69_lISkTtpJG8QPrJxF6veTUt8/edit?ts=5d64ed29#heading=h.q9p8ar9dq9yv) shared by @nehaberry  

Currently, we might hit [bz 1746055](https://bugzilla.redhat.com/show_bug.cgi?id=1746055) in PV based cluster when we try to create ~100s of PVC

**Comment by RazTamir** [comment]
Isn't it what the operator should do?
Or do we need to implement it in our deployment script?

**Comment by sidhant-agrawal** [comment]
> Isn't it what the operator should do?
> Or do we need to implement it in our deployment script?

Yes, correct.
Once OCS Operator is ready, it is expected that the OSDs and MONs will be automatically backed by PVCs.
For now to try a hands-on on manual deployment is needed.

**Comment by RazTamir** [comment]
Ok thanks @sidhant-agrawal .
Can we wait with this PR merge until https://github.com/red-hat-storage/ocs-ci/pull/640 will be merged?
In case not, could you please remove all @tierX markers for now so we will not execute this until we have the infrastructure supporting the tests?

**Comment by sidhant-agrawal** [comment]
@RazTamir  This test does not depends on PV based cluster or #640.
This test was already working in non PV based cluster, I just verified on PV based cluster because going forward we will be using that.

**Comment by RazTamir** [comment]
ahh :)
Great!

So it is ready for merge

**Pull request merged**
