### PR TITLE
Jenkins: Avoid using operator for downstream

### PR DESCRIPTION
**Pull request by zmc**

### CODE REVIEW

**Comment by RazTamir** [comment]
Why we want to avoid using operator for downstream?

**Comment by zmc** [comment]
@RazTamir According to @petr-balogh, it's not implemented yet.

**Comment by petr-balogh** [comment]
> @RazTamir According to @petr-balogh, it's not implemented yet.

That's true. Just submitted PR #713 . Consider as late night submitted PR, so maybe will need some polish on Monday.

**Comment by RazTamir** [comment]
Thanks.
LGTM

**Pull request merged**
