### PR TITLE
Ypersky clone perf lib adjustment

### PR DESCRIPTION
**Pull request by ypersky1980**
This PR handles and removes code duplication, so that multiple clone creation test ( test_pvc_multi_clone_performance.py)  will use functions implemented in the performance_lib.

### CODE REVIEW

**Comment by ypersky1980** [comment]
The test has successfully passed and the log file is available here: 

10.70.39.233://tmp/ypersky_pr/ypersky_44_test_pvc_multi_clone_1

**Review by keesturam — DISMISSED** [review]
LGTM.

**Review by Avilir — DISMISSED** [review]
LGTM

**Review by keesturam — APPROVED** [review]

**Review by ramkiperiy — APPROVED** [review]
LGTM

**Review by petr-balogh — APPROVED** [review]

**Pull request merged**
