### PR TITLE
Wait for node deletion and verify original node count during teardown of test_automated_recovery_from_stopped_node_and_start[True]

### LINKED ISSUE #8671: Wait for node deletion and verify original node count during teardown of test_automated_recovery_from_stopped_node_and_start[True]
The next test **test_automated_recovery_from_stopped_node_and_start[False]** failed as it did not find the 3rd worker node due to which Pods scheduled on that node were stuck in Pending state.

This happened because we are deleting the newly added node in the previous test **test_automated_recovery_from_stopped_node_and_start[True]** during teardown but do not wait for it's deletion and ensure that the original node count is maintained.
The check has to be implemented with proper timeout to avoid hitting such issues with other tests.

Jenkins- https://url.corp.redhat.com/fe93967

However, the failure seems intermittent as it passed with ODF  4.14.0-145.stable but it's a bit strange as we were anyways expecting at least 3 worker nodes to be available when the next test was run as the only extra node which was added in the previous test was bring deleted, and not more.

### PR DESCRIPTION
**Pull request by am-agrawa**
fixes #8671

### CODE REVIEW

**Comment by am-agrawa** [comment]
Both the parameterized test passed- https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/30680/console

**Review by ebenahar — APPROVED** [review]

**Review by pintojoy — APPROVED** [review]
LGTM

**Review by amr1ta — APPROVED** [review]

**Review by pintojoy — APPROVED** [review]
LGTM

**Pull request merged**
