### PR TITLE
Added ocs_must_gather_image to downstream config

### PR DESCRIPTION
**Pull request by clacroix12**
Signed-off-by: Coady LaCroix <clacroix@redhat.com>

https://projects.engineering.redhat.com/browse/OCSQE-59

### CODE REVIEW

**Comment by vasukulkarni** [comment]
Needs testing to confirm it works - we could run one failing test here.

**Comment by clacroix12** [comment]
Just noticed merge conflict with the downstream config, will rebase after verification job is done.

**Comment by clacroix12** [comment]
Failed due to known PG issue
```
E           ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN too few PGs per OSD (16 < min 30)
```

**Comment by vasukulkarni** [comment]
I think needs rebase, might be missing commit 250b6ec09be8dc62c6057e32d8b269ad23f27cf9 ?

**Comment by clacroix12** [comment]
@vasukulkarni Yeah, I just rebased and will be re-running the verification job

**Comment by petr-balogh** [comment]
Can we consider as verified @clacroix12  If so, please label wit verified and we can merge.

**Comment by clacroix12** [comment]
@petr-balogh yes, it seems like all of the test failures were already present and not regressions due to this change. I will fix labels so you can merge.

**Pull request merged**
