### PR TITLE
Remove elastic search usage from Scale tests

### PR DESCRIPTION
**Pull request by ramkiperiy**
Remove elastic search usage from Scale test tests/e2e/scale/test_scale_small_file_workload.py

Signed-off-by: Ramakrishnan <rperiyas@redhat.com>

### CODE REVIEW

**Review by Avilir — APPROVED** [review]
LGTM

**Review by keesturam — APPROVED** [review]
LGTM

**Comment by ramkiperiy** [comment]
image
Observed 100% pass in console

**Comment by ramkiperiy** [comment]
Failure is expected, its from teardown when there is a check for data leak, @wusui looks like it's failure we should report bz but anyway would request you to execute this test in AWS platform for confirmation

`tests/e2e/scale/test_scale_small_file_workload.py::TestSmallFileWorkloadScale::test_scale_smallfile_workload[16-1000000-4-CephFileSystem19] ERROR [100%]

==================================== ERRORS ====================================
_ ERROR at teardown of TestSmallFileWorkloadScale.test_scale_smallfile_workload[16-1000000-4-CephFileSystem19] _

    def teardown():
        """
        After all the ripsaw creation and deltion runs have finished,
        test to see if there was a leak in storage.
        """
        log.info("In scale_leaks teardown")
        orig_data = cephfs_data.ceph_fs_use
        now_data = get_cephfs_data()
        still_going_down = True
        while still_going_down:
            log.info("Waiting for Ceph to finish cleaning up")
            time.sleep(120)
            new_data = get_cephfs_data()
            still_going_down = False
            for entry in new_data:
                if new_data[entry] < now_data[entry]:
                    still_going_down = True
                    now_data[entry] = new_data[entry]
        for entry in now_data:
            # Leak indicated if over %50 more storage is used.
            log.info(f"{entry} now uses {now_data[entry]} bytes")
            log.info(f"{entry} originally used {orig_data[entry]} bytes")
            ratio = now_data[entry] / orig_data[entry]
            check = ratio < 1.50
            errmsg = f"{entry} over 50% larger -- possible leak"
>           assert check, errmsg
E           AssertionError: ocs-storagecluster-cephfilesystem-metadata over 50% larger -- possible leak
E           assert False

tests/e2e/scale/test_scale_small_file_workload.py:85: AssertionError
---------------------------- Captured stderr setup -----------------------------`

**Comment by keesturam** [comment]
@ramkiperiy Thanks for sending this PR at such a short notice

**Pull request merged**
