### PR TITLE
Python 3.10 support

### PR DESCRIPTION
**Pull request by clacroix12**
Closes: #6158 

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by shyRozen** [comment]
+1

**Review by vavuthu — APPROVED** [review]

**Comment by clacroix12** [comment]
I've tested unit tests locally in the py310 env successfully. I'm in the process of testing ocp/ocs deployment using a python 3.10 virtualenv before verifying.

**Comment by clacroix12** [comment]
I'm seeing the following error when deployment testing, looks like there might be an issue with the TimeoutSampler code with python 3.10 because I'm not seeing the same issue with a 3.8 env. Will need to dig into this a bit.

```
    @retry(ResourceWrongStatusException, tries=4, delay=5, backoff=1)
    def wait_for_phase(self, phase, timeout=300, sleep=5):
        """
        Wait till phase of resource is the same as required one passed in
        the phase parameter.

        Args:
            phase (str): Desired phase of resource object
            timeout (int): Timeout in seconds to wait for desired phase
            sleep (int): Time in seconds to sleep between attempts

        Raises:
            ResourceWrongStatusException: In case the resource is not in expected
                phase.
            NotSupportedFunctionError: If resource doesn't have phase!
            ResourceNameNotSpecifiedException: in case the name is not
                specified.

        """
        self.check_function_supported(self._has_phase)
        self.check_name_is_specified()
        sampler = TimeoutSampler(timeout, sleep, func=self.check_phase, phase=phase)
        if not sampler.wait_for_func_status(True):
>           raise ResourceWrongStatusException(
                f"Resource: {self.resource_name} is not in expected phase: " f"{phase}"
            )
E           ocs_ci.ocs.exceptions.ResourceWrongStatusException: Resource Resource: ocs-storagecluster is not in expected phase: Ready

ocs_ci/ocs/ocp.py:932: ResourceWrongStatusException
```

**Review by petr-balogh — DISMISSED** [review]

**Review by petr-balogh — APPROVED** [review]

**Review by petr-balogh — DISMISSED** [review]

**Review by ebenahar — DISMISSED** [review]

**Review by petr-balogh — APPROVED** [review]

**Comment by petr-balogh** [comment]
Can this be re-verified @clacroix12 ?

**Review by shivamdurgbuns — APPROVED** [review]
LGTM

**Comment by petr-balogh** [comment]
@clacroix12 once you back working, can you please take a look, I think good time to move with this PR and really add support for 3.10

**Review by shivamdurgbuns — APPROVED** [review]

**Pull request closed without merging**
