### PR TITLE
Add tag to ocs must gather image

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #1376

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
We have to verify with invoking must gather somehow ;)

**Comment by clacroix12** [comment]
@petr-balogh yes, we have [test_must_gather](https://github.com/red-hat-storage/ocs-ci/blob/master/tests/manage/z_cluster/test_must_gather.py) which is marked as `tier1`

**Comment by petr-balogh** [comment]
@clacroix12 I saw that your validation failed so I triggered another Pr validation job. Please check the results and I guess we can merge if verified.

**Comment by clacroix12** [comment]
@petr-balogh I saw that and checked the results. The must gather test failed with the following error:
```
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod  -n openshift-storage -o yaml. Error is Unable to connect to the server: dial tcp: lookup api.jnk-pr1377-b953.qe.rh-ocs.com on 10.11.5.19:53: no such host
```
I'm going to trigger another PR test on vmware after my other test is complete.

**Comment by clacroix12** [comment]
> PR validation [Job FAILED](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/967//testReport) (installation failed, tests not executed).

Another failure due to the jenkins slave not being provisioned properly.

**Comment by clacroix12** [comment]
> PR validation [Job FAILED](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/969//testReport) (installation failed, tests not executed).

Failed due to TLV vcenter being inaccessible. I'm going to run this again on a DC in another vcenter.

**Comment by vasukulkarni** [comment]
Had a discussion with @clacroix12 , Since this is blocking getting ocs-must gather we are merging this ASAP  and can help debug issues with operator failing in dev CI. The PR is pretty safe to merge and our testing activity will happen in background.

**Comment by petr-balogh** [comment]
@clacroix12 Actually I see issue with 4.2 as we are using RC build and there is no such tag propagated to must-gather image:  https://quay.io/repository/rhceph-dev/ocs-must-gather?tag=latest&tab=tags
```
dir/openshift-cluster-dir/auth/kubeconfig adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather:4.2-rc --dest-dir=/home/jenkins/current-cluster-dir/logs/failed_testcase_ocs_logs_1581068201/deployment_ocs_logs/ocs_must_gather.
Error is error: gather did not start for pod must-gather-7zd26: unable to pull image: ErrImagePull: rpc error: code = Unknown desc = Error reading manifest 4.2-rc in quay.io/rhceph-dev/ocs-must-gather: manifest unknown: manifest unknown
```

**Pull request merged**
