### PR TITLE
Total creation time fix and csi time added

### PR DESCRIPTION
**Pull request by ypersky1980**
The current PR handles the following: 

1) fixes calculation of the total creation time ( different logs are parsed and the calculation is done differently) 
The existing def get_snapshot_time(interface, snap_name, status): was deleted, since the implementation was wrong, and it measuring wrong Total snapshot creation time. 
2) CSI snapshot creation times was added

Signed-off-by: Yulia Persky <ypersky@redhat.com>

### CODE REVIEW

**Review by Avilir — APPROVED** [review]
LGTM

**Review by yati1998 — COMMENTED** [review]
LGTM

**Comment by yati1998** [comment]
@madhu-1 can you please review it once too.

**Review by Madhu-1 — APPROVED** [review]
LGTM

**Comment by ypersky1980** [comment]
> PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: performance PR Test Path: tests/ Additional Test Params: OCP VERSION: 4.10-ga OCS VERSION: 4.10 tested against branch: master
> 
> [Job UNSTABLE](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/2786//testReport) (some or all tests failed).

PR validation job wasw executed with wrong parameters. Started a new one : https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/2790/console

**Review by ramkiperiy — APPROVED** [review]

**Review by Avilir — APPROVED** [review]
LGTM

**Pull request merged**
