### PR TITLE
Add cache-dropper pod to the benchmark-operator base tests

### PR DESCRIPTION
**Pull request by Avilir**
This PR adds a cache dropper pod the benchmark-operator base tests (FIO / Smallfiles)

this will enable the benchmarks to drop off the kernel cache between samples for consistent results.

this feature supported by the FIO and Smallfiles benchmark and will integrate into them (updating the CRD files) after this PR will be merged.

### CODE REVIEW

**Comment by ramkiperiy** [comment]
@Avilir @keesturam General question, can't we use/create unique name for namespace ? I see in most of ripsaw tests we have my-ripsaw namespace created and deleted in teardown.
Observed a problem in one of the test execution, my-ripsaw namespace failed to be deleted and subsequent tests failed that namesapce already exists.

**Review by keesturam — APPROVED** [review]
Looks good Avi
Did we see any change in results after introducing dropping cache?

**Comment by keesturam** [comment]
> @Avilir @keesturam General question, can't we use/create unique name for namespace ? I see in most of ripsaw tests we have my-ripsaw namespace created and deleted in teardown.
> Observed a problem in one of the test execution, my-ripsaw namespace failed to be deleted and subsequent tests failed that namesapce already exists. Don't think so this is proper PR to address this.

how often do we see this issue?
my-ripsaw project not getting deleted could be an underlying issue in the cluster. I'm not sure if creating a new project is a good idea.

**Review by ramkiperiy — APPROVED** [review]

**Comment by ramkiperiy** [comment]
> > @Avilir @keesturam General question, can't we use/create unique name for namespace ? I see in most of ripsaw tests we have my-ripsaw namespace created and deleted in teardown.
> > Observed a problem in one of the test execution, my-ripsaw namespace failed to be deleted and subsequent tests failed that namesapce already exists. Don't think so this is proper PR to address this.
> 
> how often do we see this issue?
> my-ripsaw project not getting deleted could be an underlying issue in the cluster. I'm not sure if creating a new project is a good idea.

During a testing I observed this problem twice out of 4 runs but still good to add more validation to remove my-ripsaw namespace before teardown.

**Pull request merged**
