### PR TITLE
make mcgcli_pod_fixture a prerequisite for mcg_obj fixture

### PR DESCRIPTION
**Pull request by fbalak**
In this PR is dropped `autosuse` in `mcgcli_pod_fixture` and making the fixture a prerequisite for `mcg_obj` fixture.
@MeridianExplorer Does it make sense? `mcg_obj` fixture is used in almost all mcg tests. It seems that tests that don't use `mcg_obj` fixture wouldn't benefit from this.

Fixes https://github.com/red-hat-storage/ocs-ci/issues/2821

Signed-off-by: Filip Balak <fbalak@redhat.com>

### CODE REVIEW

**Review by mbukatov — APPROVED** [review]

**Comment by vasukulkarni** [comment]
tests are failing, not sure

**Comment by fbalak** [comment]
There was only one failure in teardown when deleting uls. Other mcg tests passed. I don't think that the failure was caused by this PR. Let's wait for input from @MeridianExplorer.
Also I added link to `mcgcli_pod_fixture` into `test_deployment` because deployment failed without it on sanity check.

**Comment by MeridianExplorer** [comment]
The ULS deletion problem is known, and is unrelated to the PR.
The solution offered in this PR seems good - can we please have a run of all tiers over `tests/manage/mcg/`?

**Review by MeridianExplorer — APPROVED** [review]

**Comment by ebenahar** [comment]
Marking as verified based on @fbalak and @MeridianExplorer observations

**Pull request merged**
