### PR TITLE
Fix for toolbox pod disappearance in external mode

### PR DESCRIPTION
**Pull request by sidhant-agrawal**
Fixes: #3941 

Signed-off-by: Sidhant Agrawal <sagrawal@redhat.com>

### CODE REVIEW

**Comment by sidhant-agrawal** [comment]
Ran `tier1` tests in `tests/manage/` toolbox pod persisted this time till the end of the run

Adding health check at different intervals from the run:

```
18:54:34 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-external-798d89f477-qxt86 -- ceph health
18:54:34 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
```
```
01:08:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-external-798d89f477-qxt86 -- ceph health
01:08:43 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
```
```
01:16:57 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-external-798d89f477-s54zq -- ceph health
01:16:57 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
```

Marking PR as Verified

**Review by ebenahar — APPROVED** [review]

**Review by jilju — APPROVED** [review]

**Review by petr-balogh — DISMISSED** [review]

**Comment by petr-balogh** [comment]
@sidhant-agrawal please rebase the PR and force push to finsih PR check for 3.8 and 3.9 which are required for mege

**Comment by sidhant-agrawal** [comment]
Rebased for PR checks to finish.

**Review by vasukulkarni — APPROVED** [review]

**Comment by vasukulkarni** [comment]
Hope this doesn't break 4.6???

**Comment by sidhant-agrawal** [comment]
> Hope this doesn't break 4.6???

I believe for 4.6 it was already broken since we added `return` [here](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/ocs/utils.py#L773) 
The current solution should ideally work for 4.6. To confirm, I have started PR validation for OCS 4.6

**Comment by sidhant-agrawal** [comment]
> PR validation
> 
> Cluster Name:
> Cluster Configuration: conf/ocsci/external_rhcs_cluster.yaml
> PR Test Suite: tier1
> PR Test Path: tests/manage/
> Additional Test Params:
> OCP VERSION: 4.6
> OCS VERSION: 4.6
> 
> [Job UNSTABLE](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/363//testReport) (some or all tests failed).

toolbox pod is working in OCS 4.6
Health check from above run at different intervals:
```
01:26:55 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-external-798d89f477-r2bxj -- ceph health
01:26:55 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
```
```
07:40:18 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-external-798d89f477-r2bxj -- ceph health
07:40:19 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
```

**Review by RazTamir — APPROVED** [review]

**Pull request merged**
