### PR TITLE
FIO | clean code duplication

### PR DESCRIPTION
**Pull request by Avilir**
with this PR i am implementing code reused of Performance test withing the FIO benchmark test.

Signed-off-by: Avi Liani <alayani@redhat.com>

### CODE REVIEW

**Comment by Avilir** [comment]
> PR validation
> 
> Cluster Name:
> Cluster Configuration:
> PR Test Suite: performance
> PR Test Path: tests/e2e/performance/test_fio_benchmark.py
> Additional Test Params:
> OCP VERSION: 4.6
> OCS VERSION: 4.6
> 
> [Job UNSTABLE](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/74//testReport) (some or all tests failed).

Tests with compression failed on the PG_Count BZ [#1926930](https://bugzilla.redhat.com/show_bug.cgi?id=1926930)

**Review by wusui — APPROVED** [review]
Looks good.  This makes use of ocs_ci/ocs/perftests.py.  Should we also modify other tests such as tests/e2e/scale/test_scale_small_file_workload.py to also use ocs_ci/ocs/pertests?

**Comment by Avilir** [comment]
> Looks good. This makes use of ocs_ci/ocs/perftests.py. Should we also modify other tests such as tests/e2e/scale/test_scale_small_file_workload.py to also use ocs_ci/ocs/pertests?

@wusui , this is exactly the purpose of this module, to be the parent of the performance and scale tests, with methods and function which used in these tests

**Review by keesturam — APPROVED** [review]
LGTM
@Avilir Thanks for making these minor yet important changes into our test cases.

**Review by ramkiperiy — APPROVED** [review]
Thanks for making this change Avi !!

**Comment by Avilir** [comment]
> PR validation
> 
> Cluster Name:
> Cluster Configuration:
> PR Test Suite: performance
> PR Test Path: tests/e2e/performance/test_fio_benchmark.py
> Additional Test Params:
> OCP VERSION: 4.6-ga
> OCS VERSION: 4.6
> 
> [Job UNSTABLE](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/89//testReport) (some or all tests failed).

Tests with compression failed on the PG_Count BZ #1926930
re-running the test without compression

**Pull request merged**
