### PR TITLE
Ignore flake8 checking for bash files

### PR DESCRIPTION
**Pull request by Shrivaibavi**
Signed-off-by: Shrivaibavi Raghaventhiran <sraghave@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
flake8 is complaining for bash files? can you paste the errors please? thanks

**Comment by Shrivaibavi** [comment]
@vasukulkarni http://pastebin.test.redhat.com/801437

**Comment by petr-balogh** [comment]
Vaibavi, you shouldn't run flake8 against the bash file.  If you would like to see if you have issue with flake8 in your repo you should run `tox -e flake8` and you will see what it complains.  But flake8 should go just over *.py files I guess.  Your problem can be that this [script](https://github.com/openshift-qe/v3-testfiles/blob/master/logging/tools/getOperatorSourceMetadata.sh) generates python files, and those are then checked by tox and flake8 but as the script is not triggered on travis, I think it shouldn't complain there.

So if you would like to prevent to check those generated files and if you have in the path `ocs_ci/utility/pull_images_for_logging_42/` just shell scripts, you can ignore this folder to not fail local tox execution against generated files during execution.

**Comment by Shrivaibavi** [comment]
@petr-balogh Thank you for pointing out. somehow tox command did not work for me. The travis build did not complain for shell scripts as i thought, I am closing this PR.

That was good learning for me.

**Pull request closed without merging**
