### PR TITLE
test_pod_reattachtime.py  - Increasing pod creation timeout and reducing number of files for cephfs many files test case 

### PR DESCRIPTION
**Pull request by ypersky1980**
This PR handles 2 issues: 

1) Increasing pod creation timeout in test_pod_reattachtime.py test following failures on this.

From https://github.com/red-hat-storage/ocs-ci/issues/9336 :

The following test cases failed :

[tests.cross_functional.performance.csi_tests.test_pod_reattachtime.TestPodReattachTimePerformance.test_pod_reattach_time_performance[CephFileSystem-3-120-70]](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/35137/testReport/tests.cross_functional.performance.csi_tests.test_pod_reattachtime/TestPodReattachTimePerformance/test_pod_reattach_time_performance_CephFileSystem_3_120_70_/)

Error:

ocs_ci.ocs.exceptions.PerformanceException: Pod creation time is 87.04964661598206 and greater than 70 seconds

[tests.cross_functional.performance.csi_tests.test_pod_reattachtime.TestPodReattachTimePerformance.test_pod_reattach_time_performance[CephFileSystem-13-600-420]](https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/35137/testReport/tests.cross_functional.performance.csi_tests.test_pod_reattachtime/TestPodReattachTimePerformance/test_pod_reattach_time_performance_CephFileSystem_13_600_420_/)

Error:

ocs_ci.ocs.exceptions.PerformanceException: Pod creation time is 491.2622141838074 and greater than 420 seconds

Conclusion: Submit a PR and increase Pod Creation time.

2) Reducing number of files in CephFS pod reattach with many files test case. 
We are reducing from 13 to 12 linux kernel copies written to the PVC prior to Pod Reattach action. 
During investigation a BZ was opened https://bugzilla.redhat.com/show_bug.cgi?id=2270545 
When the BZ will be fixed - the number of Linux Kernel copies should be again increased to 13 . 

Currently, because of the BZ , the maxumal number of files for pod reattach to succeed is ~ 800K files, while in 4.14 the number was ~860 K files.

### CODE REVIEW

**Comment by ypersky1980** [comment]
The validation has passed when run locally, the tests results are uploaded to Perf Dashboard, 


The ES links are the following ( from test run log) : 

http://10.0.78.167:8080/index.php?version1=41&build1=130&platform1=2&az_topology1=3&test_name%5B%5D=1&test_name%5B%5D=2&test_name%5B%5D=3&test_name%5B%5D=4&test_name%5B%5D=6&test_name%5B%5D=8&test_name%5B%5D=9&test_name%5B%5D=10&test_name%5B%5D=11&test_name%5B%5D=15&test_name%5B%5D=16&test_name%5B%5D=17&test_name%5B%5D=18&test_name%5B%5D=20&test_name%5B%5D=21&test_name%5B%5D=23&version2=40&build2=135&platform2=2&az_topology2=3&version3=&build3=&version4=&build4=&submit=Choose+options 

04:09:49 - MainThread - test_pod_reattachtime - INFO  - The Result can be found at : http://10.0.78.167:9200/pod_reattach_time_fullres/_search?q=uuid:"95e12bbcdaa444d3b8a96bd42b779910"
05:46:02 - MainThread - test_pod_reattachtime - INFO  - The Result can be found at : http://10.0.78.167:9200/pod_reattach_time_fullres/_search?q=uuid:"210fae4370b943b2b7aad5d242eb08f2"
07:17:18 - MainThread - test_pod_reattachtime - INFO  - The Result can be found at : http://10.0.78.167:9200/pod_reattach_time_fullres/_search?q=uuid:"48f7686a6ad147dc97aac22a83814e58"
09:46:29 - MainThread - test_pod_reattachtime - INFO  - The Result can be found at : http://10.0.78.167:9200/pod_reattach_time_fullres/_search?q=uuid:"e2e17905c559483099923a76a5209b25"

**Review by pintojoy — APPROVED** [review]
LGTM

**Review by ramkiperiy — APPROVED** [review]

**Comment by ramkiperiy** [comment]
@ypersky1980 can you add verified label to the PR, we can merge this PR

**Comment by ypersky1980** [comment]
The PR was merged, therefore closing the issue.

**Pull request merged**
