### PR TITLE
Removed need for run_ocsci.py as main entry point

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #270 

Note: Users will need to execute `pip install -r requirements.txt` to fix their `run-ci` entry points.

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by RazTamir** [comment]
LGTM..

Please verify and remember to send mail as soon as this is merge to remind about the need for pip install.

Thanks

**Comment by clacroix12** [comment]
@zmc I didn't notice until now that our unit tests for the main function are passing arguments directly and testing the configuration according to what is being passed. My question is now that the main method does not actually accept arguments and instead just pulls directly from `sys` how should we go about testing functionality in these unit tests?

**Comment by mbukatov** [comment]
> @zmc I didn't notice until now that our unit tests for the main function are passing arguments directly and testing the configuration according to what is being passed. My question is now that the main method does not actually accept arguments and instead just pulls directly from `sys` how should we go about testing functionality in these unit tests?

Good point, this is usually done like this:

```
def main(argv=None):
    argv = argv or sys.argv
```

**Comment by zmc** [comment]
@clacroix12 I'd go with what @mbukatov said!

**Comment by clacroix12** [comment]
Thanks @mbukatov and @zmc! Looks like that works perfectly. Going to kick off another deployment test just to officially verify on the latest changes.

**Pull request merged**
