### PR TITLE
Adapt performance testing ripsaw small file creation test for scale t…

### PR DESCRIPTION
**Pull request by wusui**
…esting

Signed-off-by: wusui <wusui@redhat.com>

### CODE REVIEW

**Review by Avilir — COMMENTED** [review]
@wusui this is the same as the performance test, just with different number of files.
i think we can use the performance class (for preventing code duplication) for the test and just change the numbers.

**Comment by keesturam** [comment]
@wusui can you please update the description with a meaningful message.

**Comment by keesturam** [comment]
@wusui please update the description

**Comment by wusui** [comment]
Avi is coorect about the code duplication.  I will try to refactor this with the performance code.

I will add more information to the bug report itself.

**Pull request closed without merging**
