### PR TITLE
Fixing node replacement issue in vSphere platform

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes :#7172
Fixes: #7390 
Fixes: #6724 
Fixes: #1821

Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Comment by vavuthu** [comment]
verifed here: https://url.corp.redhat.com/29993be

logs:  https://url.corp.redhat.com/4bea2c4

```<h2>Results</h2>


Result | Test | Description | Duration | Links
-- | -- | -- | -- | --
Passed | tests/manage/z_cluster/nodes/test_node_replacement_proactive.py::TestNodeReplacement::test_nodereplacement_proactive | Knip-894 Node Replacement proactive(without IO running) | 737.10 | Log File


Results
Result 	Test 	Description 	Duration 	Links
Passed 	tests/manage/z_cluster/nodes/test_node_replacement_proactive.py::TestNodeReplacement::test_nodereplacement_proactive 	Knip-894 Node Replacement proactive(without IO running) 	737.10 	[Log File](http://dev/null)
```

**Review by petr-balogh — APPROVED** [review]

**Review by am-agrawa — APPROVED** [review]

**Comment by am-agrawa** [comment]
@vavuthu @petr-balogh The fix needs to be backported until ODF 4.9 if not already. Just adding a note for reference.

**Comment by am-agrawa** [comment]
> @vavuthu @petr-balogh The fix needs to be backported until ODF 4.9 if not already. Just adding a note for reference.

@vavuthu @petr-balogh Gentle reminder!

**Comment by pintojoy** [comment]
@vavuthu Is the fix backported to 4.10 and 4.11? I am seeing similar failures with those runs (https://url.corp.redhat.com/500fe7d and https://url.corp.redhat.com/a691a18)

**Pull request merged**
