### PR TITLE
AWS cleanup: skip cloudformation VPCs

### PR DESCRIPTION
**Pull request by ebenahar**
Signed-off-by: Elad Ben Aharon <ebenahar@redhat.com>

### CODE REVIEW

**Comment by ebenahar** [comment]
[cleanup_log.zip](https://github.com/red-hat-storage/ocs-ci/files/4194988/cleanup_log.zip)

**Comment by clacroix12** [comment]
I'm not quite sure what we are trying to do here. Title says we are handling cloudformation VPCs but the code is just logging which ones we found. Are we supposed to be deleting these cloudformation stacks?

I'm assuming this is meant to support cleaning up after UPI deployments since that's the only time we use cloudformation to create the infrastructure. If this is the case then we will also need to handle several other cloudformation stacks before we can delete the VPC stack. You can see what we are doing to destroy the cluster in the [AWSUPI destroy_cluster method](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/aws.py#L847-L885)

**Comment by ebenahar** [comment]
@clacroix12 the handling in the title is indeed misleading. 
I have observed that when VPCs that are of cloudfomation exist, aws-cleanup fails as there is no tag of 'Name' for that VPC. 
Handling here is done in a sense of not failing the program, but skipping this VPC deletion with a warning message at the end detailing the names of those VPCs not deleted. 
The reason is that AFIAK, we don't have a way of removing this kind of resources using our cleaup

**Comment by clacroix12** [comment]
@ebenahar got it! Yeah, we handle the cleanup in our UPI destroy method but not in our `ci-cleanup` yet.

**Pull request merged**
