### PR TITLE
Add security fixes

### PR DESCRIPTION
**Pull request by petr-balogh**
Added suggestions from dependabot PRs here:
https://github.com/red-hat-storage/ocs-ci/security/dependabot

### CODE REVIEW

**Comment by petr-balogh** [comment]
Verification triggered here:
https://url.corp.redhat.com/2c04b66

**Comment by petr-balogh** [comment]
New verification after updating elasticsearch package:
https://url.corp.redhat.com/774a845

**Review by vavuthu — APPROVED** [review]

**Comment by petr-balogh** [comment]
New verification job:
https://url.corp.redhat.com/c26a036

**Review by dahorak — DISMISSED** [review]

**Comment by petr-balogh** [comment]
Performance suite:
https://url.corp.redhat.com/f44c62b

**Review by OdedViner — DISMISSED** [review]

**Review by vavuthu — DISMISSED** [review]

**Comment by petr-balogh** [comment]
New performance suite after updating scheme for elastic search:
https://url.corp.redhat.com/fbd6a67

**Review by vavuthu — APPROVED** [review]

**Review by pintojoy — APPROVED** [review]
LGTM

**Comment by petr-balogh** [comment]
Last results of performance testcase:
https://url.corp.redhat.com/8af7dce
shows that the Elasticsearch issue complaining about missing scheme is now fixed.

Considering as verified after discussion with @pintojoy .

**Pull request merged**
