### PR TITLE
Increasing the timeout for fio tests to fix https://github.com/red-hat-storage/ocs-ci/issues/8644

### PR DESCRIPTION
**Pull request by pintojoy**

### CODE REVIEW

**Review by ypersky1980 — DISMISSED** [review]
LGTM

**Review by ramkiperiy — DISMISSED** [review]
lgtm

**Comment by ramkiperiy** [comment]
@pintojoy could you run validation locally or try to execute it in existing cluster?

**Comment by pintojoy** [comment]
Verification logs can be found at https://url.corp.redhat.com/93b9a26

**Review by ramkiperiy — APPROVED** [review]
lgtm

**Review by ypersky1980 — APPROVED** [review]
LGTM

**Pull request merged**
