### PR TITLE
set mgr count for 4.15 upgrades and deployment

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #8770 

Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Comment by vavuthu** [comment]
verification job: https://url.corp.redhat.com/473524b

**Comment by Nikhil-Ladha** [comment]
@vavuthu shouldn't we add a check here as well?
https://github.com/red-hat-storage/ocs-ci/blob/e314bccccf8df461a7141fd7cca20ee3ce7b38bd/ocs_ci/deployment/deployment.py#L1572

**Comment by vavuthu** [comment]
> @vavuthu shouldn't we add a check here as well for new deployments of 4.15?
> 
> https://github.com/red-hat-storage/ocs-ci/blob/e314bccccf8df461a7141fd7cca20ee3ce7b38bd/ocs_ci/deployment/deployment.py#L1572

done

**Review by petr-balogh — APPROVED** [review]

**Comment by vavuthu** [comment]
> verification job: https://url.corp.redhat.com/473524b

upgrade odf version  is not set in above job . triggered upgrade job here https://url.corp.redhat.com/0ddbb0d

**Comment by vavuthu** [comment]
> > verification job: https://url.corp.redhat.com/473524b
> 
> upgrade odf version is not set in above job . triggered upgrade job here https://url.corp.redhat.com/0ddbb0d

upgrade job succeed.
```
2023-10-31 12:17:27  06:47:26 - MainThread - ocs_ci.ocs.resources.pod - INFO  - Waiting for 2 pods with selector: app=rook-ceph-mgr to be running and upgraded.
2023-10-31 12:17:27  06:47:26 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod  -n openshift-storage -o yaml
2023-10-31 12:17:29  06:47:29 - MainThread - ocs_ci.ocs.resources.pod - INFO  - Found 2 pod(s) for selector: app=rook-ceph-mgr
2023-10-31 12:17:29  06:47:29 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod rook-ceph-mgr-a-864b6f79b4-nx8h5 -n openshift-storage -o yaml
```

**Comment by vavuthu** [comment]
> PR validation
> 
> Cluster Name: Cluster Configuration: PR Test Suite: deployment PR Test Path: tests/ Additional Test Params: OCP VERSION: 4.15 OCS VERSION: 4.15 tested against branch: master
> 
> [Job FAILED](https://url.corp.redhat.com/ae17b17) (installation failed, tests not executed).

job failed due to pipeline was not able to remove jenkins agent in destroy job.

logs:
```
2023-10-31 13:41:14  08:11:14 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod  -n openshift-storage --selector=app=rook-ceph-mgr -o yaml
2023-10-31 13:41:14  08:11:14 - MainThread - ocs_ci.ocs.ocp - INFO  - status of  at column STATUS - item(s) were [], but we were waiting for all 2 of them to be Running
2023-10-31 13:41:14  08:11:14 - MainThread - ocs_ci.utility.utils - INFO  - Going to sleep for 3 seconds before next iteration
2023-10-31 13:41:17  08:11:17 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod  -n openshift-storage --selector=app=rook-ceph-mgr -o yaml
2023-10-31 13:41:17  08:11:17 - MainThread - ocs_ci.ocs.ocp - INFO  - status of  at column STATUS - item(s) were [], but we were waiting for all 2 of them to be Running
2023-10-31 13:41:17  08:11:17 - MainThread - ocs_ci.utility.utils - INFO  - Going to sleep for 3 seconds before next iteration
2023-10-31 13:41:21  08:11:20 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod  -n openshift-storage --selector=app=rook-ceph-mgr -o yaml
2023-10-31 13:41:21  08:11:21 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod rook-ceph-mgr-a-7466b696fb-kv8zm -n openshift-storage
2023-10-31 13:41:21  08:11:21 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod rook-ceph-mgr-b-b785995-8tr29 -n openshift-storage
2023-10-31 13:41:21  08:11:21 - MainThread - ocs_ci.ocs.ocp - INFO  - status of  at column STATUS - item(s) were ['Running', 'PodInitializing'], but we were waiting for all 2 of them to be Running
2023-10-31 13:41:21  08:11:21 - MainThread - ocs_ci.utility.utils - INFO  - Going to sleep for 3 seconds before next iteration
2023-10-31 13:41:24  08:11:24 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod  -n openshift-storage --selector=app=rook-ceph-mgr -o yaml
2023-10-31 13:41:25  08:11:24 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod rook-ceph-mgr-a-7466b696fb-kv8zm -n openshift-storage
2023-10-31 13:41:25  08:11:25 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get Pod rook-ceph-mgr-b-b785995-8tr29 -n openshift-storage
2023-10-31 13:41:25  08:11:25 - MainThread - ocs_ci.ocs.ocp - INFO  - 2 resources already reached condition!
```
Hence marking as verified since both new deployment and upgrade passed successfully

**Review by Akarsha-rai — APPROVED** [review]

**Pull request merged**
