### PR TITLE
Adding Memory and CPU option for RHEL in vSphere platform

### PR DESCRIPTION
**Pull request by vavuthu**
Signed-off-by: vavuthu <vavuthu@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
> @petr-balogh ,
> 
> Do we need this for AWS RHEL workers as well ?

@shylesh that's the good question.

How we do in AWS rhel? Do we set the same as we have for normal workers?  @vavuthu why do we differentiate between rhel and normal (CoreOS) workers?  

Thinking about why we just do not use the same values from https://github.com/red-hat-storage/ocs-ci/pull/1198/files#diff-c2468e5c96b4d141e508c8f926f3ab10R11 and https://github.com/red-hat-storage/ocs-ci/pull/1198/files#diff-c2468e5c96b4d141e508c8f926f3ab10R13 ?

**Comment by vavuthu** [comment]
> > @petr-balogh ,
> > Do we need this for AWS RHEL workers as well ?
> 
> @shylesh that's the good question.
> 
> How we do in AWS rhel? Do we set the same as we have for normal workers? @vavuthu why do we differentiate between rhel and normal (CoreOS) workers?
> 
> Thinking about why we just do not use the same values from https://github.com/red-hat-storage/ocs-ci/pull/1198/files#diff-c2468e5c96b4d141e508c8f926f3ab10R11 and https://github.com/red-hat-storage/ocs-ci/pull/1198/files#diff-c2468e5c96b4d141e508c8f926f3ab10R13 ?

I would like to differentiate the between CoreOS and RHEL. and provide option to user to change for only RHEL if needs.

**Comment by shylesh** [comment]
> > @petr-balogh ,
> > Do we need this for AWS RHEL workers as well ?
> 
> @shylesh that's the good question.
> 
> How we do in AWS rhel? Do we set the same as we have for normal workers? @vavuthu why do we differentiate between rhel and normal (CoreOS) workers?
> 
> Thinking about why we just do not use the same values from https://github.com/red-hat-storage/ocs-ci/pull/1198/files#diff-c2468e5c96b4d141e508c8f926f3ab10R11 and https://github.com/red-hat-storage/ocs-ci/pull/1198/files#diff-c2468e5c96b4d141e508c8f926f3ab10R13 ?

@petr-balogh ,

For RHEL workers on AWSUPI we are going with whatever m5.4xlarge instances have in terms of cpus and other resources, only storage part we have parameterized. Same case with RHCOS workers as well.

**Comment by petr-balogh** [comment]
@vavuthu what values are used if those two vars are not set in the config:
```
  rhel_num_cpus: '16'
  rhel_memory: '65536' 
```
?

Do we have somewhere set default values or they are somewhere in the template?
I think that the best approach is when we do not specify those values we should use the values from:
 `worker_num_cpus` and `memory` as this will use the same values as we have for current worker nodes WDYT?

**Comment by vavuthu** [comment]
> @vavuthu what values are used if those two vars are not set in the config:
> 
> ```
>   rhel_num_cpus: '16'
>   rhel_memory: '65536' 
> ```
> 
> ?
> 
> Do we have somewhere set default values or they are somewhere in the template?
> I think that the best approach is when we do not specify those values we should use the values from:
> `worker_num_cpus` and `memory` as this will use the same values as we have for current worker nodes WDYT?

@petr-balogh If we don't specify the values, it will take from https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/templates/ocp-deployment/scale_up_terraform.tfvars.j2#L14

**Pull request merged**
