### PR TITLE
Remove skip from logging testcase

### PR DESCRIPTION
**Pull request by Shrivaibavi**
Fixes: #1833
Fixes: #1812

Signed-off-by: Shrivaibavi Raghaventhiran <sraghave@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
Please add Fixes or Description for this PR.

**Comment by petr-balogh** [comment]
@Shrivaibavi  updated title and added fixes as first comment for both issues we had opened for this.

**Comment by petr-balogh** [comment]
@Shrivaibavi it's also better to add WIP: to the title as it will really block from merge ;) So I did that now and changed the title.

**Comment by Shrivaibavi** [comment]
Passed logs http://pastebin.test.redhat.com/863247

**Pull request merged**
