### PR TITLE
Add data integrity check for fio workload

### PR DESCRIPTION
**Pull request by OdedViner**
Fixes: #4663
Signed-off-by: Oded Viner <oviner@redhat.com>

### CODE REVIEW

**Comment by prsurve** [comment]
i feel this verify thing can also be added to existing tier1 tests

**Comment by OdedViner** [comment]
> i feel this verify thing can also be added to existing tier1 tests

Do you think that we need to change the default value from `verify=None` to  `verify="crc32c"`?

**Review by Avilir — APPROVED** [review]
LGTM

**Review by vasukulkarni — APPROVED** [review]

**Review by Avilir — APPROVED** [review]
LGTM

**Pull request closed without merging**
