### PR TITLE
Move to pytest-order plugin out of not maintained pytest-ordering

### PR DESCRIPTION
**Pull request by petr-balogh**

### CODE REVIEW

**Comment by petr-balogh** [comment]
```
$ pytest ocs_ci/framework/tests/order/
=============================================================================================================================================================================== test session starts ================================================================================================================================================================================
platform darwin -- Python 3.9.18, pytest-6.2.5, py-1.11.0, pluggy-1.3.0
rootdir: /Users/pbalogh/Code/OCS/ocs-ci, configfile: pytest.ini
plugins: marker-bugzilla-0.9.4, order-1.2.0, repeat-0.9.3, flaky-3.7.0, html-3.1.1, metadata-1.11.0, ordering-0.6, logger-0.5.1, anyio-4.2.0
collecting ...
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- live log collection --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
collected 8 items

ocs_ci/framework/tests/order/z/test_z.py::test_8 PASSED
ocs_ci/framework/tests/order/z/test_z.py::test_7 PASSED
ocs_ci/framework/tests/order/e/test_e.py::test_6 PASSED
ocs_ci/framework/tests/order/e/test_e.py::test_5 PASSED
ocs_ci/framework/tests/order/e/test_e.py::test_4 PASSED
ocs_ci/framework/tests/order/a/test_a.py::test_3 PASSED
ocs_ci/framework/tests/order/a/test_a.py::test_2 PASSED
ocs_ci/framework/tests/order/a/test_a.py::test_1 PASSED
```

The our current tests looks OK after this change which should verify the order is correct.

**Review by shylesh — APPROVED** [review]
LGTM

**Review by shivamdurgbuns — APPROVED** [review]

**Review by dahorak — DISMISSED** [review]

**Comment by petr-balogh** [comment]
To be on safe side, triggered verification job:
https://url.corp.redhat.com/5d37595

**Review by vavuthu — APPROVED** [review]

**Comment by petr-balogh** [comment]
Verification looked OK, just noticed one post upgrade test ran in between of OCP and OCS upgrade - it's because test was marked by both post_ocs_upgrade and post_ocp_upgrade . After discussion with @Shrivaibavi , decided to remove the post_ocp_upgrade marker - to have test running after ODF upgrade. Marking as verified based on last execution here:
https://url.corp.redhat.com/c97a804

**Pull request merged**
