### PR TITLE
Assigning red_squad to noobaa scale tests.

### PR DESCRIPTION
**Pull request by tiffanyn108**
Assigned noobaa scale tests to req squad.

### CODE REVIEW

**Review by keesturam — DISMISSED** [review]

**Review by keesturam — APPROVED** [review]

**Comment by ramkiperiy** [comment]
@tiffanyn108 could you remove scale markers and add only Red_Squad marker?

**Comment by tiffanyn108** [comment]
> @tiffanyn108 could you remove scale markers and add only Red_Squad marker?

@ramkiperiy These test cases need to run on a production cluster which has larger resources.  If we remove scale markers, which marker we should use for these test cases?

**Comment by ramkiperiy** [comment]
PR https://github.com/red-hat-storage/ocs-ci/pull/8483 --> with this PR there should be some conflict wrt moving Noobaa scale tests under Red Squad, good to hold those changes till #8483 gets merged?

**Comment by tiffanyn108** [comment]
> PR #8483 --> with this PR there should be some conflict wrt moving Noobaa scale tests under Red Squad, good to hold those changes till #8483 gets merged?

I think so too, let's wait for #8483 before changing the ownership of scale tests.

**Comment by tiffanyn108** [comment]
> > PR #8483 --> with this PR there should be some conflict wrt moving Noobaa scale tests under Red Squad, good to hold those changes till #8483 gets merged?
> 
> I think so too, let's wait for #8483 before changing the ownership of scale tests.

Rebased after #8483 merged and update the owners for noobaa scale test.  Please review.

**Comment by tiffanyn108** [comment]
> > PR #8483 --> with this PR there should be some conflict wrt moving Noobaa scale tests under Red Squad, good to hold those changes till #8483 gets merged?
> 
> I think so too, let's wait for #8483 before changing the ownership of scale tests.

**Review by ramkiperiy — APPROVED** [review]

**Comment by tiffanyn108** [comment]
Closing this PR since these test case will be tracked under scale and orange squad.

**Pull request closed without merging**
