### PR TITLE
Skip RHEL worker termination if worker list is empty

### PR DESCRIPTION
**Pull request by clacroix12**
Fixes: #1118 

Signed-off-by: Coady LaCroix <clacroix@redhat.com>

### CODE REVIEW

**Comment by shylesh** [comment]
Nice catch, I didn't see this scenario.

**Comment by clacroix12** [comment]
@shylesh @petr-balogh I have been unable to get a successful PR test deployment today, however I locally tested teardowns with and without rhel workers and did not hit any issues with this change. I think it's safe to merge but I will defer to you.

**Comment by petr-balogh** [comment]
@clacroix12 I see that the job failed in destroy.
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/1935/console
ocs_ci.deployment.aws.StackStatusError: jenkins-pr1123-sg not deleted yet, current status: DELETE_IN_PROGRESS .

Do we have opened issue about this? @shylesh have you seen this?

If we do not have issue please open for investigation and maybe we have to increase wait time if delete is in progress for longer time than we wait?

**Comment by clacroix12** [comment]
@petr-balogh I don't think we have an issue created for this so I will do so. We can easily up the amount of times we check the status of the stacks before we give up.

**Comment by clacroix12** [comment]
Installation job failed however the destroy job passed so I am considering this PR verified.

**Pull request merged**
