### PR TITLE
Fix ocs371 TC logging

### PR DESCRIPTION
**Pull request by ebenahar**

### CODE REVIEW

**Comment by ebenahar** [comment]
tests/manage/test_pvc_deletion_during_io.py::TestCaseOCS371::test_run_io_and_delete_pvc 
------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------
08:57:02 - MainThread - root - INFO - All logs are located under /tmp/logs
08:57:02 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod --selector=app=rook-ceph-tools -o yaml
08:57:05 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig rsh rook-ceph-tools-76c7d559b6-mfhm2 ceph auth get-key client.admin --format json-pretty
08:57:12 - MainThread - resources.ocs - INFO - Adding Secret with name secret-test-1108570213
08:57:12 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig create -f /tmp/Secretehl84hnr -o yaml
08:57:14 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Secret secret-test-1108570213 -o yaml
08:57:17 - MainThread - resources.ocs - INFO - Adding CephBlockPool with name cbp-test-1108571709
08:57:17 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig create -f /tmp/CephBlockPoola5g1t8a0 -o yaml
08:57:18 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get CephBlockPool cbp-test-1108571709 -o yaml
08:57:19 - MainThread - tests.helpers - INFO - Verifying that block pool cbp-test-1108571709 exists
08:57:19 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod --selector=app=rook-ceph-tools -o yaml
08:57:22 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig rsh rook-ceph-tools-76c7d559b6-mfhm2 ceph osd lspools --format json-pretty
08:57:27 - MainThread - resources.ocs - INFO - Adding StorageClass with name storageclass-test-1108572752
08:57:27 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig create -f /tmp/StorageClasshn5hx0pn -o yaml
08:57:28 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get StorageClass storageclass-test-1108572752 -o yaml
08:57:30 - MainThread - resources.ocs - INFO - Adding PersistentVolumeClaim with name pvc-test-1108573029
08:57:30 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig create -f /tmp/PersistentVolumeClaimbz2_ojt7 -o yaml
08:57:31 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get PersistentVolumeClaim pvc-test-1108573029 -o yaml
08:57:32 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get PersistentVolumeClaim pvc-test-1108573029 -o yaml
08:57:33 - MainThread - resources.ocs - INFO - Adding Pod with name pod-test-1108573389
08:57:33 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig create -f /tmp/POD_z0u12obz -o yaml
08:57:34 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod pod-test-1108573389 -o yaml
08:57:35 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod pod-test-1108573389 -o yaml
08:57:39 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod pod-test-1108573389 -o yaml
08:57:44 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod pod-test-1108573389 -o yaml
08:57:50 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod pod-test-1108573389 -o yaml
08:57:55 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Pod pod-test-1108573389 -o yaml
-------------------------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------------------------
08:57:56 - MainThread - resources.pod - INFO - Running I/O on pod pod-test-1108573389
08:57:56 - Thread-1 - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig rsh pod-test-1108573389 bash -c "let i=0; while true; do echo Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. >> /var/lib/www/html/test$i; let i++; sleep 0.01; done"
08:57:58 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig rsh pod-test-1108573389 bash -c "find /var/lib/www/html/test1"
08:58:02 - MainThread - tests.manage.test_pvc_deletion_during_io - INFO - Deleting PVC pvc-test-1108573029
08:58:02 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig delete PersistentVolumeClaim pvc-test-1108573029 --wait=false
08:58:03 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get PersistentVolumeClaim pvc-test-1108573029
08:58:21 - MainThread - tests.manage.test_pvc_deletion_during_io - INFO - Deleting PVC pod-test-1108573389
08:58:21 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig delete Pod pod-test-1108573389
08:58:24 - Thread-1 - utility.utils - ERROR - CMD error:: command terminated with exit code 137

08:58:24 - Thread-1 - resources.pod - INFO - I/O command got terminated as expected
08:58:31 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get PersistentVolumeClaim pvc-test-1108573029
08:58:35 - MainThread - utility.utils - ERROR - CMD error:: Error from server (NotFound): persistentvolumeclaims "pvc-test-1108573029" not found

PASSED
------------------------------------------------------------------------------------------------ live log teardown ------------------------------------------------------------------------------------------------
08:58:35 - MainThread - utility.utils - INFO - Executing command: oc --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get StorageClass storageclass-test-1108572752 -o yaml
08:58:39 - MainThread - utility.utils - INFO - Executing command: oc --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig delete StorageClass storageclass-test-1108572752
08:58:44 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get CephBlockPool cbp-test-1108571709 -o yaml
08:58:48 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig delete CephBlockPool cbp-test-1108571709
08:58:53 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get Secret secret-test-1108570213 -o yaml
08:58:56 - MainThread - utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig delete Secret secret-test-1108570213


=========================================================================================== 1 passed in 122.69 seconds

**Comment by RazTamir** [comment]
@ebenahar Please fix https://travis-ci.org/red-hat-storage/ocs-ci/jobs/544058652

**Comment by vasukulkarni** [comment]
I think needs rebased on latest master for CI tests to be green.

**Comment by ebenahar** [comment]
Changes are applied here https://github.com/red-hat-storage/ocs-ci/pull/203, closing this PR

**Pull request closed without merging**
