### PR TITLE
Updated the Deployment yamls and Deployment.py based on rook repo changes

### PR DESCRIPTION
**Pull request by nehaberry**
Signed-off-by: Neha Berry <nberry@redhat.com>

The rook [repo](https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph) has made certain changes to following files - See Rook PR https://github.com/rook/rook/pull/3562.

Based on that, updated the common.yaml, operator-openshift.yaml and cluster.yaml. Also updated the deployment.py with corresponding changes.

Note: Change from upstream, made this false:
- name: ROOK_ENABLE_FLEX_DRIVER
          value: "{{ rook_enable_flex_driver | default('false') }}"		          value: "{{ rook_enable_flex_driver | default('false') }}"

Note:
1. Secret **rook-ceph-csi** is now by default created in the openshift-storage project

### CODE REVIEW

**Comment by nehaberry** [comment]
@red-hat-storage/top-level-reviewers should we now take this approach :

As part of deployment itself, crate cephblockpool, and rbd+ cephfs storageclass. 

See [RBD storageclass](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml) now has cephblockpool resource details as well

**Comment by vasukulkarni** [comment]
Please add the same description message you have here in the commit message too.

**Comment by nehaberry** [comment]
**Install succeeded.**

```
-------------------------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------------------------
20:21:29 - MainThread - ocs_ci.ocs.openshift_ops - INFO - Testing access to cluster with /home/nberry/aws-install/aug8-7/auth/kubeconfig
20:21:29 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc cluster-info
20:21:30 - MainThread - ocs_ci.ocs.openshift_ops - INFO - Access to cluster is OK!
PASSED                                                                                                                                                                                                      [100%]

=================================================================================== 1 passed, 73 deselected in 2159.27 seconds ====================================================================================
```
**Pods**

```
(new-ocs-ci) [nberry@localhost ocs-ci]$ oc get cephfilesystem -n openshift-storage
NAME           MDSCOUNT   AGE
ocsci-cephfs   1          19m
(new-ocs-ci) [nberry@localhost ocs-ci]$ oc get pods -n openshift-storage
NAME                                           READY   STATUS      RESTARTS   AGE
csi-cephfsplugin-6ts6k                         2/2     Running     0          23m
csi-cephfsplugin-6wj98                         2/2     Running     0          23m
csi-cephfsplugin-provisioner-0                 3/3     Running     0          23m
csi-cephfsplugin-wghlg                         2/2     Running     0          23m
csi-rbdplugin-bhdmx                            2/2     Running     0          23m
csi-rbdplugin-cb95f                            2/2     Running     0          23m
csi-rbdplugin-provisioner-0                    4/4     Running     0          23m
csi-rbdplugin-rmcqk                            2/2     Running     0          23m
rook-ceph-mds-ocsci-cephfs-a-95678ddc-s5mwv    1/1     Running     0          20m
rook-ceph-mds-ocsci-cephfs-b-fbd4b497c-g87mf   1/1     Running     0          20m
rook-ceph-mgr-a-56d5b6499f-sjtlq               1/1     Running     0          22m
rook-ceph-mon-a-b5d67677-9zp9f                 1/1     Running     0          23m
rook-ceph-mon-b-5c8b9d9d8f-ljjls               1/1     Running     0          22m
rook-ceph-mon-c-78dcdf5659-m5g96               1/1     Running     0          22m
rook-ceph-operator-56488bb8df-hjf9d            1/1     Running     0          25m
rook-ceph-osd-0-fcdb6d999-zjdfn                1/1     Running     0          21m
rook-ceph-osd-1-c7dd8468c-4f72d                1/1     Running     0          21m
rook-ceph-osd-2-5964bfb795-d79nm               1/1     Running     0          20m
rook-ceph-osd-prepare-ip-10-0-138-84-zld8b     0/2     Completed   0          21m
rook-ceph-osd-prepare-ip-10-0-153-99-8tmg7     0/2     Completed   0          21m
rook-ceph-osd-prepare-ip-10-0-171-67-n49dh     0/2     Completed   0          21m
rook-ceph-tools-5f5dc75fd5-pksf9               1/1     Running     0          20m
rook-discover-c7btq                            1/1     Running     0          24m
rook-discover-j5c2s                            1/1     Running     0          24m
rook-discover-n8jzb                            1/1     Running     0          24m

```
**PVCs are created and BOUND**

```
Every 2.0s: oc get pvc; oc get pods                                             Thu Aug  8 20:45:58 2019

NAME	     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS
     AGE
cephfs-pvc   Bound    pvc-fce45b76-b9ee-11e9-a5b7-063d5624272c   1Gi        RWO            csi-cephfs
     3m9s
rbd-pvc      Bound    pvc-76d7f44a-b9ee-11e9-a404-0249fc17487a   1Gi        RWO            rook-ceph-blo
ck   6m54s
NAME                 READY   STATUS    RESTARTS   AGE
csicephfs-demo-pod   1/1     Running   0          2m59s
csirbd-demo-pod      1/1     Running   0          6m40s

```

**Images:**

```

sh-4.2# ceph -v
ceph version 14.2.2 (4f8fa0a0024755aae7d95567c63f11d6862d55be) nautilus (stable)
sh-4.2# rook version
 rook: v1.0.0-344.g9e1a9f6


$ oc describe pod csi-rbdplugin-provisioner-0 -n openshift-storage|grep Image
    Image:         quay.io/k8scsi/csi-provisioner:v1.2.0
    Image ID:      quay.io/k8scsi/csi-provisioner@sha256:0dffe9a8d39c4fdd49c5dd98ca5611a3f9726c012b082946f630e36988ba9f37
    Image:         quay.io/k8scsi/csi-attacher:v1.1.1
    Image ID:      quay.io/k8scsi/csi-attacher@sha256:e4db94969e1d463807162a1115192ed70d632a61fbeb3bdc97b40fe9ce78c831
    Image:         quay.io/k8scsi/csi-snapshotter:v1.1.0
    Image ID:      quay.io/k8scsi/csi-snapshotter@sha256:a49e0da1af6f2bf717e41ba1eee8b5e6a1cbd66a709dd92cc43fe475fe2589eb
    Image:         quay.io/cephcsi/cephcsi:canary
    Image ID:      quay.io/cephcsi/cephcsi@sha256:32f75b99168941ef06d056bc7d6ea269cb9be85ab441a4071aa9525fc4ce254e
[nberry@localhost aug8-6]$ oc describe pod rook-ceph-operator-56488bb8df-hjf9d -n openshift-storage|grep Image
    Image:         rook/ceph:master
    Image ID:      docker.io/rook/ceph@sha256:3a484780f5cd87258db6bc07265e60c8f9b977609b4bce3fdcf9f103389c1eb2
```

**Comment by nehaberry** [comment]
[logs-PR.txt](https://github.com/red-hat-storage/ocs-ci/files/3482541/logs-PR.txt)

**Comment by vasukulkarni** [comment]
@nehaberry commit message needs update - you can add the same thing what you mentioned in description

**Comment by nehaberry** [comment]
> Please add the same description message you have here in the commit message too.

Hi Vasu, I added the same description message in first Commit message. Then since Travis CI failed, I corrected it and pushed a new Commit . Should we keep the PR  description in all commit messages ?

**Comment by petr-balogh** [comment]
Thanks!

**Pull request merged**
