### PR TITLE
Revert MCG tier 4 timeout extensions

### LINKED ISSUE #5202: test_noobaa_sts_host_node_failure[noobaa-core-False] OBC health check timeout should be reduced
The timeout was increased in #5146 due to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=2028559)
Once the bug is fixed, we should lower the timeout accordingly 

The same applies to #5195, #5196

### PR DESCRIPTION
**Pull request by Neon-White**
Fixes #5202

### CODE REVIEW

**Review by parikshithb — APPROVED** [review]

**Review by mbukatov — APPROVED** [review]

**Review by ebenahar — APPROVED** [review]

**Review by keesturam — APPROVED** [review]
LGTM

**Comment by keesturam** [comment]
The PR isn't working as expected. Some rework maybe needed after running the tests.

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7364/320363/320370/320374/log
Run ID: 1670509372
Test Case: test_validate_ceph_config_values_in_rook_config_override
ODF Build: 4.12.0-130
OCP Version: 4.12
Job name: IBM Cloud IPI 3AZ RHCOS 3M 3W tier1
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6343/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-005ici3c33-t1/j-005ici3c33-t1_20221208T130227/logs/
Error Message: ```AssertionError: The Ceph config, set by rook-config-override is different than the expected. Please inform OCS-QE about this discrepancy. The expected values ar```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7100/296186/296193/296197/log
Run ID: 1670263326
Test Case: test_validate_ceph_config_values_in_rook_config_override
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: AWS UPI Disconnected 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6300/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-066aud3c33-ua/j-066aud3c33-ua_20221205T121524/logs/
Error Message: ```AssertionError: The Ceph config, set by rook-config-override is different than the expected. Please inform OCS-QE about this discrepancy. The expected values ar```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7051/295489/295504/295507/log
Run ID: 1670222569
Test Case: test_recovery_from_volume_deletion
ODF Build: 4.12.0-125
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS LOWERREQ VSAN 3M 3W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6298/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/vavuthulwreq-t4a/vavuthulwreq-t4a_20221205T051247/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 daemons have recently crashed"```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7015/292448/292455/292459/log
Run ID: 1670007275
Test Case: test_ceph_default_values_check
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: AZURE IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6280/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-004zi3c33-uba/j-004zi3c33-uba_20221202T083924/logs/
Error Message: ```failed on setup with "OSError: [Errno 12] Cannot allocate memory"```

**Pull request closed without merging**
