### PR TITLE
Fix for get_ceph_default_replica returning None value.

### PR DESCRIPTION
**Pull request by pintojoy**
In OCS4.9, 'ceph status' doesnot give replica count value. Hence 'ceph mgr dump' command is used.

### CODE REVIEW

**Comment by keesturam** [comment]
LGTM. Please run validation on both 4.8 and 4.9 to make sure this change doesn't break previous versions.

**Review by keesturam — DISMISSED** [review]

**Review by keesturam — APPROVED** [review]
LGTM

**Review by ramkiperiy — APPROVED** [review]
LGTM

**Review by tiffanyn108 — APPROVED** [review]
LGTM.

**Pull request merged**
