### PR TITLE
Check metadata for rbd images created during the test only

### PR DESCRIPTION
**Pull request by rachael-george**
Fixes: #6561 

Signed-off-by: rachael-george <rgeorge@redhat.com>

### CODE REVIEW

**Comment by rachael-george** [comment]
The test case passed in the run above 
Console logs: https://url.corp.redhat.com/ab34883

**Comment by ebenahar** [comment]
@rachael-george does the change keep backward compatibility of ODF and OCP?

**Comment by rachael-george** [comment]
> 

I don't think backward compatibility should be an issue here. The setting of metadata was introduced in 4.11 in ceph-csi, which was then disabled as part of this bug https://bugzilla.redhat.com/show_bug.cgi?id=2099965, so there shouldn't be any metadata either way for regular rbd volumes.
The changes in this PR ensures that we check for metadata only for the RBD volumes created as part of the test and avoids checking metadata for all rbd images in the cluster which can have metadata, for eg: encrypted volumes.

@mashetty330 to keep me honest here

**Comment by mashetty330** [comment]
> > 
> 
> I don't think backward compatibility should be an issue here. The setting of metadata was introduced in 4.11 in ceph-csi, which was then disabled as part of this bug https://bugzilla.redhat.com/show_bug.cgi?id=2099965, so there shouldn't be any metadata either way for regular rbd volumes. The changes in this PR ensures that we check for metadata only for the RBD volumes created as part of the test and avoids checking metadata for all rbd images in the cluster which can have metadata, for eg: encrypted volumes.
> 
> @mashetty330 to keep me honest here

correct @rachael-george

**Review by sidhant-agrawal — APPROVED** [review]
lgtm

**Review by vavuthu — APPROVED** [review]

**Pull request merged**
