### PR TITLE
use fedora and postgres images from quay.io to avoid docker rate limits

### PR DESCRIPTION
**Pull request by vasukulkarni**
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3367
Fixes: https://github.com/red-hat-storage/ocs-ci/issues/3368

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@tiffanyn108 @gitsridhar can you test it out in your environment?

**Review by tiffanyn108 — APPROVED** [review]
LGTM.

**Review by AviadP — APPROVED** [review]

**Comment by tiffanyn108** [comment]
Jenkins validation failed due to cluster deployment failures.

**Review by Avilir — APPROVED** [review]
LGTM

**Comment by tiffanyn108** [comment]
@vasukulkarni Validation passed with pgsql (postgres:10.

**Review by clacroix12 — APPROVED** [review]

**Pull request merged**
