### PR TITLE
Update machine CIDR and take it from config

### PR DESCRIPTION
**Pull request by petr-balogh**
Fixes: #6700

Signed-off-by: Petr Balogh <pbalogh@redhat.com>

### CODE REVIEW

**Comment by petr-balogh** [comment]
Verification job triggered here: https://url.corp.redhat.com/c27c547

**Review by clacroix12 — DISMISSED** [review]

**Comment by petr-balogh** [comment]
changed CIDR to /15 and trying verify once more here:
https://url.corp.redhat.com/dbe2501

**Comment by petr-balogh** [comment]
I see it didn't failed right after openshift-installer was triggered as in previous attempts. So, marking as verified here:
https://url.corp.redhat.com/9bcd521

**Review by clacroix12 — APPROVED** [review]

**Review by shylesh — APPROVED** [review]
Lgtm

**Pull request merged**
